import './abbr/define';
import './abs/define';
import './ceil/define';
import './clamp/define';
import './downto/define';
import './exp/define';
import './floor/define';
import './format/define';
import './isEven/define';
import './isFinite/define';
import './isInteger/define';
import './isMultipleOf/define';
import './isNaN/define';
import './isOdd/define';
import './isSafeInteger/define';
import './log/define';
import './pad/define';
import './pow/define';
import './random/define';
import './range/define';
import './round/define';
import './sqrt/define';
import './times/define';
import './toChar/define';
import './toHex/define';
import './toOrdinal/define';
import './trunc/define';
import './upto/define';

export * from '../core/number';
export { default } from '../core/number';
