var j=true,k=null,m=false;function o(a){return function(){return a}}var r=Object,s=Array,t=RegExp,u=Date,v=String,w=Number,x=Math,y="Array,Boolean,Date,Function,Number,String,RegExp".split(","),aa=z(y[0]),ba=z(y[1]),ca=z(y[2]),D=z(y[3]),E=z(y[4]),F=z(y[5]),G=z(y[6]);function z(a){return function(b){return da(b,a)}}
function ea(a){if(!a.SugarMethods){fa(a,"SugarMethods",{});H(a,m,m,{restore:function(){var b=arguments.length===0,c=I(arguments);J(a.SugarMethods,function(d,e){if(b||c.indexOf(d)>-1)fa(e.Aa?a.prototype:a,d,e.method)})},extend:function(b,c,d){H(a,d!==m,c,b)}})}}var ga=typeof global!=="undefined"?global:this,ha=r.defineProperty&&r.defineProperties;
function H(a,b,c,d){var e=b?a.prototype:a,g;ea(a);J(d,function(f,i){g=e[f];if(typeof c==="function")i=ia(e[f],i,c);if(c!==m||!e[f])fa(e,f,i);a.SugarMethods[f]={Aa:b,method:i,Ha:g}})}function ia(a,b,c){return function(){return a&&(c===j||!c.apply(this,arguments))?a.apply(this,arguments):b.apply(this,arguments)}}function fa(a,b,c){if(ha)r.defineProperty(a,b,{value:c,configurable:j,enumerable:m,writable:j});else a[b]=c}
function K(a,b,c,d,e){var g={};d=F(d)?d.split(","):d;d.forEach(function(f,i){e(g,f,i)});H(a,b,c,g)}function I(a,b){var c=[],d=0;for(d=0;d<a.length;d++){c.push(a[d]);b&&b.call(a,a[d],d)}return c}function L(a){return a!==void 0}function M(a){return a===void 0}function ja(a){return a&&typeof a==="object"}function ka(a){return!!a&&da(a,"Object")&&v(a.constructor)===v(r)}function la(a,b){return r.hasOwnProperty.call(a,b)}function da(a,b){return r.prototype.toString.call(a)==="[object "+b+"]"}
function J(a,b){for(var c in a)if(la(a,c))if(b.call(a,c,a[c])===m)break}function ma(a,b){J(b,function(c){a[c]=b[c]});return a}function na(a){return a.slice(0,1).toUpperCase()+a.slice(1)}function N(a,b,c,d){var e=[];a=parseInt(a);for(var g=d<0;!g&&a<=b||g&&a>=b;){e.push(a);c&&c.call(this,a);a+=d||1}return e}function O(a,b,c){c=x[c||"round"];var d=x.pow(10,x.abs(b||0));if(b<0)d=1/d;return c(a*d)/d}function P(a,b){return O(a,b,"floor")}
function oa(){return"\t\n\u000b\u000c\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff"}function pa(a,b){return s(x.max(0,L(a)?a:1)+1).join(b||"")}function Q(a,b,c,d){d=x.abs(a).toString(d||10);d=pa(b-d.replace(/\.\d+/,"").length,"0")+d;if(c||a<0)d=(a<0?"-":"+")+d;return d}function ra(a){if(a>=11&&a<=13)return"th";else switch(a%10){case 1:return"st";case 2:return"nd";case 3:return"rd";default:return"th"}}
function sa(a,b){var c=a.toString().match(/[^/]*$/)[0];if(b)c=(c+b).split("").sort().join("").replace(/([gimy])\1+/g,"$1");return c}function R(a){F(a)||(a=v(a));return a.replace(/([\\/'*+?|()\[\]{}.^$])/g,"\\$1")}
function S(a,b){var c,d,e,g,f,i,h=typeof a;if(h==="string")return a;d=r.prototype.toString.call(a);c=d==="[object Object]";e=d==="[object Array]";if(a!=k&&c||e){b||(b=[]);if(b.length>1)for(f=b.length;f--;)if(b[f]===a)return"CYC";b.push(a);c=v(a.constructor);g=e?a:r.keys(a).sort();for(f=0;f<g.length;f++){i=e?f:g[f];c+=i+S(a[i],b)}b.pop()}else c=1/a===-Infinity?"-0":v(a&&a.valueOf());return h+d+c}
function ta(a,b,c){var d=[],e=a.length,g=b[b.length-1]!==m,f;I(b,function(i){if(ba(i))return m;if(g){i%=e;if(i<0)i=e+i}f=c?a.charAt(i)||"":a[i];d.push(f)});return d.length<2?d[0]:d}function ua(a,b){K(b,j,m,a,function(c,d){c[d+(d==="equal"?"s":"")]=function(){return r[d].apply(k,[this].concat(I(arguments)))}})}ea(r);J(y,function(a,b){ea(ga[b])});
