var j=true,l=null,m=false;function aa(a){return function(){return a}}var o=Object,p=Array,r=RegExp,s=Date,t=String,u=Number,w=Math,ba=typeof global!=="undefined"?global:this,ca=o.defineProperty&&o.defineProperties;function y(a,b,c,d){var e=b?a.prototype:a,g;da(a);z(d,function(f,i){g=e[f];if(typeof c==="function")i=ea(e[f],i,c);if(c!==m||!e[f])fa(e,f,i);a.SugarMethods[f]={Aa:b,method:i,Ha:g}})}
function da(a){if(!a.SugarMethods){fa(a,"SugarMethods",{});y(a,m,m,{restore:function(){var b=arguments.length===0,c=A(arguments);z(a.SugarMethods,function(d,e){if(b||c.indexOf(d)>-1)fa(e.Aa?a.prototype:a,d,e.method)})},extend:function(b,c,d){y(a,d!==m,c,b)}})}}function ea(a,b,c){return function(){return a&&(c===j||!c.apply(this,arguments))?a.apply(this,arguments):b.apply(this,arguments)}}function fa(a,b,c){if(ca)o.defineProperty(a,b,{value:c,configurable:j,enumerable:m,writable:j});else a[b]=c}
function B(a,b,c,d,e){var g={};d=C(d)?d.split(","):d;d.forEach(function(f,i){e(g,f,i)});y(a,b,c,g)}function A(a,b){var c=[],d=0;for(d=0;d<a.length;d++){c.push(a[d]);b&&b.call(a,a[d],d)}return c}function ga(a,b,c){var d=[],e=a.length,g=b[b.length-1]!==m,f;A(b,function(i){if(ha(i))return m;if(g){i%=e;if(i<0)i=e+i}f=c?a.charAt(i)||"":a[i];d.push(f)});return d.length<2?d[0]:d}function D(a){return a!==void 0}function E(a){return a===void 0}
function ia(a,b){return o.prototype.toString.call(a)==="[object "+b+"]"}function ja(a){return!!a&&ia(a,"Object")&&t(a.constructor)===t(o)}function ka(a){return a&&typeof a==="object"}function la(a,b){return o.hasOwnProperty.call(a,b)}function ma(a,b){B(b,j,m,a,function(c,d){c[d+(d==="equal"?"s":"")]=function(){return o[d].apply(l,[this].concat(A(arguments)))}})}function z(a,b){for(var c in a)if(la(a,c))if(b.call(a,c,a[c])===m)break}function na(a,b){a.split(",").forEach(b)}
function oa(a,b){z(b,function(c){a[c]=b[c]});return a}function F(a){return a.slice(0,1).toUpperCase()+a.slice(1)}
function H(a,b){var c,d,e,g,f,i,h=typeof a;if(h==="string")return a;d=o.prototype.toString.call(a);c=d==="[object Object]";e=d==="[object Array]";if(a!=l&&c||e){b||(b=[]);if(b.length>1)for(f=b.length;f--;)if(b[f]===a)return"CYC";b.push(a);c=t(a.constructor);g=e?a:o.keys(a).sort();for(f=0;f<g.length;f++){i=e?f:g[f];c+=i+H(a[i],b)}b.pop()}else c=1/a===-Infinity?"-0":t(a&&a.valueOf());return h+d+c}
var I="Array,Boolean,Date,Function,Number,String,RegExp".split(","),pa=J(I[0]),ha=J(I[1]),ra=J(I[2]),K=J(I[3]),L=J(I[4]),C=J(I[5]),N=J(I[6]);function J(a){return function(b){return ia(b,a)}}function O(a,b,c,d){var e=[];a=parseInt(a);for(var g=d<0;!g&&a<=b||g&&a>=b;){e.push(a);c&&c.call(this,a);a+=d||1}return e}function P(a,b,c){c=w[c||"round"];var d=w.pow(10,w.abs(b||0));if(b<0)d=1/d;return c(a*d)/d}function Q(a,b){return P(a,b,"floor")}
function sa(){return"\t\n\u000b\u000c\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff"}function ta(a,b){return p(w.max(0,D(a)?a:1)+1).join(b||"")}function R(a,b,c,d){d=w.abs(a).toString(d||10);d=ta(b-d.replace(/\.\d+/,"").length,"0")+d;if(c||a<0)d=(a<0?"-":"+")+d;return d}function ua(a){if(a>=11&&a<=13)return"th";else switch(a%10){case 1:return"st";case 2:return"nd";case 3:return"rd";default:return"th"}}
function va(a,b){var c=a.toString().match(/[^/]*$/)[0];if(b)c=(c+b).split("").sort().join("").replace(/([gimy])\1+/g,"$1");return c}function S(a){C(a)||(a=t(a));return a.replace(/([\\/'*+?|()\[\]{}.^$])/g,"\\$1")}da(o);z(I,function(a,b){da(ba[b])});
