function ya(a,b,c,d){var e=k;if(a===b)return k;else if(C(b)&&B(a))return r(b).test(a);else if(z(b))return b.apply(c,d);else if(M(b)&&ka(a)){H(b,function(h){ya(a[h],b[h],c,[a[h],a])||(e=m)});return e}else return ra(a)&&ra(b)?T(a)===T(b):a===b}function U(a,b,c,d){return K(b)?a:z(b)?b.apply(c,d||[]):z(a[b])?a[b].call(a):a[b]}
function V(a,b,c,d){var e,h;if(c<0)c=a.length+c;h=isNaN(c)?0:c;for(c=d===k?a.length+h:a.length;h<c;){e=h%a.length;if(e in a){if(b.call(a,a[e],e,a)===m)break}else return za(a,b,h,d);h++}}function za(a,b,c){var d=[],e;for(e in a)e in a&&e>>>0==e&&e!=4294967295&&e>=c&&d.push(parseInt(e));d.sort().each(function(h){return b.call(a,a[h],h,a)});return a}function Aa(a,b,c,d,e){var h,f;V(a,function(i,g,j){if(ya(i,b,j,[i,g,j])){h=i;f=g;return m}},c,d);return e?f:h}
function Ba(a,b){var c=[],d={},e;V(a,function(h,f){e=b?U(h,b,a,[h,f,a]):h;Ea(d,e)||c.push(h)});return c}function Fa(a,b,c){var d=[],e={};b.each(function(h){Ea(e,h)});a.each(function(h){var f=T(h),i=!ra(h);if(Ga(e,f,h,i)!=c){var g=0;if(i)for(f=e[f];g<f.length;)if(f[g]===h)f.splice(g,1);else g+=1;else delete e[f];d.push(h)}});return d}function Ha(a,b,c){b=b||Infinity;c=c||0;var d=[];V(a,function(e){if(ea(e)&&c<b)d=d.concat(Ha(e,b,c+1));else d.push(e)});return d}
function Ia(a){var b=[];E(a,function(c){b=b.concat(c)});return b}function Ga(a,b,c,d){var e=b in a;if(d){a[b]||(a[b]=[]);e=a[b].indexOf(c)!==-1}return e}function Ea(a,b){var c=T(b),d=!ra(b),e=Ga(a,c,b,d);if(d)a[c].push(b);else a[c]=b;return e}function Ja(a,b,c,d){var e,h=[],f=c==="max",i=c==="min",g=Array.isArray(a);H(a,function(j){var n=a[j];j=U(n,b,a,g?[n,parseInt(j),a]:[]);if(j===e)h.push(n);else if(K(e)||f&&j>e||i&&j<e){h=[n];e=j}});g||(h=Ha(h,1));return d?h:h[0]}
function Ka(a){if(q[La])a=a.toLowerCase();return a.replace(q[Ma],"")}function Na(a,b){var c=a.charAt(b);return(q[Oa]||{})[c]||c}function Pa(a){var b=q[Qa];return a?b.indexOf(a):l}var Qa="AlphanumericSortOrder",Ma="AlphanumericSortIgnore",La="AlphanumericSortIgnoreCase",Oa="AlphanumericSortEquivalents";D(q,m,m,{create:function(){var a=[];E(arguments,function(b){if(ka(b))a=a.concat(q.prototype.slice.call(b));else a.push(b)});return a}});
D(q,k,m,{find:function(a,b,c){return Aa(this,a,b,c)},findAll:function(a,b,c){var d=[];V(this,function(e,h,f){ya(e,a,f,[e,h,f])&&d.push(e)},b,c);return d},findIndex:function(a,b,c){a=Aa(this,a,b,c,k);return K(a)?-1:a},count:function(a){if(K(a))return this.length;return this.findAll(a).length},removeAt:function(a,b){if(K(a))return this;if(K(b))b=a;for(var c=0;c<=b-a;c++)this.splice(a,1);return this},include:function(a,b){return this.clone().add(a,b)},exclude:function(){return q.prototype.remove.apply(this.clone(),
arguments)},clone:function(){return ma([],this)},unique:function(a){return Ba(this,a)},flatten:function(a){return Ha(this,a)},union:function(){return Ba(this.concat(Ia(arguments)))},intersect:function(){return Fa(this,Ia(arguments),m)},subtract:function(){return Fa(this,Ia(arguments),k)},at:function(){return sa(this,arguments)},first:function(a){if(K(a))return this[0];if(a<0)a=0;return this.slice(0,a)},last:function(a){if(K(a))return this[this.length-1];return this.slice(this.length-a<0?0:this.length-
a)},from:function(a){return this.slice(a)},to:function(a){if(K(a))a=this.length;return this.slice(0,a)},min:function(a,b){return Ja(this,a,"min",b)},max:function(a,b){return Ja(this,a,"max",b)},least:function(a,b){return Ja(this.groupBy.apply(this,[a]),"length","min",b)},most:function(a,b){return Ja(this.groupBy.apply(this,[a]),"length","max",b)},sum:function(a){a=a?this.map(a):this;return a.length>0?a.reduce(function(b,c){return b+c}):0},average:function(a){a=a?this.map(a):this;return a.length>0?
a.sum()/a.length:0},inGroups:function(a,b){var c=arguments.length>1,d=this,e=[],h=P(this.length/a,void 0,"ceil");O(0,a-1,function(f){f=f*h;var i=d.slice(f,f+h);c&&i.length<h&&O(1,h-i.length,function(){i=i.add(b)});e.push(i)});return e},inGroupsOf:function(a,b){var c=[],d=this.length,e=this,h;if(d===0||a===0)return e;if(K(a))a=1;if(K(b))b=l;O(0,P(d/a,void 0,"ceil")-1,function(f){for(h=e.slice(a*f,a*f+a);h.length<a;)h.push(b);c.push(h)});return c},isEmpty:function(){return this.compact().length==0},
sortBy:function(a,b){var c=this.clone();c.sort(function(d,e){var h,f;h=U(d,a,c,[d]);f=U(e,a,c,[e]);if(B(h)&&B(f)){h=h;f=f;var i,g,j,n,o=0,u=0;h=Ka(h);f=Ka(f);do{j=Na(h,o);n=Na(f,o);i=Pa(j);g=Pa(n);if(i===-1||g===-1){i=h.charCodeAt(o)||l;g=f.charCodeAt(o)||l}j=j!==h.charAt(o);n=n!==f.charAt(o);if(j!==n&&u===0)u=j-n;o+=1}while(i!=l&&g!=l&&i===g);h=i===g?u:i<g?-1:1}else h=h<f?-1:h>f?1:0;return h*(b?-1:1)});return c},randomize:function(){for(var a=this.concat(),b,c,d=a.length;d;b=parseInt(w.random()*
d),c=a[--d],a[d]=a[b],a[b]=c);return a},zip:function(){var a=E(arguments);return this.map(function(b,c){return[b].concat(a.map(function(d){return c in d?d[c]:l}))})},sample:function(a){var b=[],c=this.clone(),d;if(K(a))a=1;for(;b.length<a;){d=Q(w.random()*(c.length-1));b.push(c[d]);c.removeAt(d);if(c.length==0)break}return arguments.length>0?b:b[0]},each:function(a,b,c){V(this,a,b,c);return this},add:function(a,b){if(!A(v(b))||isNaN(b))b=this.length;q.prototype.splice.apply(this,[b,0].concat(a));
return this},remove:function(){var a,b=this;E(arguments,function(c){for(a=0;a<b.length;)if(ya(b[a],c,b,[b[a],a,b]))b.splice(a,1);else a++});return b},compact:function(a){var b=[];V(this,function(c){if(ea(c))b.push(c.compact());else if(a&&c)b.push(c);else!a&&c!=l&&c.valueOf()===c.valueOf()&&b.push(c)});return b},groupBy:function(a,b){var c=this,d={},e;V(c,function(h,f){e=U(h,a,c,[h,f,c]);d[e]||(d[e]=[]);d[e].push(h)});b&&H(d,b);return d},none:function(){return!this.any.apply(this,arguments)}});
D(q,k,m,{all:q.prototype.every,any:q.prototype.some,insert:q.prototype.add});function Ra(a){if(a&&a.valueOf)a=a.valueOf();return p.keys(a)}function Sa(a,b){I(p,m,m,a,function(c,d){c[d]=function(e,h,f){f=q.prototype[d].call(Ra(e),function(i){return b?U(e[i],h,e,[i,e[i],e]):ya(e[i],h,e,[i,e[i],e])},f);if(ea(f))f=f.reduce(function(i,g){i[g]=e[g];return i},{});return f}});ta(a,N)}
D(p,m,m,{map:function(a,b){return Ra(a).reduce(function(c,d){c[d]=U(a[d],b,a,[d,a[d],a]);return c},{})},reduce:function(a){var b=Ra(a).map(function(c){return a[c]});return b.reduce.apply(b,E(arguments).slice(1))},size:function(a){return Ra(a).length}});(function(){I(q,k,function(){var a=arguments;return a.length>0&&!z(a[0])},"map,every,all,some,any,none,filter",function(a,b){a[b]=function(c){return this[b](function(d,e){return b==="map"?U(d,c,this,[d,e,this]):ya(d,c,this,[d,e,this])})}})})();
(function(){q[Qa]="A\u00c1\u00c0\u00c2\u00c3\u0104BC\u0106\u010c\u00c7D\u010e\u00d0E\u00c9\u00c8\u011a\u00ca\u00cb\u0118FG\u011eH\u0131I\u00cd\u00cc\u0130\u00ce\u00cfJKL\u0141MN\u0143\u0147\u00d1O\u00d3\u00d2\u00d4PQR\u0158S\u015a\u0160\u015eT\u0164U\u00da\u00d9\u016e\u00db\u00dcVWXY\u00ddZ\u0179\u017b\u017d\u00de\u00c6\u0152\u00d8\u00d5\u00c5\u00c4\u00d6".split("").map(function(b){return b+b.toLowerCase()}).join("");var a={};V("A\u00c1\u00c0\u00c2\u00c3\u00c4,C\u00c7,E\u00c9\u00c8\u00ca\u00cb,I\u00cd\u00cc\u0130\u00ce\u00cf,O\u00d3\u00d2\u00d4\u00d5\u00d6,S\u00df,U\u00da\u00d9\u00db\u00dc".split(","),
function(b){var c=b.charAt(0);V(b.slice(1).split(""),function(d){a[d]=c;a[d.toLowerCase()]=c.toLowerCase()})});q[La]=k;q[Oa]=a})();Sa("each,any,all,none,count,find,findAll,isEmpty");Sa("sum,average,min,max,least,most",k);ta("map,reduce,size",N);
