function ya(a,b,c,d){var e=k;if(a===b)return k;else if(C(b)&&B(a))return r(b).test(a);else if(z(b))return b.apply(c,d);else if(la(b)&&ka(a)){H(b,function(g){ya(a[g],b[g],c,[a[g],a])||(e=m)});return e}else return S(a)===S(b)}function T(a,b,c,d){return K(b)?a:z(b)?b.apply(c,d||[]):z(a[b])?a[b].call(a):a[b]}function U(a,b,c,d){var e,g;if(c<0)c=a.length+c;g=isNaN(c)?0:c;for(c=d===k?a.length+g:a.length;g<c;){e=g%a.length;if(e in a){if(b.call(a,a[e],e,a)===m)break}else return za(a,b,g,d);g++}}
function za(a,b,c){var d=[],e;for(e in a)e in a&&e>>>0==e&&e!=4294967295&&e>=c&&d.push(parseInt(e));d.sort().each(function(g){return b.call(a,a[g],g,a)});return a}function Aa(a,b,c,d,e){var g,f;U(a,function(i,h,j){if(ya(i,b,j,[i,h,j])){g=i;f=h;return m}},c,d);return e?f:g}function Ba(a,b){var c=[],d={},e,g;U(a,function(f,i){g=b?T(f,b,a,[f,i,a]):f;e=S(g);if(!(e in d&&(typeof f!=="function"||f===d[e]))){d[e]=g;c.push(f)}});return c}
function Ea(a,b,c){var d=[],e={};b.each(function(g){e[S(g)]=g});a.each(function(g){var f=S(g);if((f in e&&(typeof g!=="function"||g===e[f]))!=c){delete e[f];d.push(g)}});return d}function Fa(a,b,c){b=b||Infinity;c=c||0;var d=[];U(a,function(e){if(da(e)&&c<b)d=d.concat(Fa(e,b,c+1));else d.push(e)});return d}function Ga(a){var b=[];E(a,function(c){b=b.concat(c)});return b}
function Ha(a,b,c,d){var e,g=[],f=c==="max",i=c==="min",h=Array.isArray(a);H(a,function(j){var n=a[j];j=T(n,b,a,h?[n,parseInt(j),a]:[]);if(j===e)g.push(n);else if(K(e)||f&&j>e||i&&j<e){g=[n];e=j}});h||(g=Fa(g,1));return d?g:g[0]}function Ia(a){if(q[Ja])a=a.toLowerCase();return a.replace(q[Ka],"")}function La(a,b){var c=a.charAt(b);return(q[Ma]||{})[c]||c}function Na(a){var b=q[Oa];return a?b.indexOf(a):l}
var Oa="AlphanumericSortOrder",Ka="AlphanumericSortIgnore",Ja="AlphanumericSortIgnoreCase",Ma="AlphanumericSortEquivalents";D(q,m,m,{create:function(){var a=[];E(arguments,function(b){if(ka(b))a=a.concat(q.prototype.slice.call(b));else a.push(b)});return a}});
D(q,k,m,{find:function(a,b,c){return Aa(this,a,b,c)},findAll:function(a,b,c){var d=[];U(this,function(e,g,f){ya(e,a,f,[e,g,f])&&d.push(e)},b,c);return d},findIndex:function(a,b,c){a=Aa(this,a,b,c,k);return K(a)?-1:a},count:function(a){if(K(a))return this.length;return this.findAll(a).length},removeAt:function(a,b){if(K(a))return this;if(K(b))b=a;for(var c=0;c<=b-a;c++)this.splice(a,1);return this},include:function(a,b){return this.clone().add(a,b)},exclude:function(){return q.prototype.remove.apply(this.clone(),
arguments)},clone:function(){return na([],this)},unique:function(a){return Ba(this,a)},flatten:function(a){return Fa(this,a)},union:function(){return Ba(this.concat(Ga(arguments)))},intersect:function(){return Ea(this,Ga(arguments),m)},subtract:function(){return Ea(this,Ga(arguments),k)},at:function(){return sa(this,arguments)},first:function(a){if(K(a))return this[0];if(a<0)a=0;return this.slice(0,a)},last:function(a){if(K(a))return this[this.length-1];return this.slice(this.length-a<0?0:this.length-
a)},from:function(a){return this.slice(a)},to:function(a){if(K(a))a=this.length;return this.slice(0,a)},min:function(a,b){return Ha(this,a,"min",b)},max:function(a,b){return Ha(this,a,"max",b)},least:function(a,b){return Ha(this.groupBy.apply(this,[a]),"length","min",b)},most:function(a,b){return Ha(this.groupBy.apply(this,[a]),"length","max",b)},sum:function(a){a=a?this.map(a):this;return a.length>0?a.reduce(function(b,c){return b+c}):0},average:function(a){a=a?this.map(a):this;return a.length>0?
a.sum()/a.length:0},inGroups:function(a,b){var c=arguments.length>1,d=this,e=[],g=O(this.length/a,void 0,"ceil");N(0,a-1,function(f){f=f*g;var i=d.slice(f,f+g);c&&i.length<g&&N(1,g-i.length,function(){i=i.add(b)});e.push(i)});return e},inGroupsOf:function(a,b){var c=[],d=this.length,e=this,g;if(d===0||a===0)return e;if(K(a))a=1;if(K(b))b=l;N(0,O(d/a,void 0,"ceil")-1,function(f){for(g=e.slice(a*f,a*f+a);g.length<a;)g.push(b);c.push(g)});return c},isEmpty:function(){return this.compact().length==0},
sortBy:function(a,b){var c=this.clone();c.sort(function(d,e){var g,f;g=T(d,a,c,[d]);f=T(e,a,c,[e]);if(B(g)&&B(f)){g=g;f=f;var i,h,j,n,o=0,u=0;g=Ia(g);f=Ia(f);do{j=La(g,o);n=La(f,o);i=Na(j);h=Na(n);if(i===-1||h===-1){i=g.charCodeAt(o)||l;h=f.charCodeAt(o)||l}j=j!==g.charAt(o);n=n!==f.charAt(o);if(j!==n&&u===0)u=j-n;o+=1}while(i!=l&&h!=l&&i===h);g=i===h?u:i<h?-1:1}else g=g<f?-1:g>f?1:0;return g*(b?-1:1)});return c},randomize:function(){for(var a=this.concat(),b,c,d=a.length;d;b=parseInt(w.random()*
d),c=a[--d],a[d]=a[b],a[b]=c);return a},zip:function(){var a=E(arguments);return this.map(function(b,c){return[b].concat(a.map(function(d){return c in d?d[c]:l}))})},sample:function(a){var b=[],c=this.clone(),d;if(K(a))a=1;for(;b.length<a;){d=P(w.random()*(c.length-1));b.push(c[d]);c.removeAt(d);if(c.length==0)break}return arguments.length>0?b:b[0]},each:function(a,b,c){U(this,a,b,c);return this},add:function(a,b){if(!A(v(b))||isNaN(b))b=this.length;q.prototype.splice.apply(this,[b,0].concat(a));
return this},remove:function(){var a,b=this;E(arguments,function(c){for(a=0;a<b.length;)if(ya(b[a],c,b,[b[a],a,b]))b.splice(a,1);else a++});return b},compact:function(a){var b=[];U(this,function(c){if(da(c))b.push(c.compact());else if(a&&c)b.push(c);else!a&&c!=l&&c.valueOf()===c.valueOf()&&b.push(c)});return b},groupBy:function(a,b){var c=this,d={},e;U(c,function(g,f){e=T(g,a,c,[g,f,c]);d[e]||(d[e]=[]);d[e].push(g)});b&&H(d,b);return d},none:function(){return!this.any.apply(this,arguments)}});
D(q,k,m,{all:q.prototype.every,any:q.prototype.some,insert:q.prototype.add});function Pa(a){if(a&&a.valueOf)a=a.valueOf();return p.keys(a)}function Qa(a,b){I(p,m,m,a,function(c,d){c[d]=function(e,g,f){f=q.prototype[d].call(Pa(e),function(i){return b?T(e[i],g,e,[i,e[i],e]):ya(e[i],g,e,[i,e[i],e])},f);if(da(f))f=f.reduce(function(i,h){i[h]=e[h];return i},{});return f}});ta(a,M)}
D(p,m,m,{map:function(a,b){return Pa(a).reduce(function(c,d){c[d]=T(a[d],b,a,[d,a[d],a]);return c},{})},reduce:function(a){var b=Pa(a).map(function(c){return a[c]});return b.reduce.apply(b,E(arguments).slice(1))},size:function(a){return Pa(a).length}});(function(){I(q,k,function(){var a=arguments;return a.length>0&&!z(a[0])},"map,every,all,some,any,none,filter",function(a,b){a[b]=function(c){return this[b](function(d,e){return b==="map"?T(d,c,this,[d,e,this]):ya(d,c,this,[d,e,this])})}})})();
(function(){q[Oa]="A\u00c1\u00c0\u00c2\u00c3\u0104BC\u0106\u010c\u00c7D\u010e\u00d0E\u00c9\u00c8\u011a\u00ca\u00cb\u0118FG\u011eH\u0131I\u00cd\u00cc\u0130\u00ce\u00cfJKL\u0141MN\u0143\u0147\u00d1O\u00d3\u00d2\u00d4PQR\u0158S\u015a\u0160\u015eT\u0164U\u00da\u00d9\u016e\u00db\u00dcVWXY\u00ddZ\u0179\u017b\u017d\u00de\u00c6\u0152\u00d8\u00d5\u00c5\u00c4\u00d6".split("").map(function(b){return b+b.toLowerCase()}).join("");var a={};U("A\u00c1\u00c0\u00c2\u00c3\u00c4,C\u00c7,E\u00c9\u00c8\u00ca\u00cb,I\u00cd\u00cc\u0130\u00ce\u00cf,O\u00d3\u00d2\u00d4\u00d5\u00d6,S\u00df,U\u00da\u00d9\u00db\u00dc".split(","),
function(b){var c=b.charAt(0);U(b.slice(1).split(""),function(d){a[d]=c;a[d.toLowerCase()]=c.toLowerCase()})});q[Ja]=k;q[Ma]=a})();Qa("each,any,all,none,count,find,findAll,isEmpty");Qa("sum,average,min,max,least,most",k);ta("map,reduce,size",M);
