var k=true,l=null,m=false;function ba(a){return function(){return a}}var p=Object,q=Array,r=RegExp,s=Date,t=String,v=Number,w=Math,ca=typeof global!=="undefined"?global:this,da=p.defineProperty&&p.defineProperties,x="Array,Boolean,Date,Function,Number,String,RegExp".split(","),ea=y(x[0]),fa=y(x[1]),ga=y(x[2]),z=y(x[3]),A=y(x[4]),B=y(x[5]),C=y(x[6]);function y(a){return function(b){return p.prototype.toString.call(b)==="[object "+a+"]"}}
function ha(a){if(!a.SugarMethods){ia(a,"SugarMethods",{});D(a,m,m,{restore:function(){var b=arguments.length===0,c=E(arguments);H(a.SugarMethods,function(d,e){if(b||c.indexOf(d)>-1)ia(e.ya?a.prototype:a,d,e.method)})},extend:function(b,c,d){D(a,d!==m,c,b)}})}}function D(a,b,c,d){var e=b?a.prototype:a,h;ha(a);H(d,function(f,i){h=e[f];if(typeof c==="function")i=ja(e[f],i,c);if(c!==m||!e[f])ia(e,f,i);a.SugarMethods[f]={ya:b,method:i,Ga:h}})}
function I(a,b,c,d,e){var h={};d=B(d)?d.split(","):d;d.forEach(function(f,i){e(h,f,i)});D(a,b,c,h)}function ja(a,b,c){return function(){return a&&(c===k||!c.apply(this,arguments))?a.apply(this,arguments):b.apply(this,arguments)}}function ia(a,b,c){if(da)p.defineProperty(a,b,{value:c,configurable:k,enumerable:m,writable:k});else a[b]=c}function E(a,b){var c=[],d=0;for(d=0;d<a.length;d++){c.push(a[d]);b&&b.call(a,a[d],d)}return c}function J(a){return a!==void 0}function K(a){return a===void 0}
function ka(a){return a&&typeof a==="object"}function M(a){return!!a&&p.prototype.toString.call(a)==="[object Object]"&&"hasOwnProperty"in a}function la(a,b){return p.hasOwnProperty.call(a,b)}function H(a,b){for(var c in a)if(la(a,c))if(b.call(a,c,a[c])===m)break}function ma(a,b){H(b,function(c){a[c]=b[c]});return a}function N(a){ma(this,a)}N.prototype.constructor=p;function O(a,b,c,d){var e=[];a=parseInt(a);for(var h=d<0;!h&&a<=b||h&&a>=b;){e.push(a);c&&c.call(this,a);a+=d||1}return e}
function P(a,b,c){c=w[c||"round"];var d=w.pow(10,w.abs(b||0));if(b<0)d=1/d;return c(a*d)/d}function Q(a,b){return P(a,b,"floor")}function R(a,b,c,d){d=w.abs(a).toString(d||10);d=na(b-d.replace(/\.\d+/,"").length,"0")+d;if(c||a<0)d=(a<0?"-":"+")+d;return d}function oa(a){if(a>=11&&a<=13)return"th";else switch(a%10){case 1:return"st";case 2:return"nd";case 3:return"rd";default:return"th"}}
function pa(){return"\t\n\u000b\u000c\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u2028\u2029\u3000\ufeff"}function na(a,b){return q(w.max(0,J(a)?a:1)+1).join(b||"")}function qa(a,b){var c=a.toString().match(/[^/]*$/)[0];if(b)c=(c+b).split("").sort().join("").replace(/([gimy])\1+/g,"$1");return c}function S(a){B(a)||(a=t(a));return a.replace(/([\\/'*+?|()\[\]{}.^$])/g,"\\$1")}
function T(a,b){var c=typeof a,d,e,h,f,i,g;if(c==="string")return a;h=p.prototype.toString.call(a);d=M(a);e=h==="[object Array]";if(a!=l&&d||e){b||(b=[]);if(b.length>1)for(g=b.length;g--;)if(b[g]===a)return"CYC";b.push(a);d=t(a.constructor);f=e?a:p.keys(a).sort();for(g=0;g<f.length;g++){i=e?g:f[g];d+=i+T(a[i],b)}b.pop()}else d=1/a===-Infinity?"-0":t(a&&a.valueOf?a.valueOf():a);return c+h+d}
function ra(a){var b=p.prototype.toString.call(a);return b==="[object Date]"||b==="[object Array]"||b==="[object String]"||b==="[object Number]"||b==="[object RegExp]"||b==="[object Boolean]"||b==="[object Arguments]"||M(a)}function sa(a,b,c){var d=[],e=a.length,h=b[b.length-1]!==m,f;E(b,function(i){if(fa(i))return m;if(h){i%=e;if(i<0)i=e+i}f=c?a.charAt(i)||"":a[i];d.push(f)});return d.length<2?d[0]:d}
function ta(a,b){I(b,k,m,a,function(c,d){c[d+(d==="equal"?"s":"")]=function(){return p[d].apply(l,[this].concat(E(arguments)))}})}ha(p);H(x,function(a,b){ha(ca[b])});
