var V,Ta,Ua=["ampm","hour","minute","second","ampm","utc","offset_sign","offset_hours","offset_minutes","ampm"],Va="({t})?\\s*(\\d{1,2}(?:[,.]\\d+)?)(?:{h}(\\d{1,2}(?:[,.]\\d+)?)?{m}(?::?(\\d{1,2}(?:[,.]\\d+)?){s})?\\s*(?:({t})|(Z)|(?:([+-])(\\d{2,2})(?::?(\\d{2,2}))?)?)?|\\s*({t}))",Wa={},Xa,Ya,W,Za=[],$a=[{ba:"f{1,4}|ms|milliseconds",format:function(a){return a.getMilliseconds()}},{ba:"ss?|seconds",format:function(a){return a.getSeconds()}},{ba:"mm?|minutes",format:function(a){return a.getMinutes()}},
{ba:"hh?|hours|12hr",format:function(a){a=a.getHours(void 0);return a===0?12:a-P(a/13)*12}},{ba:"HH?|24hr",format:function(a){return a.getHours()}},{ba:"dd?|date|day",format:function(a){return a.getDate()}},{ba:"dow|weekday",na:k,format:function(a,b,c){return b.weekdays[a.getDay()+(c-1)*7]}},{ba:"MM?",format:function(a){return a.getMonth()+1}},{ba:"mon|month",na:k,format:function(a,b,c){return b.months[a.getMonth()+(c-1)*12]}},{ba:"y{2,4}|year",format:function(a){return a.getFullYear()}},{ba:"[Tt]{1,2}",
format:function(a,b,c,d){a=b.ampm[P(a.getHours()/12)];if(d.length===1)a=a.slice(0,1);if(d.slice(0,1)==="T")a=a.toUpperCase();return a}},{ba:"z{1,4}|tz|timezone",text:k,format:function(a,b,c,d){a=a.getUTCOffset();if(d=="z"||d=="zz")a=a.replace(/(\d{2})(\d{2})/,function(e,g){return Q(g,d.length)});return a}},{ba:"iso(tz|timezone)",format:function(a){return a.getUTCOffset(k)}},{ba:"ord",format:function(a){a=a.getDate();return a+pa(a)}}],ab=[{$:"year",method:"FullYear",ja:k,da:function(a){return(365+
(a?a.isLeapYear()?1:0:0.25))*24*60*60*1E3}},{$:"month",method:"Month",ja:k,da:function(a,b){var c=30.4375,d;if(a){d=a.daysInMonth();if(b<=d.days())c=d}return c*24*60*60*1E3}},{$:"week",method:"Week",da:aa(6048E5)},{$:"day",method:"Date",ja:k,da:aa(864E5)},{$:"hour",method:"Hours",da:aa(36E5)},{$:"minute",method:"Minutes",da:aa(6E4)},{$:"second",method:"Seconds",da:aa(1E3)},{$:"millisecond",method:"Milliseconds",da:aa(1)}],bb={};function cb(a){na(this,a);this.ga=Za.concat()}
cb.prototype={getMonth:function(a){return A(a)?a-1:this.months.indexOf(a)%12},ka:function(a){return this.weekdays.indexOf(a)%7},qa:function(a){var b;return A(a)?a:a&&(b=this.numbers.indexOf(a))!==-1?(b+1)%10:1},wa:function(a){var b=this;return a.replace(r(this.num,"g"),function(c){return b.qa(c)||""})},ua:function(a){return V.units[this.units.indexOf(a)%8]},Da:function(a){return this.pa(a,a[2]>0?"future":"past")},ta:function(a){return this.pa(db(a),"duration")},xa:function(a){a=a||this.code;return a===
"en"||a==="en-US"?k:this.variant},Aa:function(a){return a===this.ampm[0]},Ba:function(a){return a===this.ampm[1]},pa:function(a,b){var c=a[0],d=a[1],e=a[2],g,f,i;if(this.code=="ru"){i=c.toString().slice(-1);switch(k){case i==1:i=1;break;case i>=2&&i<=4:i=2;break;default:i=3}}else i=this.plural&&c>1?1:0;f=this.units[i*8+d]||this.units[d];if(this.capitalizeUnit)f=eb(f);g=this.modifiers.filter(function(h){return h.name=="sign"&&h.value==(e>0?1:-1)})[0];return this[b].replace(/\{(.*?)\}/g,function(h,
j){switch(j){case "num":return c;case "unit":return f;case "sign":return g.src}})},va:function(){return this.oa?[this.oa].concat(this.ga):this.ga},addFormat:function(a,b,c,d,e){var g=c||[],f=this,i;a=a.replace(/\s+/g,"[-,. ]*");a=a.replace(/\{([^,]+?)\}/g,function(h,j){var n=j.match(/\?$/),o=j.match(/(\d)(?:-(\d))?/),u=j.match(/^\d+$/),H=j.replace(/[^a-z]+$/,""),F,L;if(u)F=f.optionals[u[0]];else if(f[H])F=f[H];else if(f[H+"s"]){F=f[H+"s"];if(o){L=[];F.forEach(function(Ca,$){var Da=$%(f.units?8:F.length);
if(Da>=o[1]&&Da<=(o[2]||o[1]))L.push(Ca)});F=L}F=fb(F)}if(u)return"(?:"+F+")?";else{c||g.push(H);return"("+F+")"+(n?"?":"")}});if(b){b=gb(Va,f,e);e=["t","[\\s\\u3000]"].concat(f.timeMarker);i=a.match(/\\d\{\d,\d\}\)+\??$/);hb(f,"(?:"+b+")[,\\s\\u3000]+?"+a,Ua.concat(g),d);hb(f,a+"(?:[,\\s]*(?:"+e.join("|")+(i?"+":"*")+")"+b+")?",g.concat(Ua),d)}else hb(f,a,g,d)}};function ib(a,b){var c;B(a)||(a="");c=bb[a]||bb[a.slice(0,2)];if(b===m&&!c)throw Error("Invalid locale.");return c||Ta}
function jb(a,b){function c(h){var j=f[h];if(B(j))f[h]=j.split(",");else j||(f[h]=[])}function d(h,j){h=h.split("+").map(function(n){return n.replace(/(.+):(.+)$/,function(o,u,H){return H.split("|").map(function(F){return u+F}).join("|")})}).join("|");return h.split("|").forEach(j)}function e(h,j,n){var o=[];f[h].forEach(function(u,H){if(j)u+="+"+u.slice(0,3);d(u,function(F,L){o[L*n+H]=F.toLowerCase()})});f[h]=o}function g(h,j,n){h="\\d{"+h+","+j+"}";if(n)h+="|(?:"+fb(f.numbers)+")+";return h}var f,
i;f=new cb(b);c("modifiers");"months,weekdays,units,numbers,articles,optionals,timeMarker,ampm,timeSuffixes,dateParse,timeParse".split(",").forEach(c);i=!f.monthSuffix;e("months",i,12);e("weekdays",i,7);e("units",m,8);e("numbers",m,10);f.code=a;f.date=g(1,2,f.digitDate);f.year=g(4,4);f.num=function(){var h=["\\d+"].concat(f.articles);if(f.numbers)h=h.concat(f.numbers);return fb(h)}();(function(){var h=[];f.ha={};f.modifiers.forEach(function(j){var n=j.name;d(j.src,function(o){var u=f[n];f.ha[o]=j;
h.push({name:n,src:o,value:j.value});f[n]=u?u+"|"+o:o})});f.day+="|"+fb(f.weekdays);f.modifiers=h})();if(f.monthSuffix){f.month=g(1,2);f.months=N(1,12).map(function(h){return h+f.monthSuffix})}f.full_month=g(1,2)+"|"+fb(f.months);f.timeSuffixes.length>0&&f.addFormat(gb(Va,f),m,Ua);f.addFormat("{day}",k);f.addFormat("{month}"+(f.monthSuffix||""));f.addFormat("{year}"+(f.yearSuffix||""));f.timeParse.forEach(function(h){f.addFormat(h,k)});f.dateParse.forEach(function(h){f.addFormat(h)});return bb[a]=
f}function hb(a,b,c,d){a.ga.unshift({Ea:d,za:a,Ca:r("^"+b+"$","i"),to:c})}function eb(a){return a.slice(0,1).toUpperCase()+a.slice(1)}function fb(a){return a.filter(function(b){return!!b}).join("|")}function kb(a,b){var c;if(la(a[0]))return a;else if(A(a[0])&&!A(a[1]))return[a[0]];else if(B(a[0])&&b)return[lb(a[0]),a[1]];c={};Ya.forEach(function(d,e){c[d.$]=a[e]});return[c]}
function lb(a,b){var c={};match=a.match(/^(\d+)?\s?(\w+?)s?$/i);if(K(b))b=parseInt(match[1])||1;c[match[2].toLowerCase()]=b;return c}function mb(a,b){var c={},d,e;b.forEach(function(g,f){d=a[f+1];if(!(K(d)||d==="")){if(g==="year")c.Fa=d;e=parseFloat(d.replace(/,/,"."));c[g]=!isNaN(e)?e:d.toLowerCase()}});return c}function nb(a){a=a.trim().replace(/^(just )?now|\.+$/i,"");return ob(a)}
function ob(a){return a.replace(Xa,function(b,c,d){var e=0,g=1,f,i;if(c)return b;d.split("").reverse().forEach(function(h){h=Wa[h];var j=h>9;if(j){if(f)e+=g;g*=h/(i||1);i=h}else{if(f===m)g*=10;e+=g*h}f=j});if(f)e+=g;return e})}
function pb(a,b,c){var d=new s,e=m,g,f,i,h,j,n,o,u,H;if(fa(a))d=a.clone();else if(A(a))d=new s(a);else if(la(a)){d=(new s).set(a,k);h=a}else if(B(a)){g=ib(b);a=nb(a);g&&G(g.va(),function(F,L){var Ca=a.match(L.Ca);if(Ca){i=L;f=i.za;h=mb(Ca,i.to,f);f.oa=i;if(h.timestamp){h=h.timestamp;return m}if(i.Ea&&!B(h.month)&&(B(h.date)||g.xa(b))){u=h.month;h.month=h.date;h.date=u}if(h.year&&h.Fa.length===2)h.year=O((new s).getFullYear()/100)*100-O(h.year/100)*100+h.year;if(h.month){h.month=f.getMonth(h.month);
if(h.shift&&!h.unit)h.unit=f.units[7]}if(h.weekday&&h.date)delete h.weekday;else if(h.weekday){h.weekday=f.ka(h.weekday);if(h.shift&&!h.unit)h.unit=f.units[5]}if(h.day&&(u=f.ha[h.day])){h.day=u.value;d.reset();e=k}else if(h.day&&(n=f.ka(h.day))>-1){delete h.day;if(h.num&&h.month){H=function(){var $=d.ka();d.Ha(7*(h.num-1)+($>n?n+7:n))};h.day=1}else h.weekday=n}if(h.date&&!A(h.date))h.date=f.wa(h.date);if(f.Ba(h.ampm)&&h.hour<12)h.hour+=12;else if(f.Aa(h.ampm)&&h.hour===12)h.hour=0;if("offset_hours"in
h||"offset_minutes"in h){h.utc=k;h.offset_minutes=h.offset_minutes||0;h.offset_minutes+=h.offset_hours*60;if(h.offset_sign==="-")h.offset_minutes*=-1;h.minute-=h.offset_minutes}if(h.unit){e=k;o=f.qa(h.num);j=f.ua(h.unit);if(h.shift||h.edge){o*=(u=f.ha[h.shift])?u.value:0;if(j==="month"&&J(h.date)){d.set({day:h.date},k);delete h.date}if(j==="year"&&J(h.month)){d.set({month:h.month,day:h.date},k);delete h.month;delete h.date}}if(h.sign&&(u=f.ha[h.sign]))o*=u.value;if(J(h.weekday)){d.set({weekday:h.weekday},
k);delete h.weekday}h[j]=(h[j]||0)+o}if(h.year_sign==="-")h.year*=-1;W.slice(1,4).forEach(function($,Da){var xb=h[$.$],yb=xb%1;if(yb){h[W[Da].$]=O(yb*($.$==="second"?1E3:60));h[$.$]=P(xb)}});return m}});if(i)if(e)d.advance(h);else{h.utc&&d.reset();qb(d,h,k,h.utc,m,c)}else d=a?new s(a):new s;if(h&&h.edge){u=f.ha[h.edge];G(W.slice(4),function(F,L){if(J(h[L.$])){j=L.$;return m}});if(j==="year")h.fa="month";else if(j==="month"||j==="week")h.fa="day";d[(u.value<0?"endOf":"beginningOf")+eb(j)]();u.value===
-2&&d.reset()}H&&H()}return{ea:d,set:h}}function rb(a){a.addDays(4-(a.getDay()||7)).reset();return 1+P(a.daysSince(a.clone().beginningOfYear())/7)}function db(a){var b,c=w.abs(a),d=c,e=0;W.slice(1).forEach(function(g,f){b=P(O(c/g.da()*10)/10);if(b>=1){d=b;e=f+1}});return[d,e,a]}
function sb(a,b,c,d){var e,g=ib(d),f=r(/^[A-Z]/);if(a.isValid())if(Date[b])b=Date[b];else{if(z(b)){e=db(a.millisecondsFromNow());b=b.apply(a,e.concat(g))}}else return"Invalid Date";if(!b&&c){e=e||db(a.millisecondsFromNow());if(e[1]===0){e[1]=1;e[0]=1}return g.Da(e)}b=b||"long";b=g[b]||b;$a.forEach(function(i){b=b.replace(r("\\{("+i.ba+")(\\d)?\\}",i.na?"i":""),function(h,j,n){h=i.format(a,g,n||1,j);n=j.length;var o=j.match(/^(.)\1+$/);if(i.na){if(n===3)h=h.slice(0,3);if(o||j.match(f))h=eb(h)}else if(o&&
!i.text)h=(A(h)?Q(h,n):h.toString()).slice(-n);return h})});return b}function tb(a,b,c){var d=pb(b),e=0,g=b=0,f;if(c>0){b=g=c;f=k}if(!d.ea.isValid())return m;if(d.set&&d.set.fa){ab.forEach(function(h){if(h.$===d.set.fa)e=h.da(d.ea,a-d.ea)-1});c=eb(d.set.fa);if(d.set.edge||d.set.shift)d.ea["beginningOf"+c]();if(d.set.fa==="month")i=d.ea.clone()["endOf"+c]().getTime();if(!f&&d.set.sign&&d.set.fa!="millisecond"){b=50;g=-50}}f=a.getTime();c=d.ea.getTime();var i=i||c+e;return f>=c-b&&f<=i+g}
function qb(a,b,c,d,e,g){function f(j){return J(b[j])?b[j]:b[j+"s"]}var i,h;if(A(b)&&e)b={milliseconds:b};else if(A(b)){a.setTime(b);return a}if(b.date)b.day=b.date;G(W,function(j,n){var o=n.$==="day";if(J(f(n.$))||o&&J(f("weekday"))){b.fa=n.$;h=+j;return m}else if(c&&n.$!=="week"&&(!o||!J(f("week"))))a["set"+(d?"UTC":"")+n.method](o?1:0)});ab.forEach(function(j){var n=j.$;j=j.method;var o;o=f(n);if(!K(o)){if(e){if(n==="week"){o=(b.day||0)+o*7;j="Date"}o=o*e+a["get"+j](void 0)}else n==="month"&&J(f("day"))&&
a.setDate(15);a["set"+(d?"UTC":"")+j](o);if(e&&n==="month"){n=o;if(n<0)n+=12;n%12!=a.getMonth()&&a.setDate(0)}}});if(!e&&!J(f("day"))&&J(f("weekday"))){i=f("weekday");a["set"+(d?"UTC":"")+"Weekday"](i)}(function(){var j=new s;return g===-1&&a>j||g===1&&a<j})()&&G(W.slice(h+1),function(j,n){if((n.ja||n.$==="week"&&J(f("weekday")))&&!J(f(n.$))){a[n.ia](g);return m}});return a}
function gb(a,b,c){var d={h:0,m:1,s:2},e;b=b||V;return a.replace(/{([a-z])}/g,function(g,f){var i=[],h=f==="h",j=h&&!c;if(f==="t")return b.ampm.join("|");else{h&&i.push(":");if(e=b.timeSuffixes[d[f]])i.push(e+"\\s*");return i.length===0?"":"(?:"+i.join("|")+")"+(j?"":"?")}})}function ub(a,b){var c;c=A(a[1])?kb(a)[0]:a[0];return pb(c,a[1],b).ea}
s.extend({create:function(){return ub(arguments)},past:function(){return ub(arguments,-1)},future:function(){return ub(arguments,1)},addLocale:function(a,b){return jb(a,b)},setLocale:function(a){var b=ib(a,m);Ta=b;if(a&&a!=b.code)b.code=a;return b},getLocale:function(a){return!a?Ta:ib(a,m)},addFormat:function(a,b,c){hb(ib(c),a,b)}},m,m);
s.extend({set:function(){var a=kb(arguments);return qb(this,a[0],a[1])},setUTC:function(){var a=kb(arguments);return qb(this,a[0],a[1],k)},setWeekday:function(a){if(!K(a))return this.setDate(this.getDate()+a-this.getDay())},setUTCWeekday:function(a){if(!K(a))return this.setDate(this.getUTCDate()+a-this.getDay())},setWeek:function(a){if(!K(a)){this.setMonth(0);this.setDate(a*7+1)}},setUTCWeek:function(a){if(!K(a)){this.setMonth(0);this.setUTCDate(a*7+1)}},getWeek:function(){return rb(this)},getUTCWeek:function(){return rb(this.toUTC())},
getUTCOffset:function(a){var b=this.ma?0:this.getTimezoneOffset(),c=a===k?":":"";if(!b&&a)return"Z";return Q(O(-b/60),2,k)+c+Q(b%60,2)},toUTC:function(){if(this.ma)return this;var a=this.clone().addMinutes(this.getTimezoneOffset());a.ma=k;return a},isUTC:function(){return this.ma||this.getTimezoneOffset()===0},advance:function(){var a=kb(arguments,k);return qb(this,a[0],a[1],m,1)},rewind:function(){var a=kb(arguments,k);return qb(this,a[0],a[1],m,-1)},isValid:function(){return!isNaN(this.getTime())},
isAfter:function(a,b){return this.getTime()>s.create(a).getTime()-(b||0)},isBefore:function(a,b){return this.getTime()<s.create(a).getTime()+(b||0)},isBetween:function(a,b,c){var d=this.getTime();a=s.create(a).getTime();var e=s.create(b).getTime();b=w.min(a,e);a=w.max(a,e);c=c||0;return b-c<d&&a+c>d},isLeapYear:function(){var a=this.getFullYear();return a%4===0&&a%100!==0||a%400===0},daysInMonth:function(){return 32-(new s(this.getFullYear(),this.getMonth(),32)).getDate()},format:function(a,b){return sb(this,
a,m,b)},relative:function(a,b){if(B(a)){b=a;a=l}return sb(this,a,k,b)},is:function(a,b){var c;if(this.isValid()){if(B(a)){a=a.trim().toLowerCase();switch(k){case a==="future":return this.getTime()>(new s).getTime();case a==="past":return this.getTime()<(new s).getTime();case a==="weekday":return this.getDay()>0&&this.getDay()<6;case a==="weekend":return this.getDay()===0||this.getDay()===6;case (c=V.weekdays.indexOf(a)%7)>-1:return this.getDay()===c;case (c=V.months.indexOf(a)%12)>-1:return this.getMonth()===
c}}return tb(this,a,b)}},reset:function(a){var b={},c;a=a||"hours";if(a==="date")a="days";c=ab.some(function(d){return a===d.$||a===d.$+"s"});b[a]=a.match(/^days?/)?1:0;return c?this.set(b,k):this},clone:function(){return new s(this.getTime())}});s.extend({iso:function(){return this.toISOString()},getWeekday:s.prototype.getDay,getUTCWeekday:s.prototype.getUTCDay});
function vb(a,b){function c(){return O(this*b)}function d(){return ub(arguments)[a.ia](this)}function e(){return ub(arguments)[a.ia](-this)}var g=a.$,f={};f[g]=c;f[g+"s"]=c;f[g+"Before"]=e;f[g+"sBefore"]=e;f[g+"Ago"]=e;f[g+"sAgo"]=e;f[g+"After"]=d;f[g+"sAfter"]=d;f[g+"FromNow"]=d;f[g+"sFromNow"]=d;v.extend(f)}v.extend({duration:function(a){return ib(a).ta(this)}});
V=Ta=s.addLocale("en",{plural:k,timeMarker:"at",ampm:"am,pm",months:"January,February,March,April,May,June,July,August,September,October,November,December",weekdays:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",units:"millisecond:|s,second:|s,minute:|s,hour:|s,day:|s,week:|s,month:|s,year:|s",numbers:"one,two,three,four,five,six,seven,eight,nine,ten",articles:"a,an,the",optionals:"the,st|nd|rd|th,of","short":"{Month} {d}, {yyyy}","long":"{Month} {d}, {yyyy} {h}:{mm}{tt}",full:"{Weekday} {Month} {d}, {yyyy} {h}:{mm}:{ss}{tt}",
past:"{num} {unit} {sign}",future:"{num} {unit} {sign}",duration:"{num} {unit}",modifiers:[{name:"day",src:"yesterday",value:-1},{name:"day",src:"today",value:0},{name:"day",src:"tomorrow",value:1},{name:"sign",src:"ago|before",value:-1},{name:"sign",src:"from now|after|from|in",value:1},{name:"edge",src:"last day",value:-2},{name:"edge",src:"end",value:-1},{name:"edge",src:"first day|beginning",value:1},{name:"shift",src:"last",value:-1},{name:"shift",src:"the|this",value:0},{name:"shift",src:"next",
value:1}],dateParse:["{num} {unit} {sign}","{sign} {num} {unit}","{num} {unit=4-5} {sign} {day}","{month} {year}","{shift} {unit=5-7}","{0} {edge} of {shift?} {unit=4-7?}{month?}{year?}"],timeParse:["{0} {num}{1} {day} of {month} {year?}","{weekday?} {month} {date}{1} {year?}","{date} {month} {year}","{shift} {weekday}","{shift} week {weekday}","{weekday} {2} {shift} week","{0} {date}{1} of {month}","{0}{month?} {date?}{1} of {shift} {unit=6-7}"]});W=ab.concat().reverse();Ya=ab.concat();
Ya.splice(2,1);
I(s,k,m,ab,function(a,b,c){var d=b.$,e=eb(d),g=b.da(),f,i;b.ia="add"+e+"s";f=function(h,j){return O((this.getTime()-s.create(h,j).getTime())/g)};i=function(h,j){return O((s.create(h,j).getTime()-this.getTime())/g)};a[d+"sAgo"]=i;a[d+"sUntil"]=i;a[d+"sSince"]=f;a[d+"sFromNow"]=f;a[b.ia]=function(h,j){var n={};n[d]=h;return this.advance(n,j)};vb(b,g);c<3&&["Last","This","Next"].forEach(function(h){a["is"+h+e]=function(){return this.is(h+" "+d)}});if(c<4){a["beginningOf"+e]=function(){var h={};switch(d){case "year":h.year=
this.getFullYear();break;case "month":h.month=this.getMonth();break;case "day":h.day=this.getDate();break;case "week":h.weekday=0}return this.set(h,k)};a["endOf"+e]=function(){var h={hours:23,minutes:59,seconds:59,milliseconds:999};switch(d){case "year":h.month=11;h.day=31;break;case "month":h.day=this.daysInMonth();break;case "week":h.weekday=6}return this.set(h,k)}}});V.addFormat("([+-])?(\\d{4,4})[-.]?{full_month}[-.]?(\\d{1,2})?",k,["year_sign","year","month","date"],m,k);
V.addFormat("(\\d{1,2})[-.\\/]{full_month}(?:[-.\\/](\\d{2,4}))?",k,["date","month","year"],k);V.addFormat("{full_month}[-.](\\d{4,4})",m,["month","year"]);V.addFormat("\\/Date\\((\\d+(?:\\+\\d{4,4})?)\\)\\/",m,["timestamp"]);V.addFormat(gb(Va,V),m,Ua);Za=V.ga.slice(0,7).reverse();V.ga=V.ga.slice(7).concat(Za);I(s,k,m,"short,long,full",function(a,b){a[b]=function(c){return sb(this,b,m,c)}});
"\u3007\u4e00\u4e8c\u4e09\u56db\u4e94\u516d\u4e03\u516b\u4e5d\u5341\u767e\u5343\u4e07".split("").forEach(function(a,b){if(b>9)b=w.pow(10,b-9);Wa[a]=b});"\uff10\uff11\uff12\uff13\uff14\uff15\uff16\uff17\uff18\uff19".split("").forEach(function(a,b){Wa[a]=b});Xa=r("([\u671f\u9031\u5468])?([\u3007\u4e00\u4e8c\u4e09\u56db\u4e94\u516d\u4e03\u516b\u4e5d\u5341\u767e\u5343\u4e07\uff10\uff11\uff12\uff13\uff14\uff15\uff16\uff17\uff18\uff19]+)(?!\u6628)","g");
(function(){var a="today,yesterday,tomorrow,weekday,weekend,future,past".split(","),b=V.weekdays.slice(0,7),c=V.months.slice(0,12);I(s,k,m,a.concat(b).concat(c),function(d,e){d["is"+eb(e)]=function(){return this.is(e)}})})();s.extend({RFC1123:"{Dow}, {dd} {Mon} {yyyy} {HH}:{mm}:{ss} {tz}",RFC1036:"{Weekday}, {dd}-{Mon}-{yy} {HH}:{mm}:{ss} {tz}",ISO8601_DATE:"{yyyy}-{MM}-{dd}",ISO8601_DATETIME:"{yyyy}-{MM}-{dd}T{HH}:{mm}:{ss}.{fff}{isotz}"},m,m);
