var V,Ua,Va=["ampm","hour","minute","second","ampm","utc","offset_sign","offset_hours","offset_minutes","ampm"],Wa="({t})?\\s*(\\d{1,2}(?:[,.]\\d+)?)(?:{h}(\\d{1,2}(?:[,.]\\d+)?)?{m}(?::?(\\d{1,2}(?:[,.]\\d+)?){s})?\\s*(?:({t})|(Z)|(?:([+-])(\\d{2,2})(?::?(\\d{2,2}))?)?)?|\\s*({t}))",Xa={},Ya,Za,W,$a=[],ab=[{ba:"f{1,4}|ms|milliseconds",format:function(a){return X(a,"Milliseconds")}},{ba:"ss?|seconds",format:function(a){return X(a,"Seconds")}},{ba:"mm?|minutes",format:function(a){return X(a,"Minutes")}},
{ba:"hh?|hours|12hr",format:function(a){a=X(a,"Hours");return a===0?12:a-O(a/13)*12}},{ba:"HH?|24hr",format:function(a){return X(a,"Hours")}},{ba:"dd?|date|day",format:function(a){return X(a,"Date")}},{ba:"dow|weekday",oa:k,format:function(a,b,c){a=X(a,"Day");return b.weekdays[a+(c-1)*7]}},{ba:"MM?",format:function(a){return X(a,"Month")+1}},{ba:"mon|month",oa:k,format:function(a,b,c){a=X(a,"Month");return b.months[a+(c-1)*12]}},{ba:"y{2,4}|year",format:function(a){return X(a,"FullYear")}},{ba:"[Tt]{1,2}",
format:function(a,b,c,d){a=X(a,"Hours");b=b.ampm[O(a/12)];if(d.length===1)b=b.slice(0,1);if(d.slice(0,1)==="T")b=b.toUpperCase();return b}},{ba:"z{1,4}|tz|timezone",text:k,format:function(a,b,c,d){a=a.getUTCOffset();if(d=="z"||d=="zz")a=a.replace(/(\d{2})(\d{2})/,function(e,f){return P(f,d.length)});return a}},{ba:"iso(tz|timezone)",format:function(a){return a.getUTCOffset(k)}},{ba:"ord",format:function(a){a=X(a,"Date");return a+ra(a)}}],bb=[{$:"year",method:"FullYear",ka:k,da:function(a){return(365+
(a?a.isLeapYear()?1:0:0.25))*24*60*60*1E3}},{$:"month",method:"Month",ka:k,da:function(a,b){var c=30.4375,d;if(a){d=a.daysInMonth();if(b<=d.days())c=d}return c*24*60*60*1E3}},{$:"week",method:"Week",da:ca(6048E5)},{$:"day",method:"Date",ka:k,da:ca(864E5)},{$:"hour",method:"Hours",da:ca(36E5)},{$:"minute",method:"Minutes",da:ca(6E4)},{$:"second",method:"Seconds",da:ca(1E3)},{$:"millisecond",method:"Milliseconds",da:ca(1)}],cb={};function db(a){pa(this,a);this.ha=$a.concat()}
db.prototype={getMonth:function(a){return B(a)?a-1:this.months.indexOf(a)%12},la:function(a){return this.weekdays.indexOf(a)%7},ra:function(a){var b;return B(a)?a:a&&(b=this.numbers.indexOf(a))!==-1?(b+1)%10:1},xa:function(a){var b=this;return a.replace(q(this.num,"g"),function(c){return b.ra(c)||""})},va:function(a){return V.units[this.units.indexOf(a)%8]},Ea:function(a){return this.qa(a,a[2]>0?"future":"past")},ua:function(a){return this.qa(eb(a),"duration")},ya:function(a){a=a||this.code;return a===
"en"||a==="en-US"?k:this.variant},Ba:function(a){return a===this.ampm[0]},Ca:function(a){return a===this.ampm[1]},qa:function(a,b){var c=a[0],d=a[1],e=a[2],f,g,i;if(this.code=="ru"){i=c.toString().slice(-1);switch(k){case i==1:i=1;break;case i>=2&&i<=4:i=2;break;default:i=3}}else i=this.plural&&c>1?1:0;g=this.units[i*8+d]||this.units[d];if(this.capitalizeUnit)g=fb(g);f=this.modifiers.filter(function(j){return j.name=="sign"&&j.value==(e>0?1:-1)})[0];return this[b].replace(/\{(.*?)\}/g,function(j,
h){switch(h){case "num":return c;case "unit":return g;case "sign":return f.src}})},wa:function(){return this.pa?[this.pa].concat(this.ha):this.ha},addFormat:function(a,b,c,d,e){var f=c||[],g=this,i;a=a.replace(/\s+/g,"[-,. ]*");a=a.replace(/\{([^,]+?)\}/g,function(j,h){var n=h.match(/\?$/),r=h.match(/(\d)(?:-(\d))?/),y=h.match(/^\d+$/),z=h.replace(/[^a-z]+$/,""),C,aa;if(y)C=g.optionals[y[0]];else if(g[z])C=g[z];else if(g[z+"s"]){C=g[z+"s"];if(r){aa=[];C.forEach(function(ba,Da){var Q=Da%(g.units?8:
C.length);if(Q>=r[1]&&Q<=(r[2]||r[1]))aa.push(ba)});C=aa}C=gb(C)}if(y)return"(?:"+C+")?";else{c||f.push(z);return"("+C+")"+(n?"?":"")}});if(b){b=hb(Wa,g,e);e=["t","[\\s\\u3000]"].concat(g.timeMarker);i=a.match(/\\d\{\d,\d\}\)+\??$/);ib(g,"(?:"+b+")[,\\s\\u3000]+?"+a,Va.concat(f),d);ib(g,a+"(?:[,\\s]*(?:"+e.join("|")+(i?"+":"*")+")"+b+")?",f.concat(Va),d)}else ib(g,a,f,d)}};function jb(a,b){var c;D(a)||(a="");c=cb[a]||cb[a.slice(0,2)];if(b===m&&!c)throw Error("Invalid locale.");return c||Ua}
function kb(a,b){function c(j){var h=g[j];if(D(h))g[j]=h.split(",");else h||(g[j]=[])}function d(j,h){j=j.split("+").map(function(n){return n.replace(/(.+):(.+)$/,function(r,y,z){return z.split("|").map(function(C){return y+C}).join("|")})}).join("|");return j.split("|").forEach(h)}function e(j,h,n){var r=[];g[j].forEach(function(y,z){if(h)y+="+"+y.slice(0,3);d(y,function(C,aa){r[aa*n+z]=C.toLowerCase()})});g[j]=r}function f(j,h,n){j="\\d{"+j+","+h+"}";if(n)j+="|(?:"+gb(g.numbers)+")+";return j}var g,
i;g=new db(b);c("modifiers");"months,weekdays,units,numbers,articles,optionals,timeMarker,ampm,timeSuffixes,dateParse,timeParse".split(",").forEach(c);i=!g.monthSuffix;e("months",i,12);e("weekdays",i,7);e("units",m,8);e("numbers",m,10);g.code=a;g.date=f(1,2,g.digitDate);g.year=f(4,4);g.num=function(){var j=["\\d+"].concat(g.articles);if(g.numbers)j=j.concat(g.numbers);return gb(j)}();(function(){var j=[];g.ia={};g.modifiers.forEach(function(h){var n=h.name;d(h.src,function(r){var y=g[n];g.ia[r]=h;
j.push({name:n,src:r,value:h.value});g[n]=y?y+"|"+r:r})});g.day+="|"+gb(g.weekdays);g.modifiers=j})();if(g.monthSuffix){g.month=f(1,2);g.months=M(1,12).map(function(j){return j+g.monthSuffix})}g.full_month=f(1,2)+"|"+gb(g.months);g.timeSuffixes.length>0&&g.addFormat(hb(Wa,g),m,Va);g.addFormat("{day}",k);g.addFormat("{month}"+(g.monthSuffix||""));g.addFormat("{year}"+(g.yearSuffix||""));g.timeParse.forEach(function(j){g.addFormat(j,k)});g.dateParse.forEach(function(j){g.addFormat(j)});return cb[a]=
g}function ib(a,b,c,d){a.ha.unshift({Ga:d,Aa:a,Da:q("^"+b+"$","i"),to:c})}function fb(a){return a.slice(0,1).toUpperCase()+a.slice(1)}function gb(a){return a.filter(function(b){return!!b}).join("|")}function lb(a,b){var c;if(na(a[0]))return a;else if(B(a[0])&&!B(a[1]))return[a[0]];else if(D(a[0])&&b)return[mb(a[0]),a[1]];c={};Za.forEach(function(d,e){c[d.$]=a[e]});return[c]}
function mb(a,b){var c={};match=a.match(/^(\d+)?\s?(\w+?)s?$/i);if(K(b))b=parseInt(match[1])||1;c[match[2].toLowerCase()]=b;return c}function nb(a,b){var c={},d,e;b.forEach(function(f,g){d=a[g+1];if(!(K(d)||d==="")){if(f==="year")c.Ha=d;e=parseFloat(d.replace(/,/,"."));c[f]=!isNaN(e)?e:d.toLowerCase()}});return c}function ob(a){a=a.trim().replace(/^(just )?now|\.+$/i,"");return pb(a)}
function pb(a){return a.replace(Ya,function(b,c,d){var e=0,f=1,g,i;if(c)return b;d.split("").reverse().forEach(function(j){j=Xa[j];var h=j>9;if(h){if(g)e+=f;f*=j/(i||1);i=j}else{if(g===m)f*=10;e+=f*j}g=h});if(g)e+=f;return e})}
function qb(a,b,c,d){var e=new s,f=m,g,i,j,h,n,r,y,z,C;d&&e.na();if(ha(a))e=a.clone();else if(B(a))e=new s(a);else if(na(a)){e.set(a,k);h=a}else if(D(a)){g=jb(b);a=ob(a);g&&H(g.wa(),function(aa,ba){var Da=a.match(ba.Da);if(Da){j=ba;i=j.Aa;h=nb(Da,j.to,i);h.utc&&e.na();i.pa=j;if(h.timestamp){h=h.timestamp;return m}if(j.Ga&&!D(h.month)&&(D(h.date)||g.ya(b))){z=h.month;h.month=h.date;h.date=z}if(h.year&&h.Ha.length===2)h.year=N(X(new s,"FullYear")/100)*100-N(h.year/100)*100+h.year;if(h.month){h.month=
i.getMonth(h.month);if(h.shift&&!h.unit)h.unit=i.units[7]}if(h.weekday&&h.date)delete h.weekday;else if(h.weekday){h.weekday=i.la(h.weekday);if(h.shift&&!h.unit)h.unit=i.units[5]}if(h.day&&(z=i.ia[h.day])){h.day=z.value;e.reset();f=k}else if(h.day&&(r=i.la(h.day))>-1){delete h.day;if(h.num&&h.month){C=function(){var Q=e.la();e.Fa(7*(h.num-1)+(Q>r?r+7:r))};h.day=1}else h.weekday=r}if(h.date&&!B(h.date))h.date=i.xa(h.date);if(i.Ca(h.ampm)&&h.hour<12)h.hour+=12;else if(i.Ba(h.ampm)&&h.hour===12)h.hour=
0;if("offset_hours"in h||"offset_minutes"in h){e.na();h.offset_minutes=h.offset_minutes||0;h.offset_minutes+=h.offset_hours*60;if(h.offset_sign==="-")h.offset_minutes*=-1;h.minute-=h.offset_minutes}if(h.unit){f=k;y=i.ra(h.num);n=i.va(h.unit);if(h.shift||h.edge){y*=(z=i.ia[h.shift])?z.value:0;if(n==="month"&&J(h.date)){e.set({day:h.date},k);delete h.date}if(n==="year"&&J(h.month)){e.set({month:h.month,day:h.date},k);delete h.month;delete h.date}}if(h.sign&&(z=i.ia[h.sign]))y*=z.value;if(J(h.weekday)){e.set({weekday:h.weekday},
k);delete h.weekday}h[n]=(h[n]||0)+y}if(h.year_sign==="-")h.year*=-1;W.slice(1,4).forEach(function(Q,Ub){var zb=h[Q.$],Ab=zb%1;if(Ab){h[W[Ub].$]=N(Ab*(Q.$==="second"?1E3:60));h[Q.$]=O(zb)}});return m}});if(j)if(f)e.advance(h);else{e.ea&&e.reset();rb(e,h,k,m,c)}else e=a?new s(a):new s;if(h&&h.edge){z=i.ia[h.edge];H(W.slice(4),function(aa,ba){if(J(h[ba.$])){n=ba.$;return m}});if(n==="year")h.ga="month";else if(n==="month"||n==="week")h.ga="day";e[(z.value<0?"endOf":"beginningOf")+fb(n)]();z.value===
-2&&e.reset()}C&&C()}return{fa:e,set:h}}function eb(a){var b,c=v.abs(a),d=c,e=0;W.slice(1).forEach(function(f,g){b=O(N(c/f.da()*10)/10);if(b>=1){d=b;e=g+1}});return[d,e,a]}
function sb(a,b,c,d){var e,f=jb(d),g=q(/^[A-Z]/);if(a.isValid())if(Date[b])b=Date[b];else{if(A(b)){e=eb(a.millisecondsFromNow());b=b.apply(a,e.concat(f))}}else return"Invalid Date";if(!b&&c){e=e||eb(a.millisecondsFromNow());if(e[1]===0){e[1]=1;e[0]=1}return f.Ea(e)}b=b||"long";b=f[b]||b;ab.forEach(function(i){b=b.replace(q("\\{("+i.ba+")(\\d)?\\}",i.oa?"i":""),function(j,h,n){j=i.format(a,f,n||1,h);n=h.length;var r=h.match(/^(.)\1+$/);if(i.oa){if(n===3)j=j.slice(0,3);if(r||h.match(g))j=fb(j)}else if(r&&
!i.text)j=(B(j)?P(j,n):j.toString()).slice(-n);return j})});return b}
function tb(a,b,c,d){var e=qb(b,l,l,d),f=0;d=b=0;var g;if(c>0){b=d=c;g=k}if(!e.fa.isValid())return m;if(e.set&&e.set.ga){bb.forEach(function(j){if(j.$===e.set.ga)f=j.da(e.fa,a-e.fa)-1});c=fb(e.set.ga);if(e.set.edge||e.set.shift)e.fa["beginningOf"+c]();if(e.set.ga==="month")i=e.fa.clone()["endOf"+c]().getTime();if(!g&&e.set.sign&&e.set.ga!="millisecond"){b=50;d=-50}}g=a.getTime();c=e.fa.getTime();var i=i||c+f;return g>=c-b&&g<=i+d}
function rb(a,b,c,d,e){function f(j){return J(b[j])?b[j]:b[j+"s"]}var g,i;if(B(b)&&d)b={milliseconds:b};else if(B(b)){a.setTime(b);return a}if(b.date)b.day=b.date;H(W,function(j,h){var n=h.$==="day";if(J(f(h.$))||n&&J(f("weekday"))){b.ga=h.$;i=+j;return m}else if(c&&h.$!=="week"&&(!n||!J(f("week"))))ub(a,h.method,n?1:0)});bb.forEach(function(j){var h=j.$;j=j.method;var n;n=f(h);if(!K(n)){if(d){if(h==="week"){n=(b.day||0)+n*7;j="Date"}n=n*d+X(a,j)}else h==="month"&&J(f("day"))&&ub(a,"Date",15);ub(a,
j,n);if(d&&h==="month"){h=n;if(h<0)h+=12;h%12!=X(a,"Month")&&ub(a,"Date",0)}}});if(!d&&!J(f("day"))&&J(f("weekday"))){g=f("weekday");a.Fa(g)}(function(){var j=new s;return e===-1&&a>j||e===1&&a<j})()&&H(W.slice(i+1),function(j,h){if((h.ka||h.$==="week"&&J(f("weekday")))&&!J(f(h.$))){a[h.ja](e);return m}});return a}function X(a,b){return a["get"+(a.ea?"UTC":"")+b]()}function ub(a,b,c){return a["set"+(a.ea?"UTC":"")+b](c)}
function hb(a,b,c){var d={h:0,m:1,s:2},e;b=b||V;return a.replace(/{([a-z])}/g,function(f,g){var i=[],j=g==="h",h=j&&!c;if(g==="t")return b.ampm.join("|");else{j&&i.push(":");if(e=b.timeSuffixes[d[g]])i.push(e+"\\s*");return i.length===0?"":"(?:"+i.join("|")+")"+(h?"":"?")}})}function vb(a,b){var c,d,e;if(B(a[1]))c=lb(a)[0];else{c=a[0];d=a[1];e=a[2]}return qb(c,d,b,e).fa}
s.extend({create:function(){return vb(arguments)},past:function(){return vb(arguments,-1)},future:function(){return vb(arguments,1)},addLocale:function(a,b){return kb(a,b)},setLocale:function(a){var b=jb(a,m);Ua=b;if(a&&a!=b.code)b.code=a;return b},getLocale:function(a){return!a?Ua:jb(a,m)},addFormat:function(a,b,c){ib(jb(c),a,b)}},m,m);
s.extend({set:function(){var a=lb(arguments);return rb(this,a[0],a[1])},setWeekday:function(a){if(!K(a))return ub(this,"Date",X(this,"Date")+a-X(this,"Day"))},setWeek:function(a){if(!K(a)){X(this,"Date");ub(this,"Month",0);ub(this,"Date",a*7+1);return this.getTime()}},getWeek:function(){var a=this;a=a.clone();var b=X(a,"Day")||7;a.addDays(4-b).reset();return 1+O(a.daysSince(a.clone().beginningOfYear())/7)},getUTCOffset:function(a){var b=this.ea?0:this.getTimezoneOffset(),c=a===k?":":"";if(!b&&a)return"Z";
return P(N(-b/60),2,k)+c+P(b%60,2)},utc:function(a){this.ea=a===k||arguments.length===0;return this},isUTC:function(){return!!this.ea||this.getTimezoneOffset()===0},advance:function(){var a=lb(arguments,k);return rb(this,a[0],a[1],1)},rewind:function(){var a=lb(arguments,k);return rb(this,a[0],a[1],-1)},isValid:function(){return!isNaN(this.getTime())},isAfter:function(a,b){return this.getTime()>s.create(a).getTime()-(b||0)},isBefore:function(a,b){return this.getTime()<s.create(a).getTime()+(b||0)},
isBetween:function(a,b,c){var d=this.getTime();a=s.create(a).getTime();var e=s.create(b).getTime();b=v.min(a,e);a=v.max(a,e);c=c||0;return b-c<d&&a+c>d},isLeapYear:function(){var a=X(this,"FullYear");return a%4===0&&a%100!==0||a%400===0},daysInMonth:function(){return 32-X(new s(X(this,"FullYear"),X(this,"Month"),32),"Date")},format:function(a,b){return sb(this,a,m,b)},relative:function(a,b){if(D(a)){b=a;a=l}return sb(this,a,k,b)},is:function(a,b,c){var d,e;if(this.isValid()){if(D(a)){a=a.trim().toLowerCase();
e=this.clone().na(c);switch(k){case a==="future":return this.getTime()>(new s).getTime();case a==="past":return this.getTime()<(new s).getTime();case a==="weekday":return X(e,"Day")>0&&X(e,"Day")<6;case a==="weekend":return X(e,"Day")===0||X(e,"Day")===6;case (d=V.weekdays.indexOf(a)%7)>-1:return X(e,"Day")===d;case (d=V.months.indexOf(a)%12)>-1:return X(e,"Month")===d}}return tb(this,a,b,c)}},reset:function(a){var b={},c;a=a||"hours";if(a==="date")a="days";c=bb.some(function(d){return a===d.$||a===
d.$+"s"});b[a]=a.match(/^days?/)?1:0;return c?this.set(b,k):this},clone:function(){var a=new s(this.getTime());a.ea=this.ea;return a}});s.extend({iso:function(){return this.toISOString()},getWeekday:s.prototype.getDay,getUTCWeekday:s.prototype.getUTCDay});
function wb(a,b){function c(){return N(this*b)}function d(){return vb(arguments)[a.ja](this)}function e(){return vb(arguments)[a.ja](-this)}var f=a.$,g={};g[f]=c;g[f+"s"]=c;g[f+"Before"]=e;g[f+"sBefore"]=e;g[f+"Ago"]=e;g[f+"sAgo"]=e;g[f+"After"]=d;g[f+"sAfter"]=d;g[f+"FromNow"]=d;g[f+"sFromNow"]=d;u.extend(g)}u.extend({duration:function(a){return jb(a).ua(this)}});
V=Ua=s.addLocale("en",{plural:k,timeMarker:"at",ampm:"am,pm",months:"January,February,March,April,May,June,July,August,September,October,November,December",weekdays:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",units:"millisecond:|s,second:|s,minute:|s,hour:|s,day:|s,week:|s,month:|s,year:|s",numbers:"one,two,three,four,five,six,seven,eight,nine,ten",articles:"a,an,the",optionals:"the,st|nd|rd|th,of","short":"{Month} {d}, {yyyy}","long":"{Month} {d}, {yyyy} {h}:{mm}{tt}",full:"{Weekday} {Month} {d}, {yyyy} {h}:{mm}:{ss}{tt}",
past:"{num} {unit} {sign}",future:"{num} {unit} {sign}",duration:"{num} {unit}",modifiers:[{name:"day",src:"yesterday",value:-1},{name:"day",src:"today",value:0},{name:"day",src:"tomorrow",value:1},{name:"sign",src:"ago|before",value:-1},{name:"sign",src:"from now|after|from|in",value:1},{name:"edge",src:"last day",value:-2},{name:"edge",src:"end",value:-1},{name:"edge",src:"first day|beginning",value:1},{name:"shift",src:"last",value:-1},{name:"shift",src:"the|this",value:0},{name:"shift",src:"next",
value:1}],dateParse:["{num} {unit} {sign}","{sign} {num} {unit}","{num} {unit=4-5} {sign} {day}","{month} {year}","{shift} {unit=5-7}","{0} {edge} of {shift?} {unit=4-7?}{month?}{year?}"],timeParse:["{0} {num}{1} {day} of {month} {year?}","{weekday?} {month} {date}{1} {year?}","{date} {month} {year}","{shift} {weekday}","{shift} week {weekday}","{weekday} {2} {shift} week","{0} {date}{1} of {month}","{0}{month?} {date?}{1} of {shift} {unit=6-7}"]});W=bb.concat().reverse();Za=bb.concat();
Za.splice(2,1);
I(s,k,m,bb,function(a,b,c){var d=b.$,e=fb(d),f=b.da(),g,i;b.ja="add"+e+"s";g=function(j,h){return N((this.getTime()-s.create(j,h).getTime())/f)};i=function(j,h){return N((s.create(j,h).getTime()-this.getTime())/f)};a[d+"sAgo"]=i;a[d+"sUntil"]=i;a[d+"sSince"]=g;a[d+"sFromNow"]=g;a[b.ja]=function(j,h){var n={};n[d]=j;return this.advance(n,h)};wb(b,f);c<3&&["Last","This","Next"].forEach(function(j){a["is"+j+e]=function(){return this.is(j+" "+d)}});if(c<4){a["beginningOf"+e]=function(){var j={};switch(d){case "year":j.year=
X(this,"FullYear");break;case "month":j.month=X(this,"Month");break;case "day":j.day=X(this,"Date");break;case "week":j.weekday=0}return this.set(j,k)};a["endOf"+e]=function(){var j={hours:23,minutes:59,seconds:59,milliseconds:999};switch(d){case "year":j.month=11;j.day=31;break;case "month":j.day=this.daysInMonth();break;case "week":j.weekday=6}return this.set(j,k)}}});V.addFormat("([+-])?(\\d{4,4})[-.]?{full_month}[-.]?(\\d{1,2})?",k,["year_sign","year","month","date"],m,k);
V.addFormat("(\\d{1,2})[-.\\/]{full_month}(?:[-.\\/](\\d{2,4}))?",k,["date","month","year"],k);V.addFormat("{full_month}[-.](\\d{4,4})",m,["month","year"]);V.addFormat("\\/Date\\((\\d+(?:\\+\\d{4,4})?)\\)\\/",m,["timestamp"]);V.addFormat(hb(Wa,V),m,Va);$a=V.ha.slice(0,7).reverse();V.ha=V.ha.slice(7).concat($a);I(s,k,m,"short,long,full",function(a,b){a[b]=function(c){return sb(this,b,m,c)}});
"\u3007\u4e00\u4e8c\u4e09\u56db\u4e94\u516d\u4e03\u516b\u4e5d\u5341\u767e\u5343\u4e07".split("").forEach(function(a,b){if(b>9)b=v.pow(10,b-9);Xa[a]=b});"\uff10\uff11\uff12\uff13\uff14\uff15\uff16\uff17\uff18\uff19".split("").forEach(function(a,b){Xa[a]=b});Ya=q("([\u671f\u9031\u5468])?([\u3007\u4e00\u4e8c\u4e09\u56db\u4e94\u516d\u4e03\u516b\u4e5d\u5341\u767e\u5343\u4e07\uff10\uff11\uff12\uff13\uff14\uff15\uff16\uff17\uff18\uff19]+)(?!\u6628)","g");
(function(){var a="today,yesterday,tomorrow,weekday,weekend,future,past".split(","),b=V.weekdays.slice(0,7),c=V.months.slice(0,12);I(s,k,m,a.concat(b).concat(c),function(d,e){d["is"+fb(e)]=function(f){return this.is(e,0,f)}})})();s.extend({RFC1123:"{Dow}, {dd} {Mon} {yyyy} {HH}:{mm}:{ss} {tz}",RFC1036:"{Weekday}, {dd}-{Mon}-{yy} {HH}:{mm}:{ss} {tz}",ISO8601_DATE:"{yyyy}-{MM}-{dd}",ISO8601_DATETIME:"{yyyy}-{MM}-{dd}T{HH}:{mm}:{ss}.{fff}{isotz}"},m,m);
