var V,Ra,Sa=["ampm","hour","minute","second","ampm","utc","offset_sign","offset_hours","offset_minutes","ampm"],Ta="({t})?\\s*(\\d{1,2}(?:[,.]\\d+)?)(?:{h}(\\d{1,2}(?:[,.]\\d+)?)?{m}(?::?(\\d{1,2}(?:[,.]\\d+)?){s})?\\s*(?:({t})|(Z)|(?:([+-])(\\d{2,2})(?::?(\\d{2,2}))?)?)?|\\s*({t}))",Ua={},Va,Wa,W,Xa=[],Ya=[{ba:"f{1,4}|ms|milliseconds",format:function(a){return a.getMilliseconds()}},{ba:"ss?|seconds",format:function(a){return a.getSeconds()}},{ba:"mm?|minutes",format:function(a){return a.getMinutes()}},
{ba:"hh?|hours|12hr",format:function(a){a=a.getHours(void 0);return a===0?12:a-P(a/13)*12}},{ba:"HH?|24hr",format:function(a){return a.getHours()}},{ba:"dd?|date|day",format:function(a){return a.getDate()}},{ba:"dow|weekday",na:j,format:function(a,b,c){return b.weekdays[a.getDay()+(c-1)*7]}},{ba:"MM?",format:function(a){return a.getMonth()+1}},{ba:"mon|month",na:j,format:function(a,b,c){return b.months[a.getMonth()+(c-1)*12]}},{ba:"y{2,4}|year",format:function(a){return a.getFullYear()}},{ba:"[Tt]{1,2}",
format:function(a,b,c,d){a=b.ampm[P(a.getHours()/12)];if(d.length===1)a=a.slice(0,1);if(d.slice(0,1)==="T")a=a.toUpperCase();return a}},{ba:"z{1,4}|tz|timezone",text:j,format:function(a,b,c,d){a=a.getUTCOffset();if(d=="z"||d=="zz")a=a.replace(/(\d{2})(\d{2})/,function(e,g){return Q(g,d.length)});return a}},{ba:"iso(tz|timezone)",format:function(a){return a.getUTCOffset(j)}},{ba:"ord",format:function(a){a=a.getDate();return a+pa(a)}}],Za=[{$:"year",method:"FullYear",ja:j,da:function(a){return(365+
(a?a.isLeapYear()?1:0:0.25))*24*60*60*1E3}},{$:"month",method:"Month",ja:j,da:function(a,b){var c=30.4375,d;if(a){d=a.daysInMonth();if(b<=d.days())c=d}return c*24*60*60*1E3}},{$:"week",method:"Week",da:aa(6048E5)},{$:"day",method:"Date",ja:j,da:aa(864E5)},{$:"hour",method:"Hours",da:aa(36E5)},{$:"minute",method:"Minutes",da:aa(6E4)},{$:"second",method:"Seconds",da:aa(1E3)},{$:"millisecond",method:"Milliseconds",da:aa(1)}],$a={};function ab(a){na(this,a);this.ga=Xa.concat()}
ab.prototype={getMonth:function(a){return A(a)?a-1:this.months.indexOf(a)%12},ka:function(a){return this.weekdays.indexOf(a)%7},qa:function(a){var b;return A(a)?a:a&&(b=this.numbers.indexOf(a))!==-1?(b+1)%10:1},wa:function(a){var b=this;return a.replace(r(this.num,"g"),function(c){return b.qa(c)||""})},ua:function(a){return V.units[this.units.indexOf(a)%8]},Ca:function(a){return this.pa(a,a[2]>0?"future":"past")},ta:function(a){return this.pa(bb(a),"duration")},xa:function(a){a=a||this.code;return a===
"en"||a==="en-US"?j:this.variant},Aa:function(a){return a===this.ampm[1]},pa:function(a,b){var c=a[0],d=a[1],e=a[2],g,f,i;if(this.code=="ru"){i=c.toString().slice(-1);switch(j){case i==1:i=1;break;case i>=2&&i<=4:i=2;break;default:i=3}}else i=this.plural&&c>1?1:0;f=this.units[i*8+d]||this.units[d];if(this.capitalizeUnit)f=cb(f);g=this.modifiers.filter(function(h){return h.name=="sign"&&h.value==(e>0?1:-1)})[0];return this[b].replace(/\{(.*?)\}/g,function(h,k){switch(k){case "num":return c;case "unit":return f;
case "sign":return g.src}})},va:function(){return this.oa?[this.oa].concat(this.ga):this.ga},addFormat:function(a,b,c,d,e){var g=c||[],f=this,i;a=a.replace(/\s+/g,"[-,. ]*");a=a.replace(/\{([^,]+?)\}/g,function(h,k){var n=k.match(/\?$/),o=k.match(/(\d)(?:-(\d))?/),w=k.match(/^\d+$/),G=k.replace(/[^a-z]+$/,""),F,N;if(w)F=f.optionals[w[0]];else if(f[G])F=f[G];else if(f[G+"s"]){F=f[G+"s"];if(o){N=[];F.forEach(function(Ca,$){var Da=$%(f.units?8:F.length);if(Da>=o[1]&&Da<=(o[2]||o[1]))N.push(Ca)});F=N}F=
db(F)}if(w)return"(?:"+F+")?";else{c||g.push(G);return"("+F+")"+(n?"?":"")}});if(b){b=eb(Ta,f,e);e=["t","[\\s\\u3000]"].concat(f.timeMarker);i=a.match(/\\d\{\d,\d\}\)+\??$/);fb(f,"(?:"+b+")[,\\s\\u3000]+?"+a,Sa.concat(g),d);fb(f,a+"(?:[,\\s]*(?:"+e.join("|")+(i?"+":"*")+")"+b+")?",g.concat(Sa),d)}else fb(f,a,g,d)}};function gb(a,b){var c;B(a)||(a="");c=$a[a]||$a[a.slice(0,2)];if(b===m&&!c)throw Error("Invalid locale.");return c||Ra}
function hb(a,b){function c(i){var h=f[i];if(B(h))f[i]=h.split(",");else h||(f[i]=[])}function d(i,h){i=i.split("+").map(function(k){return k.replace(/(.+):(.+)$/,function(n,o,w){return w.split("|").map(function(G){return o+G}).join("|")})}).join("|");return i.split("|").forEach(h)}function e(i,h,k){var n=[];if(f[i]){f[i].forEach(function(o,w){d(o,function(G,F){n[F*k+w]=G.toLowerCase()})});if(h)n=n.concat(f[i].map(function(o){return o.slice(0,3).toLowerCase()}));return f[i]=n}}function g(i,h,k){i=
"\\d{"+i+","+h+"}";if(k)i+="|(?:"+db(f.numbers)+")+";return i}var f;f=new ab(b);c("modifiers");"months,weekdays,units,numbers,articles,optionals,timeMarker,ampm,timeSuffixes,dateParse,timeParse".split(",").forEach(c);e("months",j,12);e("weekdays",j,7);e("units",m,8);e("numbers",m,10);f.code=a;f.date=g(1,2,f.digitDate);f.year=g(4,4);f.num=function(){var i=["\\d+"].concat(f.articles);if(f.numbers)i=i.concat(f.numbers);return db(i)}();(function(){var i=[];f.ha={};f.modifiers.forEach(function(h){var k=
h.name;d(h.src,function(n){var o=f[k];f.ha[n]=h;i.push({name:k,src:n,value:h.value});f[k]=o?o+"|"+n:n})});f.day+="|"+db(f.weekdays);f.modifiers=i})();if(f.monthSuffix){f.month=g(1,2);f.months=M(1,12).map(function(i){return i+f.monthSuffix})}f.full_month=g(1,2)+"|"+db(f.months);f.timeSuffixes.length>0&&f.addFormat(eb(Ta,f),m,Sa);f.addFormat("{day}",j);f.addFormat("{month}"+(f.monthSuffix||""));f.addFormat("{year}"+(f.yearSuffix||""));f.timeParse.forEach(function(i){f.addFormat(i,j)});f.dateParse.forEach(function(i){f.addFormat(i)});
return $a[a]=f}function fb(a,b,c,d){a.ga.unshift({Da:d,za:a,Ba:r("^"+b+"$","i"),to:c})}function cb(a){return a.slice(0,1).toUpperCase()+a.slice(1)}function db(a){return a.filter(function(b){return!!b}).join("|")}function ib(a,b){var c;if(la(a[0]))return a;else if(A(a[0])&&!A(a[1]))return[a[0]];else if(B(a[0])&&b)return[jb(a[0]),a[1]];c={};Wa.forEach(function(d,e){c[d.$]=a[e]});return[c]}
function jb(a,b){var c={};match=a.match(/^(\d+)?\s?(\w+?)s?$/i);if(K(b))b=parseInt(match[1])||1;c[match[2].toLowerCase()]=b;return c}function kb(a,b){var c={},d,e;b.forEach(function(g,f){d=a[f+1];if(!(K(d)||d==="")){if(g==="year")c.Ea=d;e=parseFloat(d.replace(/,/,"."));c[g]=!isNaN(e)?e:d.toLowerCase()}});return c}function lb(a){a=a.trim().replace(/^(just )?now|\.+$/i,"");return mb(a)}
function mb(a){return a.replace(Va,function(b,c,d){var e=0,g=1,f,i;if(c)return b;d.split("").reverse().forEach(function(h){h=Ua[h];var k=h>9;if(k){if(f)e+=g;g*=h/(i||1);i=h}else{if(f===m)g*=10;e+=g*h}f=k});if(f)e+=g;return e})}
function nb(a,b,c){var d=new s,e=m,g,f,i,h,k,n,o,w,G;if(fa(a))d=a.clone();else if(A(a))d=new s(a);else if(la(a)){d=(new s).set(a,j);h=a}else if(B(a)){g=gb(b);a=lb(a);g&&H(g.va(),function(F,N){var Ca=a.match(N.Ba);if(Ca){i=N;f=i.za;h=kb(Ca,i.to,f);f.oa=i;if(h.timestamp){h=h.timestamp;return m}if(i.Da&&!B(h.month)&&(B(h.date)||g.xa(b))){w=h.month;h.month=h.date;h.date=w}if(h.year&&h.Ea.length===2)h.year=O((new s).getFullYear()/100)*100-O(h.year/100)*100+h.year;if(h.month){h.month=f.getMonth(h.month);
if(h.shift&&!h.unit)h.unit=f.units[7]}if(h.weekday&&h.date)delete h.weekday;else if(h.weekday){h.weekday=f.ka(h.weekday);if(h.shift&&!h.unit)h.unit=f.units[5]}if(h.day&&(w=f.ha[h.day])){h.day=w.value;d.reset();e=j}else if(h.day&&(n=f.ka(h.day))>-1){delete h.day;if(h.num&&h.month){G=function(){var $=d.ka();d.Ga(7*(h.num-1)+($>n?n+7:n))};h.day=1}else h.weekday=n}if(h.date&&!A(h.date))h.date=f.wa(h.date);if(f.Aa(h.ampm)&&h.hour<12)h.hour+=12;if("offset_hours"in h||"offset_minutes"in h){h.utc=j;h.offset_minutes=
h.offset_minutes||0;h.offset_minutes+=h.offset_hours*60;if(h.offset_sign==="-")h.offset_minutes*=-1;h.minute-=h.offset_minutes}if(h.unit){e=j;o=f.qa(h.num);k=f.ua(h.unit);if(h.shift||h.edge){o*=(w=f.ha[h.shift])?w.value:0;if(k==="month"&&J(h.date)){d.set({day:h.date},j);delete h.date}if(k==="year"&&J(h.month)){d.set({month:h.month,day:h.date},j);delete h.month;delete h.date}}if(h.sign&&(w=f.ha[h.sign]))o*=w.value;if(J(h.weekday)){d.set({weekday:h.weekday},j);delete h.weekday}h[k]=(h[k]||0)+o}if(h.year_sign===
"-")h.year*=-1;W.slice(1,4).forEach(function($,Da){var vb=h[$.$],wb=vb%1;if(wb){h[W[Da].$]=O(wb*($.$==="second"?1E3:60));h[$.$]=P(vb)}});return m}});if(i)if(e)d.advance(h);else{h.utc&&d.reset();ob(d,h,j,h.utc,m,c)}else d=a?new s(a):new s;if(h&&h.edge){w=f.ha[h.edge];H(W.slice(4),function(F,N){if(J(h[N.$])){k=N.$;return m}});if(k==="year")h.fa="month";else if(k==="month"||k==="week")h.fa="day";d[(w.value<0?"endOf":"beginningOf")+cb(k)]();w.value===-2&&d.reset()}G&&G()}return{ea:d,set:h}}
function pb(a){a.addDays(4-(a.getDay()||7)).reset();return 1+P(a.daysSince(a.clone().beginningOfYear())/7)}function bb(a){var b,c=v.abs(a),d=c,e=0;W.slice(1).forEach(function(g,f){b=P(O(c/g.da()*10)/10);if(b>=1){d=b;e=f+1}});return[d,e,a]}
function qb(a,b,c,d){var e,g=gb(d),f=r(/^[A-Z]/);if(a.isValid())if(Date[b])b=Date[b];else{if(z(b)){e=bb(a.millisecondsFromNow());b=b.apply(a,e.concat(g))}}else return"Invalid Date";if(!b&&c){e=e||bb(a.millisecondsFromNow());if(e[1]===0){e[1]=1;e[0]=1}return g.Ca(e)}b=b||"long";b=g[b]||b;Ya.forEach(function(i){b=b.replace(r("\\{("+i.ba+")(\\d)?\\}",i.na?"i":""),function(h,k,n){h=i.format(a,g,n||1,k);n=k.length;var o=k.match(/^(.)\1+$/);if(i.na){if(n===3)h=h.slice(0,3);if(o||k.match(f))h=cb(h)}else if(o&&
!i.text)h=(A(h)?Q(h,n):h.toString()).slice(-n);return h})});return b}function rb(a,b,c){var d=nb(b),e=0,g=b=0,f;if(c>0){b=g=c;f=j}if(!d.ea.isValid())return m;if(d.set&&d.set.fa){Za.forEach(function(h){if(h.$===d.set.fa)e=h.da(d.ea,a-d.ea)-1});c=cb(d.set.fa);if(d.set.edge||d.set.shift)d.ea["beginningOf"+c]();if(d.set.fa==="month")i=d.ea.clone()["endOf"+c]().getTime();if(!f&&d.set.sign&&d.set.fa!="millisecond"){b=50;g=-50}}f=a.getTime();c=d.ea.getTime();var i=i||c+e;return f>=c-b&&f<=i+g}
function ob(a,b,c,d,e,g){function f(k){return J(b[k])?b[k]:b[k+"s"]}var i,h;if(A(b)&&e)b={milliseconds:b};else if(A(b)){a.setTime(b);return a}if(b.date)b.day=b.date;H(W,function(k,n){var o=n.$==="day";if(J(f(n.$))||o&&J(f("weekday"))){b.fa=n.$;h=+k;return m}else if(c&&n.$!=="week"&&(!o||!J(f("week"))))a["set"+(d?"UTC":"")+n.method](o?1:0)});Za.forEach(function(k){var n=k.$;k=k.method;var o;o=f(n);if(!K(o)){if(e){if(n==="week"){o=(b.day||0)+o*7;k="Date"}o=o*e+a["get"+k](void 0)}else n==="month"&&J(f("day"))&&
a.setDate(15);a["set"+(d?"UTC":"")+k](o);if(e&&n==="month"){n=o;if(n<0)n+=12;n%12!=a.getMonth()&&a.setDate(0)}}});if(!e&&!J(f("day"))&&J(f("weekday"))){i=f("weekday");a["set"+(d?"UTC":"")+"Weekday"](i)}(function(){var k=new s;return g===-1&&a>k||g===1&&a<k})()&&H(W.slice(h+1),function(k,n){if((n.ja||n.$==="week"&&J(f("weekday")))&&!J(f(n.$))){a[n.ia](g);return m}});return a}
function eb(a,b,c){var d={h:0,m:1,s:2},e;b=b||V;return a.replace(/{([a-z])}/g,function(g,f){var i=[],h=f==="h",k=h&&!c;if(f==="t")return b.ampm.join("|");else{h&&i.push(":");if(e=b.timeSuffixes[d[f]])i.push(e+"\\s*");return i.length===0?"":"(?:"+i.join("|")+")"+(k?"":"?")}})}function sb(a,b){var c;c=A(a[1])?ib(a)[0]:a[0];return nb(c,a[1],b).ea}
s.extend({create:function(){return sb(arguments)},past:function(){return sb(arguments,-1)},future:function(){return sb(arguments,1)},addLocale:function(a,b){return hb(a,b)},setLocale:function(a){var b=gb(a,m);Ra=b;if(a&&a!=b.code)b.code=a;return b},getLocale:function(a){return!a?Ra:gb(a,m)},addFormat:function(a,b,c){fb(gb(c),a,b)}},m,m);
s.extend({set:function(){var a=ib(arguments);return ob(this,a[0],a[1])},setUTC:function(){var a=ib(arguments);return ob(this,a[0],a[1],j)},setWeekday:function(a){if(!K(a))return this.setDate(this.getDate()+a-this.getDay())},setUTCWeekday:function(a){if(!K(a))return this.setDate(this.getUTCDate()+a-this.getDay())},setWeek:function(a){if(!K(a)){this.setMonth(0);this.setDate(a*7+1)}},setUTCWeek:function(a){if(!K(a)){this.setMonth(0);this.setUTCDate(a*7+1)}},getWeek:function(){return pb(this)},getUTCWeek:function(){return pb(this.toUTC())},
getUTCOffset:function(a){var b=this.ma?0:this.getTimezoneOffset(),c=a===j?":":"";if(!b&&a)return"Z";return Q(O(-b/60),2,j)+c+Q(b%60,2)},toUTC:function(){if(this.ma)return this;var a=this.clone().addMinutes(this.getTimezoneOffset());a.ma=j;return a},isUTC:function(){return this.ma||this.getTimezoneOffset()===0},advance:function(){var a=ib(arguments,j);return ob(this,a[0],a[1],m,1)},rewind:function(){var a=ib(arguments,j);return ob(this,a[0],a[1],m,-1)},isValid:function(){return!isNaN(this.getTime())},
isAfter:function(a,b){return this.getTime()>s.create(a).getTime()-(b||0)},isBefore:function(a,b){return this.getTime()<s.create(a).getTime()+(b||0)},isBetween:function(a,b,c){var d=this.getTime();a=s.create(a).getTime();var e=s.create(b).getTime();b=v.min(a,e);a=v.max(a,e);c=c||0;return b-c<d&&a+c>d},isLeapYear:function(){var a=this.getFullYear();return a%4===0&&a%100!==0||a%400===0},daysInMonth:function(){return 32-(new s(this.getFullYear(),this.getMonth(),32)).getDate()},format:function(a,b){return qb(this,
a,m,b)},relative:function(a,b){if(B(a)){b=a;a=l}return qb(this,a,j,b)},is:function(a,b){var c;if(this.isValid()){if(B(a)){a=a.trim().toLowerCase();switch(j){case a==="future":return this.getTime()>(new s).getTime();case a==="past":return this.getTime()<(new s).getTime();case a==="weekday":return this.getDay()>0&&this.getDay()<6;case a==="weekend":return this.getDay()===0||this.getDay()===6;case (c=V.weekdays.indexOf(a)%7)>-1:return this.getDay()===c;case (c=V.months.indexOf(a)%12)>-1:return this.getMonth()===
c}}return rb(this,a,b)}},reset:function(a){var b={},c;a=a||"hours";if(a==="date")a="days";c=Za.some(function(d){return a===d.$||a===d.$+"s"});b[a]=a.match(/^days?/)?1:0;return c?this.set(b,j):this},clone:function(){return new s(this.getTime())}});s.extend({iso:function(){return this.toISOString()},getWeekday:s.prototype.getDay,getUTCWeekday:s.prototype.getUTCDay});
function tb(a,b){function c(){return O(this*b)}function d(){return sb(arguments)[a.ia](this)}function e(){return sb(arguments)[a.ia](-this)}var g=a.$,f={};f[g]=c;f[g+"s"]=c;f[g+"Before"]=e;f[g+"sBefore"]=e;f[g+"Ago"]=e;f[g+"sAgo"]=e;f[g+"After"]=d;f[g+"sAfter"]=d;f[g+"FromNow"]=d;f[g+"sFromNow"]=d;u.extend(f)}u.extend({duration:function(a){return gb(a).ta(this)}});
V=Ra=s.addLocale("en",{plural:j,timeMarker:"at",ampm:"am,pm",months:"January,February,March,April,May,June,July,August,September,October,November,December",weekdays:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",units:"millisecond:|s,second:|s,minute:|s,hour:|s,day:|s,week:|s,month:|s,year:|s",numbers:"one,two,three,four,five,six,seven,eight,nine,ten",articles:"a,an,the",optionals:"the,st|nd|rd|th,of","short":"{Month} {d}, {yyyy}","long":"{Month} {d}, {yyyy} {h}:{mm}{tt}",full:"{Weekday} {Month} {d}, {yyyy} {h}:{mm}:{ss}{tt}",
past:"{num} {unit} {sign}",future:"{num} {unit} {sign}",duration:"{num} {unit}",modifiers:[{name:"day",src:"yesterday",value:-1},{name:"day",src:"today",value:0},{name:"day",src:"tomorrow",value:1},{name:"sign",src:"ago|before",value:-1},{name:"sign",src:"from now|after|from|in",value:1},{name:"edge",src:"last day",value:-2},{name:"edge",src:"end",value:-1},{name:"edge",src:"first day|beginning",value:1},{name:"shift",src:"last",value:-1},{name:"shift",src:"the|this",value:0},{name:"shift",src:"next",
value:1}],dateParse:["{num} {unit} {sign}","{sign} {num} {unit}","{num} {unit=4-5} {sign} {day}","{month} {year}","{shift} {unit=5-7}","{0} {edge} of {shift?} {unit=4-7?}{month?}{year?}"],timeParse:["{0} {num}{1} {day} of {month} {year?}","{weekday?} {month} {date}{1} {year?}","{date} {month} {year}","{shift} {weekday}","{shift} week {weekday}","{weekday} {2} {shift} week","{0} {date}{1} of {month}","{0}{month?} {date?}{1} of {shift} {unit=6-7}"]});W=Za.concat().reverse();Wa=Za.concat();
Wa.splice(2,1);
I(s,j,m,Za,function(a,b,c){var d=b.$,e=cb(d),g=b.da(),f,i;b.ia="add"+e+"s";f=function(h,k){return O((this.getTime()-s.create(h,k).getTime())/g)};i=function(h,k){return O((s.create(h,k).getTime()-this.getTime())/g)};a[d+"sAgo"]=i;a[d+"sUntil"]=i;a[d+"sSince"]=f;a[d+"sFromNow"]=f;a[b.ia]=function(h,k){var n={};n[d]=h;return this.advance(n,k)};tb(b,g);c<3&&["Last","This","Next"].forEach(function(h){a["is"+h+e]=function(){return this.is(h+" "+d)}});if(c<4){a["beginningOf"+e]=function(){var h={};switch(d){case "year":h.year=
this.getFullYear();break;case "month":h.month=this.getMonth();break;case "day":h.day=this.getDate();break;case "week":h.weekday=0}return this.set(h,j)};a["endOf"+e]=function(){var h={hours:23,minutes:59,seconds:59,milliseconds:999};switch(d){case "year":h.month=11;h.day=31;break;case "month":h.day=this.daysInMonth();break;case "week":h.weekday=6}return this.set(h,j)}}});V.addFormat("([+-])?(\\d{4,4})[-.]?{full_month}[-.]?(\\d{1,2})?",j,["year_sign","year","month","date"],m,j);
V.addFormat("(\\d{1,2})[-.\\/]{full_month}(?:[-.\\/](\\d{2,4}))?",j,["date","month","year"],j);V.addFormat("{full_month}[-.](\\d{4,4})",m,["month","year"]);V.addFormat("\\/Date\\((\\d+(?:\\+\\d{4,4})?)\\)\\/",m,["timestamp"]);V.addFormat(eb(Ta,V),m,Sa);Xa=V.ga.slice(0,7).reverse();V.ga=V.ga.slice(7).concat(Xa);I(s,j,m,"short,long,full",function(a,b){a[b]=function(c){return qb(this,b,m,c)}});
"\u3007\u4e00\u4e8c\u4e09\u56db\u4e94\u516d\u4e03\u516b\u4e5d\u5341\u767e\u5343\u4e07".split("").forEach(function(a,b){if(b>9)b=v.pow(10,b-9);Ua[a]=b});"\uff10\uff11\uff12\uff13\uff14\uff15\uff16\uff17\uff18\uff19".split("").forEach(function(a,b){Ua[a]=b});Va=r("([\u671f\u9031\u5468])?([\u3007\u4e00\u4e8c\u4e09\u56db\u4e94\u516d\u4e03\u516b\u4e5d\u5341\u767e\u5343\u4e07\uff10\uff11\uff12\uff13\uff14\uff15\uff16\uff17\uff18\uff19]+)(?!\u6628)","g");
(function(){var a="today,yesterday,tomorrow,weekday,weekend,future,past".split(","),b=V.weekdays.slice(0,7),c=V.months.slice(0,12);I(s,j,m,a.concat(b).concat(c),function(d,e){d["is"+cb(e)]=function(){return this.is(e)}})})();s.extend({RFC1123:"{Dow}, {dd} {Mon} {yyyy} {HH}:{mm}:{ss} {tz}",RFC1036:"{Weekday}, {dd}-{Mon}-{yy} {HH}:{mm}:{ss} {tz}",ISO8601_DATE:"{yyyy}-{MM}-{dd}",ISO8601_DATETIME:"{yyyy}-{MM}-{dd}T{HH}:{mm}:{ss}.{fff}{isotz}"},m,m);
