var Fb=[],Gb=[],X=[],Hb=[],Ib={},Jb,Y;function Kb(a,b){var c=a.indexOf(b);c>-1&&a.splice(c,1)}
function Lb(a,b,c){B(b)&&Kb(X,b);Kb(X,c);a.unshift({la:b,ra:c})}function Mb(a,b){return a==b||a=="all"||!a}function Nb(a){return X.some(function(b){return(new r("\\b"+b+"$","i")).test(a)})}function Ob(a,b){a=B(a)?a.toString():"";return a.isBlank()||Nb(a)?a:Pb(a,b?Fb:Gb)}function Pb(a,b){G(b,function(c,d){if(a.match(d.la)){a=a.replace(d.la,d.ra);return m}});return a}function Qb(a){return a.replace(/^\W*[a-z]/,function(b){return b.toUpperCase()})}
Y={acronym:function(a){Ib[a.toLowerCase()]=a;a=p.keys(Ib).map(function(b){return Ib[b]});Y.acronymRegExp=r(a.join("|"),"g")},plural:function(a,b){Lb(Fb,a,b)},singular:function(a,b){Lb(Gb,a,b)},irregular:function(a,b){var c=a.first(),d=a.from(1),e=b.first(),g=b.from(1),f=e.toUpperCase(),i=e.toLowerCase(),h=c.toUpperCase(),j=c.toLowerCase();Kb(X,a);Kb(X,b);if(h==f){Y.plural(new r("({1}){2}$".assign(c,d),"i"),"$1"+g);Y.plural(new r("({1}){2}$".assign(e,g),"i"),"$1"+g);Y.singular(new r("({1}){2}$".assign(e,
g),"i"),"$1"+d)}else{Y.plural(new r("{1}{2}$".assign(h,d)),f+g);Y.plural(new r("{1}{2}$".assign(j,d)),i+g);Y.plural(new r("{1}{2}$".assign(f,g)),f+g);Y.plural(new r("{1}{2}$".assign(i,g)),i+g);Y.singular(new r("{1}{2}$".assign(f,g)),h+d);Y.singular(new r("{1}{2}$".assign(i,g)),j+d)}},uncountable:function(a){var b=q.isArray(a)?a:E(arguments);X=X.concat(b)},human:function(a,b){Hb.unshift({la:a,ra:b})},clear:function(a){if(Mb(a,"singulars"))Gb=[];if(Mb(a,"plurals"))Fb=[];if(Mb(a,"uncountables"))X=[];
if(Mb(a,"humans"))Hb=[];if(Mb(a,"acronyms"))Ib={}}};Jb=["and","or","nor","a","an","the","so","but","to","of","at","by","from","into","on","onto","off","out","in","over","with","for"];Y.plural(/$/,"s");Y.plural(/s$/gi,"s");Y.plural(/(ax|test)is$/gi,"$1es");Y.plural(/(octop|vir|fung|foc|radi|alumn)(i|us)$/gi,"$1i");Y.plural(/(census|alias|status)$/gi,"$1es");Y.plural(/(bu)s$/gi,"$1ses");Y.plural(/(buffal|tomat)o$/gi,"$1oes");Y.plural(/([ti])um$/gi,"$1a");Y.plural(/([ti])a$/gi,"$1a");
Y.plural(/sis$/gi,"ses");Y.plural(/f+e?$/gi,"ves");Y.plural(/(cuff|roof)$/gi,"$1s");Y.plural(/([ht]ive)$/gi,"$1s");Y.plural(/([^aeiouy]o)$/gi,"$1es");Y.plural(/([^aeiouy]|qu)y$/gi,"$1ies");Y.plural(/(x|ch|ss|sh)$/gi,"$1es");Y.plural(/(matr|vert|ind)(?:ix|ex)$/gi,"$1ices");Y.plural(/([ml])ouse$/gi,"$1ice");Y.plural(/([ml])ice$/gi,"$1ice");Y.plural(/^(ox)$/gi,"$1en");Y.plural(/^(oxen)$/gi,"$1");Y.plural(/(quiz)$/gi,"$1zes");Y.plural(/(phot|cant|hom|zer|pian|portic|pr|quart|kimon)o$/gi,"$1os");
Y.plural(/(craft)$/gi,"$1");Y.plural(/([ft])[eo]{2}(th?)$/gi,"$1ee$2");Y.singular(/s$/gi,"");Y.singular(/([pst][aiu]s)$/gi,"$1");Y.singular(/([aeiouy])ss$/gi,"$1ss");Y.singular(/(n)ews$/gi,"$1ews");Y.singular(/([ti])a$/gi,"$1um");Y.singular(/((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$/gi,"$1$2sis");Y.singular(/(^analy)ses$/gi,"$1sis");Y.singular(/(i)(f|ves)$/i,"$1fe");Y.singular(/([aeolr]f?)(f|ves)$/i,"$1f");Y.singular(/([ht]ive)s$/gi,"$1");Y.singular(/([^aeiouy]|qu)ies$/gi,"$1y");
Y.singular(/(s)eries$/gi,"$1eries");Y.singular(/(m)ovies$/gi,"$1ovie");Y.singular(/(x|ch|ss|sh)es$/gi,"$1");Y.singular(/([ml])(ous|ic)e$/gi,"$1ouse");Y.singular(/(bus)(es)?$/gi,"$1");Y.singular(/(o)es$/gi,"$1");Y.singular(/(shoe)s?$/gi,"$1");Y.singular(/(cris|ax|test)[ie]s$/gi,"$1is");Y.singular(/(octop|vir|fung|foc|radi|alumn)(i|us)$/gi,"$1us");Y.singular(/(census|alias|status)(es)?$/gi,"$1");Y.singular(/^(ox)(en)?/gi,"$1");Y.singular(/(vert|ind)(ex|ices)$/gi,"$1ex");
Y.singular(/(matr)(ix|ices)$/gi,"$1ix");Y.singular(/(quiz)(zes)?$/gi,"$1");Y.singular(/(database)s?$/gi,"$1");Y.singular(/ee(th?)$/gi,"oo$1");Y.irregular("person","people");Y.irregular("man","men");Y.irregular("child","children");Y.irregular("sex","sexes");Y.irregular("move","moves");Y.irregular("save","saves");Y.irregular("save","saves");Y.irregular("cow","kine");Y.irregular("goose","geese");Y.irregular("zombie","zombies");Y.uncountable("equipment,information,rice,money,species,series,fish,sheep,jeans".split(","));
D(t,k,m,{pluralize:function(){return Ob(this,k)},singularize:function(){return Ob(this,m)},humanize:function(){var a=Pb(this,Hb);a=a.replace(/_id$/g,"");a=a.replace(/(_)?([a-z\d]*)/gi,function(b,c,d){return(c?" ":"")+(Ib[d]||d.toLowerCase())});return Qb(a)},titleize:function(){var a=/[.:;!]$/,b,c,d;return this.spacify().humanize().words(function(e,g,f){b=a.test(e);d=g==0||g==f.length-1||b||c;c=b;return d||Jb.indexOf(e)===-1?Qb(e):e}).join(" ")},parameterize:function(a){var b=this;if(a===undefined)a=
"-";if(b.normalize)b=b.normalize();b=b.replace(/[^a-z0-9\-_]+/gi,a);if(a)b=b.replace(new r("^{sep}+|{sep}+$|({sep}){sep}+".assign({sep:R(a)}),"g"),"$1");return encodeURI(b.toLowerCase())}});t.Inflector=Y;t.Inflector.acronyms=Ib;
