function Aa(a,b,c,d){var e=k;if(a===b)return k;else if(E(b)&&D(a))return q(b).test(a);else if(A(b)&&!A(a))return b.apply(c,d);else if(L(b)&&la(a)){H(b,function(f){Aa(a[f],b[f],c,[a[f],a])||(e=m)});return e}else return ta(a)&&ta(b)?sa(a)===sa(b):a===b}function T(a,b,c,d){return K(b)?a:A(b)?b.apply(c,d||[]):A(a[b])?a[b].call(a):a[b]}
function U(a,b,c,d){var e,f;if(c<0)c=a.length+c;f=isNaN(c)?0:c;for(c=d===k?a.length+f:a.length;f<c;){e=f%a.length;if(e in a){if(b.call(a,a[e],e,a)===m)break}else return Ba(a,b,f,d);f++}}function Ba(a,b,c){var d=[],e;for(e in a)e in a&&e>>>0==e&&e!=4294967295&&e>=c&&d.push(parseInt(e));d.sort().each(function(f){return b.call(a,a[f],f,a)});return a}function Ca(a,b,c,d,e){var f,g;U(a,function(j,i,h){if(Aa(j,b,h,[j,i,h])){f=j;g=i;return m}},c,d);return e?g:f}
function Ea(a,b){var c=[],d={},e;U(a,function(f,g){e=b?T(f,b,a,[f,g,a]):f;Fa(d,e)||c.push(f)});return c}function Ga(a,b,c){var d=[],e={};b.each(function(f){Fa(e,f)});a.each(function(f){var g=sa(f),j=!ta(f);if(Ha(e,g,f,j)!=c){var i=0;if(j)for(g=e[g];i<g.length;)if(g[i]===f)g.splice(i,1);else i+=1;else delete e[g];d.push(f)}});return d}function Ia(a,b,c){b=b||Infinity;c=c||0;var d=[];U(a,function(e){if(fa(e)&&c<b)d=d.concat(Ia(e,b,c+1));else d.push(e)});return d}
function Ja(a){var b=[];G(a,function(c){b=b.concat(c)});return b}function Ha(a,b,c,d){var e=b in a;if(d){a[b]||(a[b]=[]);e=a[b].indexOf(c)!==-1}return e}function Fa(a,b){var c=sa(b),d=!ta(b),e=Ha(a,c,b,d);if(d)a[c].push(b);else a[c]=b;return e}function Ka(a,b,c,d){var e,f=[],g=c==="max",j=c==="min",i=Array.isArray(a);H(a,function(h){var n=a[h];h=T(n,b,a,i?[n,parseInt(h),a]:[]);if(h===e)f.push(n);else if(K(e)||g&&h>e||j&&h<e){f=[n];e=h}});i||(f=Ia(f,1));return d?f:f[0]}
function La(a){if(p[Ma])a=a.toLowerCase();return a.replace(p[Na],"")}function Oa(a,b){var c=a.charAt(b);return(p[Pa]||{})[c]||c}function Qa(a){var b=p[Ra];return a?b.indexOf(a):l}var Ra="AlphanumericSortOrder",Na="AlphanumericSortIgnore",Ma="AlphanumericSortIgnoreCase",Pa="AlphanumericSortEquivalents";F(p,m,m,{create:function(){var a=[];G(arguments,function(b){if(la(b))a=a.concat(p.prototype.slice.call(b));else a.push(b)});return a}});
F(p,k,m,{find:function(a,b,c){return Ca(this,a,b,c)},findAll:function(a,b,c){var d=[];U(this,function(e,f,g){Aa(e,a,g,[e,f,g])&&d.push(e)},b,c);return d},findIndex:function(a,b,c){a=Ca(this,a,b,c,k);return K(a)?-1:a},count:function(a){if(K(a))return this.length;return this.findAll(a).length},removeAt:function(a,b){if(K(a))return this;if(K(b))b=a;for(var c=0;c<=b-a;c++)this.splice(a,1);return this},include:function(a,b){return this.clone().add(a,b)},exclude:function(){return p.prototype.remove.apply(this.clone(),
arguments)},clone:function(){return na([],this)},unique:function(a){return Ea(this,a)},flatten:function(a){return Ia(this,a)},union:function(){return Ea(this.concat(Ja(arguments)))},intersect:function(){return Ga(this,Ja(arguments),m)},subtract:function(){return Ga(this,Ja(arguments),k)},at:function(){return ua(this,arguments)},first:function(a){if(K(a))return this[0];if(a<0)a=0;return this.slice(0,a)},last:function(a){if(K(a))return this[this.length-1];return this.slice(this.length-a<0?0:this.length-
a)},from:function(a){return this.slice(a)},to:function(a){if(K(a))a=this.length;return this.slice(0,a)},min:function(a,b){return Ka(this,a,"min",b)},max:function(a,b){return Ka(this,a,"max",b)},least:function(a,b){return Ka(this.groupBy.apply(this,[a]),"length","min",b)},most:function(a,b){return Ka(this.groupBy.apply(this,[a]),"length","max",b)},sum:function(a){a=a?this.map(a):this;return a.length>0?a.reduce(function(b,c){return b+c}):0},average:function(a){a=a?this.map(a):this;return a.length>0?
a.sum()/a.length:0},inGroups:function(a,b){var c=arguments.length>1,d=this,e=[],f=O(this.length/a,void 0,"ceil");N(0,a-1,function(g){g=g*f;var j=d.slice(g,g+f);c&&j.length<f&&N(1,f-j.length,function(){j=j.add(b)});e.push(j)});return e},inGroupsOf:function(a,b){var c=[],d=this.length,e=this,f;if(d===0||a===0)return e;if(K(a))a=1;if(K(b))b=l;N(0,O(d/a,void 0,"ceil")-1,function(g){for(f=e.slice(a*g,a*g+a);f.length<a;)f.push(b);c.push(f)});return c},isEmpty:function(){return this.compact().length==0},
sortBy:function(a,b){var c=this.clone();c.sort(function(d,e){var f,g;f=T(d,a,c,[d]);g=T(e,a,c,[e]);if(D(f)&&D(g)){f=f;g=g;var j,i,h,n,r=0,y=0;f=La(f);g=La(g);do{h=Oa(f,r);n=Oa(g,r);j=Qa(h);i=Qa(n);if(j===-1||i===-1){j=f.charCodeAt(r)||l;i=g.charCodeAt(r)||l}h=h!==f.charAt(r);n=n!==g.charAt(r);if(h!==n&&y===0)y=h-n;r+=1}while(j!=l&&i!=l&&j===i);f=j===i?y:j<i?-1:1}else f=f<g?-1:f>g?1:0;return f*(b?-1:1)});return c},randomize:function(){for(var a=this.concat(),b,c,d=a.length;d;b=parseInt(v.random()*
d),c=a[--d],a[d]=a[b],a[b]=c);return a},zip:function(){var a=G(arguments);return this.map(function(b,c){return[b].concat(a.map(function(d){return c in d?d[c]:l}))})},sample:function(a){var b=[],c=this.clone(),d;if(K(a))a=1;for(;b.length<a;){d=P(v.random()*(c.length-1));b.push(c[d]);c.removeAt(d);if(c.length==0)break}return arguments.length>0?b:b[0]},each:function(a,b,c){U(this,a,b,c);return this},add:function(a,b){if(!B(u(b))||isNaN(b))b=this.length;p.prototype.splice.apply(this,[b,0].concat(a));
return this},remove:function(){var a,b=this;G(arguments,function(c){for(a=0;a<b.length;)if(Aa(b[a],c,b,[b[a],a,b]))b.splice(a,1);else a++});return b},compact:function(a){var b=[];U(this,function(c){if(fa(c))b.push(c.compact());else if(a&&c)b.push(c);else!a&&c!=l&&c.valueOf()===c.valueOf()&&b.push(c)});return b},groupBy:function(a,b){var c=this,d={},e;U(c,function(f,g){e=T(f,a,c,[f,g,c]);d[e]||(d[e]=[]);d[e].push(f)});b&&H(d,b);return d},none:function(){return!this.any.apply(this,arguments)}});
F(p,k,m,{all:p.prototype.every,any:p.prototype.some,insert:p.prototype.add});function Sa(a){if(a&&a.valueOf)a=a.valueOf();return o.keys(a)}function Ta(a,b){I(o,m,m,a,function(c,d){c[d]=function(e,f,g){g=p.prototype[d].call(Sa(e),function(j){return b?T(e[j],f,e,[j,e[j],e]):Aa(e[j],f,e,[j,e[j],e])},g);if(fa(g))g=g.reduce(function(j,i){j[i]=e[i];return j},{});return g}});va(a,M)}
F(o,m,m,{map:function(a,b){return Sa(a).reduce(function(c,d){c[d]=T(a[d],b,a,[d,a[d],a]);return c},{})},reduce:function(a){var b=Sa(a).map(function(c){return a[c]});return b.reduce.apply(b,G(arguments).slice(1))},size:function(a){return Sa(a).length}});(function(){I(p,k,function(){var a=arguments;return a.length>0&&!A(a[0])},"map,every,all,some,any,none,filter",function(a,b){a[b]=function(c){return this[b](function(d,e){return b==="map"?T(d,c,this,[d,e,this]):Aa(d,c,this,[d,e,this])})}})})();
(function(){p[Ra]="A\u00c1\u00c0\u00c2\u00c3\u0104BC\u0106\u010c\u00c7D\u010e\u00d0E\u00c9\u00c8\u011a\u00ca\u00cb\u0118FG\u011eH\u0131I\u00cd\u00cc\u0130\u00ce\u00cfJKL\u0141MN\u0143\u0147\u00d1O\u00d3\u00d2\u00d4PQR\u0158S\u015a\u0160\u015eT\u0164U\u00da\u00d9\u016e\u00db\u00dcVWXY\u00ddZ\u0179\u017b\u017d\u00de\u00c6\u0152\u00d8\u00d5\u00c5\u00c4\u00d6".split("").map(function(b){return b+b.toLowerCase()}).join("");var a={};U("A\u00c1\u00c0\u00c2\u00c3\u00c4,C\u00c7,E\u00c9\u00c8\u00ca\u00cb,I\u00cd\u00cc\u0130\u00ce\u00cf,O\u00d3\u00d2\u00d4\u00d5\u00d6,S\u00df,U\u00da\u00d9\u00db\u00dc".split(","),
function(b){var c=b.charAt(0);U(b.slice(1).split(""),function(d){a[d]=c;a[d.toLowerCase()]=c.toLowerCase()})});p[Ma]=k;p[Pa]=a})();Ta("each,any,all,none,count,find,findAll,isEmpty");Ta("sum,average,min,max,least,most",k);va("map,reduce,size",M);
