function xa(a,b,c,d){var f=j;if(a===b)return j;else if(G(b)&&F(a))return t(b).test(a);else if(D(b))return b.apply(c,d);else if(ka(b)&&ja(a)){J(b,function(g){xa(a[g],b[g],c,[a[g],a])||(f=m)});return r.keys(b).length>0&&f}else return U(a)===U(b)}function V(a,b,c,d){return M(b)?a:D(b)?b.apply(c,d||[]):D(a[b])?a[b].call(a):a[b]}
function W(a,b,c,d,f){var g,e;if(c<0)c=a.length+c;e=isNaN(c)?0:c;for(c=d===j?a.length+e:a.length;e<c;){g=e%a.length;if(!(g in a)&&f===j)return ya(a,b,e,d);else if(b.call(a,a[g],g,a)===m)break;e++}}function ya(a,b,c){var d=[],f;for(f in a)f in a&&f>>>0==f&&f!=4294967295&&f>=c&&d.push(parseInt(f));d.sort().each(function(g){return b.call(a,a[g],g,a)});return a}function za(a,b,c,d,f){var g,e;W(a,function(i,h,l){if(xa(i,b,l,[i,h,l])){g=i;e=h;return m}},c,d);return f?e:g}
function Aa(a,b){var c=[],d={},f,g;W(a,function(e,i){g=b?V(e,b,a,[e,i,a]):e;f=U(g);if(!(f in d&&(typeof e!=="function"||e===d[f]))){d[f]=g;c.push(e)}});return c}function Da(a,b,c){var d=[],f={};b.each(function(g){f[U(g)]=g});a.each(function(g){var e=U(g);if((e in f&&(typeof g!=="function"||g===f[e]))!=c){delete f[e];d.push(g)}});return d}function Ea(a,b,c){b=b||Infinity;c=c||0;var d=[];W(a,function(f){if(ca(f)&&c<b)d=d.concat(Ea(f,b,c+1));else d.push(f)});return d}
function Fa(a){var b=[];I(a,function(c){b=b.concat(c)});return b}function Ga(a,b,c,d){var f=c==="max",g=c==="min",e=f?-Infinity:Infinity,i=[];J(a,function(h){var l=a[h];h=V(l,b,a,d?[l,parseInt(h),a]:[]);if(h===e)i.push(l);else if(f&&h>e||g&&h<e){i=[l];e=h}});return i}function Ha(a){if(s[Ia])a=a.toLowerCase();return a.replace(s[Ja],"")}function Ka(a,b){var c=a.charAt(b);return(s[La]||{})[c]||c}function Ma(a){var b=s[Na];return a?b.indexOf(a):k}
var Na="AlphanumericSortOrder",Ja="AlphanumericSortIgnore",Ia="AlphanumericSortIgnoreCase",La="AlphanumericSortEquivalents";H(s,m,m,{create:function(){var a=[];I(arguments,function(b){if(b&&b.callee)b=I(b);a=a.concat(b)});return a}});
H(s,j,m,{find:function(a,b,c){return za(this,a,b,c)},findAll:function(a,b,c){var d=[];W(this,function(f,g,e){xa(f,a,e,[f,g,e])&&d.push(f)},b,c);return d},findIndex:function(a,b,c){a=za(this,a,b,c,j);return M(a)?-1:a},count:function(a){if(M(a))return this.length;return this.findAll(a).length},removeAt:function(a,b){if(M(a))return this;if(M(b))b=a;for(var c=0;c<=b-a;c++)this.splice(a,1);return this},include:function(a,b){return this.clone().add(a,b)},exclude:function(){return s.prototype.remove.apply(this.clone(),
arguments)},clone:function(){return ma([],this)},unique:function(a){return Aa(this,a)},flatten:function(a){return Ea(this,a)},union:function(){return Aa(this.concat(Fa(arguments)))},intersect:function(){return Da(this,Fa(arguments),m)},subtract:function(){return Da(this,Fa(arguments),j)},at:function(){return ra(this,arguments)},first:function(a){if(M(a))return this[0];if(a<0)a=0;return this.slice(0,a)},last:function(a){if(M(a))return this[this.length-1];return this.slice(this.length-a<0?0:this.length-
a)},from:function(a){return this.slice(a)},to:function(a){if(M(a))a=this.length;return this.slice(0,a)},min:function(a){return Aa(Ga(this,a,"min",j))},max:function(a){return Aa(Ga(this,a,"max",j))},least:function(){var a=Ea(Ga(this.groupBy.apply(this,arguments),"length","min"));return a.length===this.length?[]:Aa(a)},most:function(){var a=Ea(Ga(this.groupBy.apply(this,arguments),"length","max"));return a.length===this.length?[]:Aa(a)},sum:function(a){a=a?this.map(a):this;return a.length>0?a.reduce(function(b,
c){return b+c}):0},average:function(a){a=a?this.map(a):this;return a.length>0?a.sum()/a.length:0},inGroups:function(a,b){var c=arguments.length>1,d=this,f=[],g=P(this.length/a,void 0,"ceil");O(0,a-1,function(e){e=e*g;var i=d.slice(e,e+g);c&&i.length<g&&O(1,g-i.length,function(){i=i.add(b)});f.push(i)});return f},inGroupsOf:function(a,b){var c=[],d=this.length,f=this,g;if(d===0||a===0)return f;if(M(a))a=1;if(M(b))b=k;O(0,P(d/a,void 0,"ceil")-1,function(e){for(g=f.slice(a*e,a*e+a);g.length<a;)g.push(b);
c.push(g)});return c},isEmpty:function(){return this.compact().length==0},sortBy:function(a,b){var c=this.clone();c.sort(function(d,f){var g,e;g=V(d,a,c,[d]);e=V(f,a,c,[f]);if(F(g)&&F(e)){g=g;e=e;var i,h,l,n,o=0,p=0;g=Ha(g);e=Ha(e);do{l=Ka(g,o);n=Ka(e,o);i=Ma(l);h=Ma(n);if(i===-1||h===-1){i=g.charCodeAt(o)||k;h=e.charCodeAt(o)||k}l=l!==g.charAt(o);n=n!==e.charAt(o);if(l!==n&&p===0)p=l-n;o+=1}while(i!=k&&h!=k&&i===h);g=i===h?p:i<h?-1:1}else g=g<e?-1:g>e?1:0;return g*(b?-1:1)});return c},randomize:function(){for(var a=
this.concat(),b,c,d=a.length;d;b=parseInt(x.random()*d),c=a[--d],a[d]=a[b],a[b]=c);return a},zip:function(){var a=I(arguments);return this.map(function(b,c){return[b].concat(a.map(function(d){return c in d?d[c]:k}))})},sample:function(a){var b=[],c=this.clone(),d;for(a>0||(a=1);b.length<a;){d=Q(x.random()*(c.length-1));b.push(c[d]);c.removeAt(d);if(c.length==0)break}return arguments.length>0?b:b[0]},each:function(a,b,c){W(this,a,b,c,j);return this},add:function(a,b){if(!E(w(b))||isNaN(b))b=this.length;
s.prototype.splice.apply(this,[b,0].concat(a));return this},remove:function(){var a,b=this;I(arguments,function(c){for(a=0;a<b.length;)if(xa(b[a],c,b,[b[a],a,b]))b.splice(a,1);else a++});return b},compact:function(a){var b=[];W(this,function(c){if(ca(c))b.push(c.compact());else if(a&&c)b.push(c);else!a&&c!=k&&c.valueOf()===c.valueOf()&&b.push(c)});return b},groupBy:function(a,b){var c=this,d={},f;W(c,function(g,e){f=V(g,a,c,[g,e,c]);d[f]||(d[f]=[]);d[f].push(g)});b&&J(d,b);return d},none:function(){return!this.any.apply(this,
arguments)}});H(s,j,m,{all:s.prototype.every,any:s.prototype.some,insert:s.prototype.add});function Oa(a){if(a&&a.valueOf)a=a.valueOf();return r.keys(a)}function Pa(a,b){K(r,m,m,a,function(c,d){c[d]=function(f,g){var e;e=s.prototype[d].call(Oa(f),function(i){return b?V(f[i],g,f,[i,f[i],f]):xa(f[i],g,f,[i,f[i],f])});if(ca(e))e=e.reduce(function(i,h){i[h]=f[h];return i},{});return e}});sa(a,N)}
H(r,m,m,{map:function(a,b){return Oa(a).reduce(function(c,d){c[d]=V(a[d],b,a,[d,a[d],a]);return c},{})},reduce:function(a){var b=Oa(a).map(function(c){return a[c]});return b.reduce.apply(b,I(arguments).slice(1))},size:function(a){return Oa(a).length}});(function(){K(s,j,function(){var a=arguments;return a.length>0&&!D(a[0])},"map,every,all,some,any,none,filter",function(a,b){a[b]=function(c){return this[b](function(d,f){return b==="map"?V(d,c,this,[d,f,this]):xa(d,c,this,[d,f,this])})}})})();
(function(){s[Na]="A\u00c1\u00c0\u00c2\u00c3\u0104BC\u0106\u010c\u00c7D\u010e\u00d0E\u00c9\u00c8\u011a\u00ca\u00cb\u0118FG\u011eH\u0131I\u00cd\u00cc\u0130\u00ce\u00cfJKL\u0141MN\u0143\u0147\u00d1O\u00d3\u00d2\u00d4PQR\u0158S\u015a\u0160\u015eT\u0164U\u00da\u00d9\u016e\u00db\u00dcVWXY\u00ddZ\u0179\u017b\u017d\u00de\u00c6\u0152\u00d8\u00d5\u00c5\u00c4\u00d6".split("").map(function(b){return b+b.toLowerCase()}).join("");var a={};W("A\u00c1\u00c0\u00c2\u00c3\u00c4,C\u00c7,E\u00c9\u00c8\u00ca\u00cb,I\u00cd\u00cc\u0130\u00ce\u00cf,O\u00d3\u00d2\u00d4\u00d5\u00d6,S\u00df,U\u00da\u00d9\u00db\u00dc".split(","),
function(b){var c=b.charAt(0);W(b.slice(1).split(""),function(d){a[d]=c;a[d.toLowerCase()]=c.toLowerCase()})});s[Ia]=j;s[La]=a})();Pa("any,all,none,count,find,findAll,isEmpty");Pa("sum,average,min,max,least,most",j);sa("map,reduce,size",N);
