var Sugar;
(function(){var l=function(a,b,c){for(var d in c)if(c.hasOwnProperty(d)&&!a.prototype[d])if(b)a.prototype[d]=c[d];else a[d]=c[d]},r=function(a,b,c){for(var d in c)if(c.hasOwnProperty(d))a.prototype[d]=U(a.prototype[d],c[d],b)},U=function(a,b,c){return function(){return a&&(c===true||c.apply(this,arguments))?a.apply(this,arguments):b.apply(this,arguments)}},t=function(a){if(typeof a[0]==="object")return a;for(var b={},c=Array.prototype.slice.call(arguments,1),d=0;d<a.length;d++)b[c[d]]=a[d];return[b]},
z=function(a,b){if(typeof a=="object"&&typeof b=="object"){var c=false,d;for(d in a)if(a.hasOwnProperty(d)){if(!z(a[d],b[d]))return false;c=true}if(!c)for(d in b)if(b.hasOwnProperty(d))return false;return true}else return a===b},o=function(a,b,c,d){return Object.isRegExp(b)?b.test(a):Object.isFunction(b)?b.apply(c,[a].concat(d)):typeof b==="object"?z(b,a):b!==undefined?b===a:!!a},u=function(a,b,c,d){return Object.isFunction(b)?b.apply(c,[a].concat(d)):b===undefined?a:a[b]},A=function(a,b,c){var d=
b==="max";b=b==="min";var e=d?-Infinity:Infinity,h=[],f;for(f in a)if(a.hasOwnProperty(f)){var i=a[f],g=u(i,c);if(!(g===undefined||g===null))if(g===e)h.push(i);else if(d&&g>e||b&&g<e){h=[i];e=g}}return h},J=function(a){var b=this;v(a,function(c,d){b[c]=d})},v=function(a,b){var c=0,d;for(d in a)if(a.hasOwnProperty(d)){b.call(a,d,a[d],c);c++}};l(Object,false,{isObject:function(a){return a===null||a===undefined||arguments.length===0?false:Object.prototype.toString.call(a)==="[object Object]"},create:function(a){return new J(a)}});
var V=new J({keys:function(a){var b=[];v(this,function(c){b.push(c);a&&a.call(this,c)});return b},values:function(a){var b=[];v(this,function(c,d){b.push(d);a&&a.call(this,d)});return b},each:function(a){v(this,function(b,c){a&&a.call(this,b,c)})},merge:function(){for(var a=0;a<arguments.length;a++){var b=arguments[a],c;for(c in b)if(b.hasOwnProperty(c))this[c]=b[c]}return this},clone:function(){var a={};v(this,function(b,c){a[b]=Object.isObject(c)||Object.isArray(c)?Object.clone(c):c});return a},
empty:function(){return z(this,{})},equals:function(a){return z(this,a)}});RegExp.NPCGSupport=/()??/.exec("")[1]===undefined;l(RegExp,false,{escape:function(a){return a.replace(/([/'*+?|()\[\]{}.^$])/g,"\\$1")}});var K=function(a,b,c){c=Math[c];var d=Math.pow(10,Math.abs(b||0));if(b<0)d=1/d;return c(a*d)/d};l(Number,true,{toNumber:function(){return parseFloat(this,10)},ceil:function(a){return K(this,a,"ceil")},floor:function(a){return K(this,a,"floor")},abs:function(){return Math.abs(this)},pow:function(a){if(a===
undefined||a==null)a=1;return Math.pow(this,a)},round:function(a){return K(this,a,"round")},chr:function(){return String.fromCharCode(this)},odd:function(){return!this.multipleOf(2)},even:function(){return this.multipleOf(2)},multipleOf:function(a){return this%a===0},upto:function(a,b){for(var c=[],d=parseInt(this);d<=a;d++){c.push(d);b&&b.call(this,d)}return c},downto:function(a,b){for(var c=[],d=parseInt(this);d>=a;d--){c.push(d);b&&b.call(this,d)}return c},times:function(a){if(a)for(var b=0;b<
this;b++)a.call(this,b);return this.toNumber()},ordinalize:function(){var a;if(this>=11&&this<=13)a="th";else switch(this%10){case 1:a="st";break;case 2:a="nd";break;case 3:a="rd";break;default:a="th"}return this.toString()+a},pad:function(a,b){var c=this.toNumber()===0?"":this.toString().replace(/^-/,"");c=c.padLeft(a-c.length,"0");if(b||this<0)c=(this<0?"-":"+")+c;return c},format:function(a,b){a=a||",";b=b||".";var c=this.toString().split("."),d=c[0];c=c.length>1?b+c[1]:"";for(var e=/(\d+)(\d{3})/;e.test(d);)d=
d.replace(e,"$1"+a+"$2");return d+c},hex:function(){return this.toString(16)},empty:function(){return false}});var s,n,p,w,B,C,W=String.prototype.match,D=["\u00e0a`","\u0101a-","\u00e1a'","\u01ceav","\u00e4a:","\u0103au","\u00e2a^","\u00e5ao","\u00e3a~","\u0107c'","\u010dcv","\u0109c^","\u010bc.","\u00e7c,","\u010fdv","\u0111d-","\u00e8e`","\u0113e-","\u00e9e'","\u011bev","\u00ebe:","\u0115eu","\u00eae^","\u011fgu","\u00eci`","\u012bi-","\u00edi'","\u01d0iv","\u00efi:","\u012diu","\u00eei^","\u0129i~",
"\u013al`","\u013el'","\u0142l/","\u0148nv","\u0144n'","\u00f1n~","\u00f2o`","\u014do-","\u00f3o'","\u01d2ov","\u00f6o:","\u014fou","\u00f4o^","\u00f5o~","\u00f8o/",'\u0151o"',"\u0159rv","\u0155r'","\u0161sv","\u015fs,","\u015bs'","\u0165t'","\u0163t,","\u00f9u`","\u016bu-","\u00fau'","\u01d4uv","\u00fcu:","\u016duu","\u00fbu^","\u016fuo","\u01d8u':","\u01d6u-:","\u00fdy'","\u00ffy:","\u0177y^","\u017ezv","\u017az'","\u017cz."],L=[{full:"\u3000",half:" ",type:"p"},{full:"\u3001",half:"\uff64",type:"p"},
{full:"\u3002",half:"\uff61",type:"p"},{full:"\uff0c",half:",",type:"p"},{full:"\uff0e",half:".",type:"p"},{full:"\u30fb",half:"\uff65",type:"p"},{full:"\uff1a",half:":",type:"p"},{full:"\uff1b",half:";",type:"p"},{full:"\uff1f",half:"?",type:"p"},{full:"\uff01",half:"!",type:"p"},{full:"\u2018",half:"'",type:"p"},{full:"\u2019",half:"'",type:"p"},{full:"\u201c",half:'"',type:"p"},{full:"\u201d",half:'"',type:"p"},{full:"\u30fc",half:"\uff70",type:"p"},{full:"\uff5e",half:"~",type:"p"},{full:"\u309b",
half:"\uff9e",type:"s"},{full:"\u309c",half:"\uff9f",type:"s"},{full:"\uff3e",half:"^",type:"s"},{full:"\u2010",half:"-",type:"s"},{full:"\uff0f",half:"/",type:"s"},{full:"\uff5c",half:"|",type:"s"},{full:"\uff08",half:"(",type:"s"},{full:"\uff09",half:")",type:"s"},{full:"\uff3b",half:"[",type:"s"},{full:"\uff3d",half:"]",type:"s"},{full:"\uff5b",half:"{",type:"s"},{full:"\uff5d",half:"}",type:"s"},{full:"\u300c",half:"\uff62",type:"s"},{full:"\u300d",half:"\uff63",type:"s"},{full:"\u3008",half:"<",
type:"s"},{full:"\u3009",half:">",type:"s"},{full:"\u300a",half:"\u00ab",type:"s"},{full:"\u300b",half:"\u00bb",type:"s"},{full:"\uff0b",half:"+",type:"s"},{full:"\uff0d",half:"-",type:"s"},{full:"\uff1d",half:"=",type:"s"},{full:"\uff1c",half:"<",type:"s"},{full:"\uff1e",half:">",type:"s"},{full:"\u2103",half:"\u00b0C",type:"s"},{full:"\uffe5",half:"\u00a5",type:"s"},{full:"\uff04",half:"$",type:"s"},{full:"\uffe0",half:"\u00a2",type:"s"},{full:"\uffe1",half:"\u00a3",type:"s"},{full:"\uff05",half:"%",
type:"s"},{full:"\uff03",half:"#",type:"s"},{full:"\uff06",half:"&",type:"s"},{full:"\uff0a",half:"*",type:"s"},{full:"\uff20",half:"@",type:"s"},{full:"\uff10",half:"0",type:"n"},{full:"\uff11",half:"1",type:"n"},{full:"\uff12",half:"2",type:"n"},{full:"\uff13",half:"3",type:"n"},{full:"\uff14",half:"4",type:"n"},{full:"\uff15",half:"5",type:"n"},{full:"\uff16",half:"6",type:"n"},{full:"\uff17",half:"7",type:"n"},{full:"\uff18",half:"8",type:"n"},{full:"\uff19",half:"9",type:"n"},{full:"\uff21",
half:"A",type:"a"},{full:"\uff22",half:"B",type:"a"},{full:"\uff23",half:"C",type:"a"},{full:"\uff24",half:"D",type:"a"},{full:"\uff25",half:"E",type:"a"},{full:"\uff26",half:"F",type:"a"},{full:"\uff27",half:"G",type:"a"},{full:"\uff28",half:"H",type:"a"},{full:"\uff29",half:"I",type:"a"},{full:"\uff2a",half:"J",type:"a"},{full:"\uff2b",half:"K",type:"a"},{full:"\uff2c",half:"L",type:"a"},{full:"\uff2d",half:"M",type:"a"},{full:"\uff2e",half:"N",type:"a"},{full:"\uff2f",half:"O",type:"a"},{full:"\uff30",
half:"P",type:"a"},{full:"\uff31",half:"Q",type:"a"},{full:"\uff32",half:"R",type:"a"},{full:"\uff33",half:"S",type:"a"},{full:"\uff34",half:"T",type:"a"},{full:"\uff35",half:"U",type:"a"},{full:"\uff36",half:"V",type:"a"},{full:"\uff37",half:"W",type:"a"},{full:"\uff38",half:"X",type:"a"},{full:"\uff39",half:"Y",type:"a"},{full:"\uff3a",half:"Z",type:"a"},{full:"\uff41",half:"a",type:"a"},{full:"\uff42",half:"b",type:"a"},{full:"\uff43",half:"c",type:"a"},{full:"\uff44",half:"d",type:"a"},{full:"\uff45",
half:"e",type:"a"},{full:"\uff46",half:"f",type:"a"},{full:"\uff47",half:"g",type:"a"},{full:"\uff48",half:"h",type:"a"},{full:"\uff49",half:"i",type:"a"},{full:"\uff4a",half:"j",type:"a"},{full:"\uff4b",half:"k",type:"a"},{full:"\uff4c",half:"l",type:"a"},{full:"\uff4d",half:"m",type:"a"},{full:"\uff4e",half:"n",type:"a"},{full:"\uff4f",half:"o",type:"a"},{full:"\uff50",half:"p",type:"a"},{full:"\uff51",half:"q",type:"a"},{full:"\uff52",half:"r",type:"a"},{full:"\uff53",half:"s",type:"a"},{full:"\uff54",
half:"t",type:"a"},{full:"\uff55",half:"u",type:"a"},{full:"\uff56",half:"v",type:"a"},{full:"\uff57",half:"w",type:"a"},{full:"\uff58",half:"x",type:"a"},{full:"\uff59",half:"y",type:"a"},{full:"\uff5a",half:"z",type:"a"},{full:"\u30a1",half:"\uff67",type:"k"},{full:"\u30a2",half:"\uff71",type:"k"},{full:"\u30a3",half:"\uff68",type:"k"},{full:"\u30a4",half:"\uff72",type:"k"},{full:"\u30a5",half:"\uff69",type:"k"},{full:"\u30a6",half:"\uff73",type:"k"},{full:"\u30a7",half:"\uff6a",type:"k"},{full:"\u30a8",
half:"\uff74",type:"k"},{full:"\u30a9",half:"\uff6b",type:"k"},{full:"\u30aa",half:"\uff75",type:"k"},{full:"\u30ab",half:"\uff76",type:"k"},{full:"\u30ac",half:"\uff76\uff9e",type:"k"},{full:"\u30ad",half:"\uff77",type:"k"},{full:"\u30ae",half:"\uff77\uff9e",type:"k"},{full:"\u30af",half:"\uff78",type:"k"},{full:"\u30b0",half:"\uff78\uff9e",type:"k"},{full:"\u30b1",half:"\uff79",type:"k"},{full:"\u30b2",half:"\uff79\uff9e",type:"k"},{full:"\u30b3",half:"\uff7a",type:"k"},{full:"\u30b4",half:"\uff7a\uff9e",
type:"k"},{full:"\u30b5",half:"\uff7b",type:"k"},{full:"\u30b6",half:"\uff7b\uff9e",type:"k"},{full:"\u30b7",half:"\uff7c",type:"k"},{full:"\u30b8",half:"\uff7c\uff9e",type:"k"},{full:"\u30b9",half:"\uff7d",type:"k"},{full:"\u30ba",half:"\uff7d\uff9e",type:"k"},{full:"\u30bb",half:"\uff7e",type:"k"},{full:"\u30bc",half:"\uff7e\uff9e",type:"k"},{full:"\u30bd",half:"\uff7f",type:"k"},{full:"\u30be",half:"\uff7f\uff9e",type:"k"},{full:"\u30bf",half:"\uff80",type:"k"},{full:"\u30c0",half:"\uff80\uff9e",
type:"k"},{full:"\u30c1",half:"\uff81",type:"k"},{full:"\u30c2",half:"\uff81\uff9e",type:"k"},{full:"\u30c3",half:"\uff6f",type:"k"},{full:"\u30c4",half:"\uff82",type:"k"},{full:"\u30c5",half:"\uff82\uff9e",type:"k"},{full:"\u30c6",half:"\uff83",type:"k"},{full:"\u30c7",half:"\uff83\uff9e",type:"k"},{full:"\u30c8",half:"\uff84",type:"k"},{full:"\u30c9",half:"\uff84\uff9e",type:"k"},{full:"\u30ca",half:"\uff85",type:"k"},{full:"\u30cb",half:"\uff86",type:"k"},{full:"\u30cc",half:"\uff87",type:"k"},
{full:"\u30cd",half:"\uff88",type:"k"},{full:"\u30ce",half:"\uff89",type:"k"},{full:"\u30cf",half:"\uff8a",type:"k"},{full:"\u30d0",half:"\uff8a\uff9e",type:"k"},{full:"\u30d1",half:"\uff8a\uff9f",type:"k"},{full:"\u30d2",half:"\uff8b",type:"k"},{full:"\u30d3",half:"\uff8b\uff9e",type:"k"},{full:"\u30d4",half:"\uff8b\uff9f",type:"k"},{full:"\u30d5",half:"\uff8c",type:"k"},{full:"\u30d6",half:"\uff8c\uff9e",type:"k"},{full:"\u30d7",half:"\uff8c\uff9f",type:"k"},{full:"\u30d8",half:"\uff8d",type:"k"},
{full:"\u30d9",half:"\uff8d\uff9e",type:"k"},{full:"\u30da",half:"\uff8d\uff9f",type:"k"},{full:"\u30db",half:"\uff8e",type:"k"},{full:"\u30dc",half:"\uff8e\uff9e",type:"k"},{full:"\u30dd",half:"\uff8e\uff9f",type:"k"},{full:"\u30de",half:"\uff8f",type:"k"},{full:"\u30df",half:"\uff90",type:"k"},{full:"\u30e0",half:"\uff91",type:"k"},{full:"\u30e1",half:"\uff92",type:"k"},{full:"\u30e2",half:"\uff93",type:"k"},{full:"\u30e3",half:"\uff6c",type:"k"},{full:"\u30e4",half:"\uff94",type:"k"},{full:"\u30e5",
half:"\uff6d",type:"k"},{full:"\u30e6",half:"\uff95",type:"k"},{full:"\u30e7",half:"\uff6e",type:"k"},{full:"\u30e8",half:"\uff96",type:"k"},{full:"\u30e9",half:"\uff97",type:"k"},{full:"\u30ea",half:"\uff98",type:"k"},{full:"\u30eb",half:"\uff99",type:"k"},{full:"\u30ec",half:"\uff9a",type:"k"},{full:"\u30ed",half:"\uff9b",type:"k"},{full:"\u30ef",half:"\uff9c",type:"k"},{full:"\u30f2",half:"\uff66",type:"k"},{full:"\u30f3",half:"\uff9d",type:"k"}],M=[{hira:"\u3041",kata:"\u30a1"},{hira:"\u3042",
kata:"\u30a2"},{hira:"\u3043",kata:"\u30a3"},{hira:"\u3044",kata:"\u30a4"},{hira:"\u3045",kata:"\u30a5"},{hira:"\u3046",kata:"\u30a6"},{hira:"\u3047",kata:"\u30a7"},{hira:"\u3048",kata:"\u30a8"},{hira:"\u3049",kata:"\u30a9"},{hira:"\u304a",kata:"\u30aa"},{hira:"\u304b",kata:"\u30ab"},{hira:"\u304c",kata:"\u30ac"},{hira:"\u304d",kata:"\u30ad"},{hira:"\u304e",kata:"\u30ae"},{hira:"\u304f",kata:"\u30af"},{hira:"\u3050",kata:"\u30b0"},{hira:"\u3051",kata:"\u30b1"},{hira:"\u3052",kata:"\u30b2"},{hira:"\u3053",
kata:"\u30b3"},{hira:"\u3054",kata:"\u30b4"},{hira:"\u3055",kata:"\u30b5"},{hira:"\u3056",kata:"\u30b6"},{hira:"\u3057",kata:"\u30b7"},{hira:"\u3058",kata:"\u30b8"},{hira:"\u3059",kata:"\u30b9"},{hira:"\u305a",kata:"\u30ba"},{hira:"\u305b",kata:"\u30bb"},{hira:"\u305c",kata:"\u30bc"},{hira:"\u305d",kata:"\u30bd"},{hira:"\u305e",kata:"\u30be"},{hira:"\u305f",kata:"\u30bf"},{hira:"\u3060",kata:"\u30c0"},{hira:"\u3061",kata:"\u30c1"},{hira:"\u3062",kata:"\u30c2"},{hira:"\u3063",kata:"\u30c3"},{hira:"\u3064",
kata:"\u30c4"},{hira:"\u3065",kata:"\u30c5"},{hira:"\u3066",kata:"\u30c6"},{hira:"\u3067",kata:"\u30c7"},{hira:"\u3068",kata:"\u30c8"},{hira:"\u3069",kata:"\u30c9"},{hira:"\u306a",kata:"\u30ca"},{hira:"\u306b",kata:"\u30cb"},{hira:"\u306c",kata:"\u30cc"},{hira:"\u306d",kata:"\u30cd"},{hira:"\u306e",kata:"\u30ce"},{hira:"\u306f",kata:"\u30cf"},{hira:"\u3070",kata:"\u30d0"},{hira:"\u3071",kata:"\u30d1"},{hira:"\u3072",kata:"\u30d2"},{hira:"\u3073",kata:"\u30d3"},{hira:"\u3074",kata:"\u30d4"},{hira:"\u3075",
kata:"\u30d5"},{hira:"\u3076",kata:"\u30d6"},{hira:"\u3077",kata:"\u30d7"},{hira:"\u3078",kata:"\u30d8"},{hira:"\u3079",kata:"\u30d9"},{hira:"\u307a",kata:"\u30da"},{hira:"\u307b",kata:"\u30db"},{hira:"\u307c",kata:"\u30dc"},{hira:"\u307d",kata:"\u30dd"},{hira:"\u307e",kata:"\u30de"},{hira:"\u307f",kata:"\u30df"},{hira:"\u3080",kata:"\u30e0"},{hira:"\u3081",kata:"\u30e1"},{hira:"\u3082",kata:"\u30e2"},{hira:"\u3083",kata:"\u30e3"},{hira:"\u3084",kata:"\u30e4"},{hira:"\u3085",kata:"\u30e5"},{hira:"\u3086",
kata:"\u30e6"},{hira:"\u3087",kata:"\u30e7"},{hira:"\u3088",kata:"\u30e8"},{hira:"\u3089",kata:"\u30e9"},{hira:"\u308a",kata:"\u30ea"},{hira:"\u308b",kata:"\u30eb"},{hira:"\u308c",kata:"\u30ec"},{hira:"\u308d",kata:"\u30ed"},{hira:"\u308e",kata:"\u30ee"},{hira:"\u308f",kata:"\u30ef"},{hira:"\u3090",kata:"\u30f0"},{hira:"\u3091",kata:"\u30f1"},{hira:"\u3092",kata:"\u30f2"},{hira:"\u3093",kata:"\u30f3"}],N=function(a){if(!a)return{a:true,n:true,k:true,s:true,p:true};var b={};if(a.length<6)for(var c=
0;c<a.length;c++)b[a.charAt(c)]=true;else{if(a==="alphabet")b.a=true;if(a==="numbers")b.n=true;if(a==="katakana")b.k=true;if(a==="special")b.s=true;if(a==="punctuation")b.p=true}return b},O=function(a,b,c,d){b=b||0;c=c||" ";d=d||"both";for(var e=0;e<b;e++){if(d==="left"||d==="both")a=c+a;if(d==="right"||d==="both")a+=c}return a.toString()};l(String,true,{escapeRegExp:function(){return RegExp.escape(this)},capitalize:function(){return this.substr(0,1).toUpperCase()+this.substr(1).toLowerCase()},trim:function(){return this.trimLeft().trimRight()},
trimLeft:function(){return this.replace(/^[\s\u3000][\s\u3000]*/,"")},trimRight:function(){return this.replace(/[\s\u3000][\s\u3000]*$/,"")},pad:function(a,b){return this.padLeft(a,b).padRight(a,b)},padLeft:function(a,b){return O(this,a,b,"left")},padRight:function(a,b){return O(this,a,b,"right")},repeat:function(a){a=a||0;if(a<0)return this;for(var b="",c=0;c<a;c++)b+=this;return b},each:function(a,b){if(Object.isFunction(a)){b=a;a=/./g}else if(a){if(Object.isString(a))a=RegExp(RegExp.escape(a),
"gi")}else a=/./g;var c=this.match(a)||[];if(b)for(var d=0;d<c.length;d++)c[d]=b.call(this,c[d],d)||c[d];return c},codes:function(a){for(var b=[],c=0;c<this.length;c++){var d=this.charCodeAt(c);b.push(d);a&&a.call(this,d,c)}return b},chars:function(a){return this.trim().each(a)},words:function(a){return this.trim().each(/\S+/g,a)},lines:function(a){return this.trim().each(/^.*$/gm,a)},paragraphs:function(a){var b=this.trim().split(/[\r\n]{2,}/);return b=b.map(function(c){if(a)var d=a.call(c);return d?
d:c})},normalize:function(){var a=this.toString(),b;for(b in s)if(s.hasOwnProperty(b))a=a.replace(s[b],b);return a},accent:function(a){a=a||"";var b=this.toString();return n[a]&&n[a][this]?n[a][b]:b},startsWith:function(a,b){if(b===undefined)b=true;var c=Object.isRegExp(a)?a.source.replace("^",""):RegExp.escape(a);return RegExp("^"+c,b?"":"i").test(this)},endsWith:function(a,b){if(b===undefined)b=true;var c=Object.isRegExp(a)?a.source.replace("$",""):RegExp.escape(a);return RegExp(c+"$",b?"":"i").test(this)},
empty:function(){return this.trim().length===0},has:function(a){return this.search(a)!==-1},insert:function(a,b){b=b||0;if(b<0)b=this.length+b+1;if(b<0||b>this.length)return this;return this.substr(0,b)+a+this.substr(b)},hankaku:function(a){a=N(a);for(var b="",c=0;c<this.length;c++){var d=this.charAt(c);b+=w[d]&&a[w[d].type]?w[d].half:d}return b},zenkaku:function(a){a=N(a);for(var b="",c=0;c<this.length;c++){var d=this.charAt(c),e=this.charAt(c+1);if(e&&p[d+e]){b+=p[d+e].full;c++}else b+=p[d]&&a[p[d].type]?
p[d].full:d}return b},hiragana:function(a){a=a===false?this:this.zenkaku("k");for(var b="",c=0;c<a.length;c++){var d=a.charAt(c);b+=B[d]?B[d].hira:d}return b},katakana:function(){for(var a="",b=0;b<this.length;b++){var c=this.charAt(b);a+=C[c]?C[c].kata:c}return a},toNumber:function(a){var b=this.replace(/,/g,"");return b.match(/\./)?parseFloat(b):parseInt(b,a||10)},reverse:function(){return this.split("").reverse().join("")},compact:function(){return this.replace(/[\r\n]/g,"").trim().replace(/([\s\u3000])+/g,
"$1")},at:function(){for(var a=[],b=0;b<arguments.length;b++){var c=arguments[b];if(c<0)c=this.length+c;a.push(this.charAt(c))}return arguments.length>1?a:a.first()||""},first:function(a){a=a===undefined?1:a;return this.substr(0,a)},last:function(a){a=a===undefined?1:a;return this.substr(this.length-a<0?0:this.length-a)},from:function(a){a=a===undefined?0:a;if(a<0)a=this.length+a;return this.substr(a)},to:function(a){a=a===undefined?this.length:a;if(a<0)a=this.length+a;return this.substr(0,a+1)},
toDate:function(){return Date.create(this.toString())},dasherize:function(){return this.replace(/([a-z])([A-Z])/g,"$1-$2").replace(/_/g,"-").toLowerCase()},underscore:function(){return this.replace(/([a-z])([A-Z])/g,"$1_$2").replace(/-/g,"_").toLowerCase()},camelize:function(a){a=a==="lower";for(var b=this.dasherize().split("-"),c="",d=0;d<b.length;d++)c+=a&&d===0?b[d].toLowerCase():b[d].substr(0,1).toUpperCase()+b[d].substr(1).toLowerCase();return c},titleize:function(){return this.trim().words(function(a){return a.capitalize()}).join(" ")},
isKatakana:function(){return!!this.trim().match(/^[\u30A0-\u30FF\uFF61-\uFF9F\s]+$/)},hasKatakana:function(){return!!this.match(/[\u30A0-\u30FF\uFF61-\uFF9F]/)},isHiragana:function(){return!!this.trim().match(/^[\u3040-\u309F\u30FB-\u30FC\s]+$/)},hasHiragana:function(){return!!this.match(/[\u3040-\u309F\u30FB-\u30FC]/)},isKana:function(){return!!this.trim().match(/^[\u3040-\u30FF\uFF61-\uFF9F\s]+$/)},hasKana:function(){return this.hasHiragana()||this.hasKatakana()},isHan:function(){return!!this.trim().match(/^[\u4E00-\u9FFF\uF900-\uFAFF\s]+$/)},
hasHan:function(){return!!this.match(/[\u4E00-\u9FFF\uF900-\uFAFF]/)},isHangul:function(){return!!this.match(/^[\uAC00-\uD7AF\s]+$/)},hasHangul:function(){return!!this.match(/[\uAC00-\uD7AF\s]/)},stripTags:function(){args=arguments.length>0?arguments:[""];for(var a=this.toString(),b=0;b<args.length;b++){var c=RegExp("</?"+args[b].escapeRegExp()+"[^<>]*>","gi");a=a.replace(c,"")}return a},removeTags:function(){var a=this.toString();if(arguments.length==0){a=a.replace(/<.+?\/>/g,"");a=a.replace(/<.+?>.*<\/.+?>/g,
"")}else for(var b=0;b<arguments.length;b++){var c=arguments[b].escapeRegExp();a=a.replace(RegExp("<"+c+"[^<>]*?/>","gi"),"");a=a.replace(RegExp("<"+c+"[^<>]*>.*?</"+c+">","gi"),"")}return a},toObject:function(a,b){var c={};this.split(a||"&").each(function(d){var e=d.split(b||"=");d=e[0];var h=e[1];if(e=parseInt(e[1]))h=e;else if(h==="true")h=true;else if(h==="false")h=false;c[d]=h});return c}});r(String,function(a){return!Object.isRegExp(a)},{split:function(a,b){var c=[],d=0,e=(a.ignoreCase?"i":
"")+(a.multiline?"m":"")+(a.sticky?"y":"");a=RegExp(a.source,e+"g");var h,f,i;RegExp.NPCGSupport||(h=RegExp("^"+a.source+"$(?!\\s)",e));if(b===undefined||+b<0)b=Infinity;else{b=Math.floor(+b);if(!b)return[]}for(;f=a.exec(this);){e=f.index+f[0].length;if(e>d){c.push(this.slice(d,f.index));!RegExp.NPCGSupport&&f.length>1&&f[0].replace(h,function(){for(var g=1;g<arguments.length-2;g++)if(arguments[g]===undefined)f[g]=undefined});f.length>1&&f.index<this.length&&Array.prototype.push.apply(c,f.slice(1));
i=f[0].length;d=e;if(c.length>=b)break}a.lastIndex===f.index&&a.lastIndex++}if(d===this.length){if(i||!a.test(""))c.push("")}else c.push(this.slice(d));return c.length>b?c.slice(0,b):c}});r(String,function(a){return RegExp.NPCGSupport||a.global},{match:function(){var a=W.apply(this,arguments);if(a)for(var b=1;b<a.length;b++)if(a[b]==="")a[b]=undefined;return a}});l(String,true,{isKanji:String.prototype.isHan,hasKanji:String.prototype.hasHan});r(Array,true,{forEach:function(a,b){for(var c=0,d=this.length;c<
d;c++)a.call(b,this[c],c,this)},reduce:function(a,b){for(var c=b===undefined?this[0]:b,d=b?0:1,e=this.length;d<e;d++)c=a.call(null,c,this[d],d,this);return c},reduceRight:function(a,b){for(var c=b===undefined?this[this.length-1]:b,d=b?this.length-1:this.length-2;d>=0;d--)c=a.call(null,c,this[d],d,this);return c}});r(Array,function(a){return!Object.isObject(a)&&!Object.isFunction(a)},{indexOf:function(a,b){if(b<0)b=this.length+b;else if(b===undefined)b=0;if(b>=this.length)return-1;for(var c=b,d=this.length;c<
d;c++)if(o(this[c],a,this,[c,this]))return c;return-1},lastIndexOf:function(a,b){if(b<0)b=this.length+b;else if(b===undefined||b>this.length)b=this.length-1;for(var c=b;c>=0;c--)if(o(this[c],a,this,[c,this]))return c;return-1}});r(Array,function(a){return Object.isFunction(a)},{every:function(a,b){for(var c=0,d=this.length;c<d;c++)if(!o(this[c],a,b,[c,this]))return false;return true},some:function(a,b){for(var c=0,d=this.length;c<d;c++)if(o(this[c],a,b,[c,this]))return true;return false},filter:function(a,
b){for(var c=[],d=0,e=this.length;d<e;d++)o(this[d],a,b,[d,this])&&c.push(this[d]);return c},map:function(a,b){for(var c=[],d=0,e=this.length;d<e;d++)c.push(u(this[d],a,b,[d,this]));return c}});l(Array,true,{find:function(a){a=this.findAllFromIndex(0,a,1);return a.length>0?a[0]:undefined},findAll:function(a,b){return this.findAllFromIndex(0,a,b)},findFromIndex:function(a,b){var c=this.findAllFromIndex(a,b,1);return c.length>0?c[0]:undefined},findAllFromIndex:function(a,b,c){var d=[];a=a!==0?this.slice(a).concat(this.slice(0,
a)):this;for(var e=0,h=a.length;e<h;e++){o(a[e],b,a,e)&&d.push(a[e]);if(c&&d.length===c)break}return d},count:function(a){return this.findAllFromIndex(0,a).length},none:function(a){return!this.any(a)},remove:function(a){var b=this;return this.findAllFromIndex(0,function(c,d){return!o(c,a,b,[d,b])})},removeIndex:function(a,b){if(a===undefined)return this;if(b===undefined)b=a;return this.findAllFromIndex(0,function(c,d){return d<a||d>b})},unique:function(){var a=[];this.each(function(b){a.indexOf(b)===
-1&&a.push(b)});return a},union:function(a){return this.concat(a).unique()},intersect:function(a){var b=[];Object.isArray(a)||(a=[a]);this.each(function(c){a.indexOf(c)!==-1&&b.push(c)});return b.unique()},subtract:function(a){var b=[];Object.isArray(a)||(a=[a]);this.each(function(c){a.indexOf(c)===-1&&b.push(c)});return b},at:function(){var a=Array.prototype.slice.call(arguments).map(function(b){return b<0?this.length+b:b},this);return(a.length>1?this.findAllFromIndex:this.findFromIndex).call(this,
0,function(b,c){return a.has(c)})},first:function(a){if(a===undefined)return this[0];if(a<0)a=0;return this.slice(0,a)},last:function(a){if(a===undefined)return this[this.length-1];return this.slice(this.length-a<0?0:this.length-a)},from:function(a){a=a===undefined?0:a;return this.slice(a)},to:function(a){a=a===undefined?this.length-1:a;if(a<0)a=this.length+a;return this.slice(0,a+1)},min:function(a){return A(this,"min",a).unique()},max:function(a){return A(this,"max",a).unique()},least:function(a){a=
A(this.groupBy(a),"min","length").flatten();return a.length===this.length?[]:a.unique()},most:function(a){a=A(this.groupBy(a),"max","length").flatten();return a.length===this.length?[]:a.unique()},sum:function(a){a=a?this.map(a):this;return a.length>0?a.reduce(function(b,c){return b+c}):0},average:function(a){a=a?this.map(a):this;return a.length>0?a.sum()/a.length:0},groupBy:function(a){var b={};this.each(function(c){var d=u(c,a);b[d]||(b[d]=[]);b[d].push(c)});return b},inGroups:function(a,b){var c=
arguments.length>1,d=this,e=[],h=Math.ceil(this.length/a);(0).upto(a-1,function(f){f=f*h;var i=d.slice(f,f+h);c&&i.length<h&&(h-i.length).times(function(){i=i.add(b)});e.push(i)});return e},inGroupsOf:function(a,b){if(this.length===0||a===0)return this;if(a===undefined)a=1;if(b===undefined)b=null;var c=[],d=null;this.each(function(e,h){if(h%a===0){d&&c.push(d);d=[]}if(e===undefined)e=b;d.push(e)});if(!this.length.multipleOf(a)){(a-this.length%a).times(function(){d.push(b)});this.length+=a-this.length%
a}d.length>0&&c.push(d);return c},split:function(a){var b=this,c=[],d=0;this.each(function(e,h){if(Object.isFunction(a)?a(e):e===a){var f=b.slice(d,h);f.length>0&&c.push(f);d=h+1}});d<this.length&&c.push(this.slice(d,this.length));return c},compact:function(){return this.remove(function(a,b,c){if(Object.isArray(a)){c[b]=a.compact();return false}else return a===undefined||a===null||typeof a==="number"&&isNaN(a)})},empty:function(){return this.compact().length==0},flatten:function(){var a=[];this.each(function(b){if(Object.isArray(b))a=
a.concat(b.flatten());else a.push(b)});return a},sortBy:function(a,b){this.sort(function(c,d){var e=u(c,a),h=u(d,a),f=typeof e=="number";return f&&b?h-e:f&&!b?e-h:e===h?0:b?e<h?1:-1:e<h?-1:1});return this},addAtIndex:function(a,b){if(a<0)a=this.length+a+1;if(!Object.isNumber(a)||isNaN(a)||a<0||a>this.length)a=this.length;return this.slice(0,a).concat(b).concat(this.slice(a))},randomize:function(){for(var a=this.concat(),b,c,d=a.length;d;b=parseInt(Math.random()*d),c=a[--d],a[d]=a[b],a[b]=c);return a}});
l(Array,true,{collect:Array.prototype.map,shuffle:Array.prototype.randomize,each:Array.prototype.forEach,all:Array.prototype.every,any:Array.prototype.some,has:Array.prototype.some,add:Array.prototype.concat});var E,F,G=["january","february","march","april","may","june","july","august","september","october","november","december"],H=["sunday","monday","tuesday","wednesday","thursday","friday","saturday"],P=["zero","one","two","three","four","five","six","seven","eight","nine","ten"],Q=[{reg:"(\\d{4})",
to:["year"]},{reg:"(\\d{4})[-/.](\\d{1,2})",to:["year","month"]},{reg:"([+-])?(\\d{4})[-/.]?(\\d{1,2})[-/.]?(\\d{1,2})",to:["year_sign","year","month","day"]},{reg:"(\\d{2})-?(\\d{2})-?(\\d{2})",to:["year","month","day"]},{reg:"(\\d{1,2})[\\-/.](\\d{1,2})",to:["month","day"],variant:true},{reg:"(\\d{1,2})[\\-/.](\\d{1,2})[\\-/.](\\d{2,4})",to:["month","day","year"],variant:true},{reg:"({MONTHS})[\\s\\-.](\\d{4})",to:["month","year"]},{reg:"(?:{WEEKDAYS})?\\s*({MONTHS})[\\s\\-.]?(?:(\\d{1,2})(?:st|nd|rd|th)?)?,?[\\s\\-.]?(\\d{2,4})?",
to:["month","day","year"]},{reg:"(\\d{1,2}) ({MONTHS}),? (\\d{4})",to:["day","month","year"]},{reg:"(?:(the|a|{NUMBER}|\\d+) (day|week|month|year)s? (before|after|from)\\s+)?(today|tomorrow|yesterday|{WEEKDAYS})",to:["modifier_amount","modifier_unit","modifier_sign","fuzzy_day"]},{reg:"(a|{NUMBER}|\\d+) (millisecond|second|minute|hour|day|week|month|year)s? (from now|ago)",to:["modifier_amount","modifier_unit","modifier_sign"],relative:true},{reg:"(this|next|last)?\\s*(?:week\\s*)?({WEEKDAYS})",to:["modifier_sign",
"fuzzy_day"]},{reg:"({WEEKDAYS}) (?:of\\s*)?(this|next|last) week",to:["fuzzy_day","modifier_sign"]},{reg:"({MONTHS})(?: (\\d{1,2})(?:st|nd|rd|th)?)? of (this|next|last) (year)",to:["month","day","modifier_sign","modifier_unit"]},{reg:"(?:the\\s)?(first day|last day)?(\\d{1,2}(?:st|nd|rd|th))? of (?:(the|this|next|last) (month)|({MONTHS}))",to:["modifier_edge","day","modifier_sign","modifier_unit","month"]},{reg:"(?:the\\s)?(beginning|end|first day|last day) of (?:(the|this|next|last) (week|month|year)|(\\d{4})|({MONTHS}))",
to:["modifier_edge","modifier_sign","modifier_unit","year","month"]},{reg:"(this|next|last) (week|month|year)",to:["modifier_sign","modifier_unit"],relative:true},{reg:"(midnight|noon)(?: (tonight|today|tomorrow|yesterday|{WEEKDAYS}))?",to:["hour","fuzzy_day"],timeIncluded:true},{reg:"^(?:(\\d{1,2}):?(\\d{2})?:?(\\d{2})?(\\.\\d{1,6})?(am|pm)?(?:(Z)|(?:([+-])(\\d{2})(?::?(\\d{2}))?)?)?)$",to:["hour","minute","second","millisecond","meridian","utc","offset_sign","offset_hours","offset_minutes"],today:true,
timeIncluded:true}],X=[{token:"millisec(?:onds?)?|ms(?:ms)?",pad:3,format:function(a,b){return k(a,"get",b,"Milliseconds")}},{token:"s(?:s|ec(?:onds?)?)?",pad:2,format:function(a,b){return k(a,"get",b,"Seconds")}},{token:"m(?:m|in(?:utes?)?)?",pad:2,caps:true,format:function(a,b){return k(a,"get",b,"Minutes")}},{token:"h(?:h|(?:ours?))?|24hr",pad:2,format:function(a,b){return k(a,"get",b,"Hours")}},{token:"12hr",pad:2,format:function(a,b){var c=k(a,"get",b,"Hours");return c===0?12:c-Math.floor(c/
13)*12}},{token:"d(?:d|(?:ays?))?",pad:2,format:function(a,b){return k(a,"get",b,"Date")}},{token:"dow|weekday(?: short)?",weekdays:true,format:function(a,b){return k(a,"get",b,"Day")}},{token:"MM?",pad:2,caps:true,format:function(a,b){return k(a,"get",b,"Month")+1}},{token:"mon(th)?(?: short)?",months:true,format:function(a,b){return k(a,"get",b,"Month")}},{token:"yy",format:function(a,b){return k(a,"get",b,"FullYear").toString().from(2)}},{token:"yyyy|year",format:function(a,b){return k(a,"get",
b,"FullYear")}},{token:"t{1,2}",meridian:true,format:function(a,b){return k(a,"get",b,"Hours")<12?"am":"pm"}},{token:"tz|timezone",format:function(a){return a.getUTCOffset()}},{token:"iso(tz|timezone)",format:function(a){return a.getUTCOffset(true)}},{token:"ord",format:function(a,b){return k(a,"get",b,"Date").ordinalize()}}],x=[{unit:"year",method:"FullYear",multiplier:function(a){return(365+(a?a.leapYear()?1:0:0.25))*24*60*60*1E3}},{unit:"month",method:"Month",multiplier:function(a){return(a?a.daysInMonth():
30.4375)*24*60*60*1E3}},{unit:"week",method:"Week",multiplier:function(){return 6048E5}},{unit:"day",method:"Date",multiplier:function(){return 864E5}},{unit:"hour",method:"Hours",multiplier:function(){return 36E5}},{unit:"minute",method:"Minutes",multiplier:function(){return 6E4}},{unit:"second",method:"Seconds",multiplier:function(){return 1E3}},{unit:"millisecond",method:"Milliseconds",multiplier:function(){return 1}}],Y=function(a,b){var c={};b.each(function(d,e){var h=a[e+1];if(typeof h==="string")h=
h.toLowerCase();c[d]=h});return c},R=function(a,b){var c,d={},e={},h=false,f=new Date;if(Object.isObject(a)){e=a;f=(new Date).set(a,true)}else if(Object.isNumber(a))f=new Date(a);else if(Object.isDate(a))f=a;else if(Object.isString(a)){a=a.trim().replace(/\.+$/,"").replace(/^now$/,"");Q.each(function(i){if(!c)if(c=a.match(i.reg)){d=i;var g=Y(c,d.to);if(b&&d.variant){i=g.month;g.month=g.day;g.day=i}if(g.year){if(!g.modifier_unit)g.modifier_unit="year";if(g.year.length===2)g.year=Z(g.year.toNumber())}if(g.month){i=
g.month.toNumber();g.month=isNaN(i)?E.indexOf(g.month.to(2)):i-1}if(g.hour==="noon"||g.hour==="midnight"){g.hour=g.hour==="noon"?12:24;if(!e.day&&!g.fuzzy_day)g.fuzzy_day="today"}if(g.fuzzy_day){i=0;var j=g.fuzzy_day;if(j==="yesterday")i=-1;else if(j==="tomorrow")i=1;else if((j=F.indexOf(j.to(2)))!==-1){f.setWeekday(j);i=0;if(g.modifier_sign&&!g.modifier_unit&&!g.modifier_amount)g.modifier_unit="week"}e.year=f.getFullYear();e.month=f.getMonth();e.day=f.getDate()+i}if(g.millisecond)g.millisecond=(parseFloat(g.millisecond,
10)*1E3).round();x.each(function(y){y=y.unit;if(g[y]!==undefined)e[y]=g[y].toNumber()});if(g.meridian)if(g.meridian==="pm"&&g.hour<12)e.hour+=12;if(g.utc||g.offset_hours||g.offset_minutes){h=true;i=0;if(g.offset_hours)i+=g.offset_hours.toNumber()*60;if(g.offset_minutes)i+=g.offset_minutes.toNumber();if(g.offset_sign&&g.offset_sign==="-")i*=-1;e.minute-=i}if(g.modifier_unit&&g.modifier_sign){i=g.modifier_amount||1;j=g.modifier_unit;var m;i=i==="the"||i==="a"?1:(m=P.indexOf(i))!==-1?m:i.toNumber();
if(g.modifier_sign==="before"||g.modifier_sign==="ago"||g.modifier_sign==="last")i*=-1;else if(g.modifier_sign==="this"||g.modifier_sign==="the")i=0;if(j==="year"&&!d.relative)e.year=f.getFullYear();else if(j==="month"&&!d.relative)e.month=f.getMonth();else if(j==="week"&&!d.relative){e.day=f.getDate();j="day";i*=7}if(e[j]===undefined)e[j]=0;e[j]+=i}if(g.modifier_edge){m=g.modifier_edge;if(m==="beginning"||m==="first"||m==="first day"){if(g.modifier_unit==="week"){e.month=f.getMonth();e.weekday=0}else if(g.modifier_unit===
"month"||g.month)e.day=1;if(!m.match(/day/)){e.hour=0;e.minute=0;e.second=0;e.millisecond=0}}else if(m==="end"||m==="last"||m==="last day"){if(g.modifier_unit==="week"){e.month=f.getMonth();e.weekday=6}else if(g.modifier_unit==="month"||g.month)e.day=32-(new Date(f.getFullYear(),e.month,32)).getDate();else if(g.modifier_unit==="year"){e.month=11;e.day=31}if(!m.match(/day/)){e.hour=23;e.minute=59;e.second=59;e.millisecond=999}}}if(g.year_sign&&g.year_sign==="-")e.year*=-1;if(d.today){e.year=f.getFullYear();
e.month=f.getMonth();e.day=f.getDate()}}});if(c)if(d.relative)f.advance(e);else h?f.setUTC(e,true):f.set(e,true);else f=a?new Date(a):new Date}return{date:f,set:e,format:d}},q=function(a,b,c,d,e){var h,f,i=R(b);c=c>0?c:0;if(!i.date.isValid())return false;x.each(function(j){if(i.set[j.unit]!==undefined||i.set[j.unit+"s"]!==undefined){h=j.unit;f=j.multiplier(i.date)-1}});if(i.format.relative)if(b=i.date["beginningOf"+h.capitalize()])b.call(i.date);else{c=c||Math.round(f/2);f=0}f=f||0;a=a.getTime();
b=i.date.getTime();var g=b+f;return d==="after"?e?a-c>b:a>g+c:d==="before"?e?a<g+c:a-c<b:a>=b-c&&a<g+c+1},I=function(a,b,c,d,e){d=d===true?"UTC":"";if(b.date)b.day=b.date;c&&a.setDate(15);x.each(function(f){var i=f.unit;f=f.method;var g=S(b,i,c);if(g!==undefined){if(e){if(i==="week"){g=(b.day||0)+g*7;f="Date"}g=g*e+k(a,"get","",f)}k(a,"set",d,f,g)}});if(!e){var h=S(b,"weekday",c);h!==undefined&&k(a,"set",d,"Weekday",h)}return a},S=function(a,b,c){var d=a[b];if(d===undefined)d=a[b+"s"];if(d===undefined&&
c)switch(b){case "day":d=1;break;case "year":case "week":case "weekday":break;default:d=0}return d},k=function(a,b,c,d,e){return a[b+c+d].call(a,e)},Z=function(a){return Math.round((new Date).getFullYear()/100)*100-Math.round(a/100)*100+a},$=function(a){if(/\w+\s+\w+/.test(a))return null;a=E.indexOf(a.toLowerCase().to(2));return a===-1?null:a},aa=function(a){if(/\w+\s+\w+/.test(a))return null;a=F.indexOf(a.toLowerCase().to(2));return a===-1?null:a},T=function(a,b,c,d){b=Date.create(b);var e={};e[c]=
a;return b[d].call(b,e)},ba=function(a,b){var c=function(){return this*b},d=function(h){return T(this,h,a,"rewind")},e=function(h){return T(this,h,a,"advance")};Number.prototype[a]=c;Number.prototype[a+"s"]=c;Number.prototype[a+"Ago"]=d;Number.prototype[a+"sAgo"]=d;Number.prototype[a+"Before"]=d;Number.prototype[a+"sBefore"]=d;Number.prototype[a+"After"]=e;Number.prototype[a+"sAfter"]=e;Number.prototype[a+"FromNow"]=e;Number.prototype[a+"sFromNow"]=e};l(Date,false,{create:function(a,b){if(arguments.length>=
2&&Object.isNumber(b)){a=t(arguments,"year","month","day","hour","minute","second","millisecond")[0];b=false}return R(a,b).date},DSTOffset:((new Date(2E3,6,1)).getTimezoneOffset()-(new Date(2E3,0,1)).getTimezoneOffset())*60*1E3,AMERICAN_DATE:"{M}/{d}/{yyyy}",AMERICAN_DATETIME:"{M}/{d}/{yyyy} {h}:{mm}{tt}",EUROPEAN_DATE:"{d}/{M}/{yyyy}",INTERNATIONAL_TIME:"{h}:{mm}:{ss}",RFC1123:"{Dow}, {dd} {Mon} {yyyy} {hh}:{mm}:{ss} GMT{tz}",RFC1036:"{Weekday}, {dd}-{Mon}-{yy} {hh}:{mm}:{ss} GMT{tz}",ISO8601_DATE:"{yyyy}-{MM}-{dd}",
ISO8601_DATETIME:"{yyyy}-{MM}-{dd}T{hh}:{mm}:{ss}.{ms}Z"});l(Date,true,{set:function(){var a=t(arguments,"year","month","day","hour","minute","second","millisecond");return I(this,a[0],a[1])},setUTC:function(){var a=t(arguments,"year","month","day","hour","minute","second","millisecond");return I(this,a[0],a[1],true)},setWeekday:function(a){a!==undefined&&this.setDate(this.getDate()+a-this.getDay())},setUTCWeekday:function(a){a!==undefined&&this.setDate(this.getUTCDate()+a-this.getDay())},setWeek:function(a){if(a!==
undefined){this.getDate();this.setMonth(0);this.setDate(a*7+1)}},setUTCWeek:function(a){if(a!==undefined){this.getUTCDate();this.setMonth(0);this.setUTCDate(a*7+1)}},getWeek:function(){var a=new Date(this.getFullYear(),0,1);return Math.ceil((this.getTime()-a.getTime()+1)/6048E5)},getUTCWeek:function(){var a=(new Date).setUTC(this.getUTCFullYear(),0,1,0,0,0,0);return Math.ceil((this.getTime()-a.getTime()+1)/6048E5)},getUTCOffset:function(a){var b=this.getTimezoneOffset(),c=a===true?":":"";if(!b&&a)return"Z";
return Math.round(-b/60).pad(2,true)+c+(b%60).pad(2)},utc:function(){return this.addMinutes(this.getTimezoneOffset())},isUTC:function(){return this.getTimezoneOffset()===0},advance:function(){var a=t(arguments,"year","month","day","hour","minute","second","millisecond");return I(this,a[0],false,false,1,true)},rewind:function(){var a=t(arguments,"year","month","day","hour","minute","second","millisecond");return I(this,a[0],false,false,-1)},isValid:function(){return!isNaN(this.getTime())},isAfter:function(a,
b){return q(this,a,b,"after")},isBefore:function(a,b){return q(this,a,b,"before")},isBetween:function(a,b,c){return q(this,a,c,"after",true)&&q(this,b,c,"before",true)?true:q(this,b,c,"after",true)&&q(this,a,c,"before",true)},leapYear:function(){var a=this.getFullYear();return a%4===0&&a%100!==0||a%400===0},daysInMonth:function(){return 32-(new Date(this.getFullYear(),this.getMonth(),32)).getDate()},format:function(a,b){var c=this;b=b===true?"UTC":"";if(Date[a])a=Date[a];if(!a)return this.toString();
X.each(function(d){if(a)a=a.replace(RegExp("{("+d.token+")(?: (pad))?}",d.caps?"":"i"),function(e,h,f){e=d.format.call(null,c,b);if(d.pad&&(h.length===2||f==="pad"))e=e.pad(d.pad);if(d.weekdays){f=h.toLowerCase();e=(f=f==="dow"||f==="weekday short")?F[e]:H[e];if(h.first().toUpperCase()===h.first())e=e.capitalize()}if(d.months){f=h.toLowerCase();e=(f=f==="mon"||f==="month short")?E[e]:G[e];if(h.first().toUpperCase()===h.first())e=e.capitalize()}if(d.meridian){if(h.length===1)e=e.to(0);if(h.toUpperCase()===
h)e=e.toUpperCase()}return e})});return a},is:function(a,b){var c,d;if(Object.isString(b)){var e=x.find(function(h){return h.unit===b});if(e)b=e.multiplier()}b=b>0?b:0;if(Object.isString(a)){a=a.trim();return a==="future"?this.getTime()>(new Date).getTime():a==="past"?this.getTime()<(new Date).getTime():a==="weekday"?!(this.getDay()===0||this.getDay()===6):a==="weekend"?this.getDay()===0||this.getDay()===6:(d=aa(a))?this.getDay()===d:(c=$(a))?this.getMonth()===c:q(this,a,b)}else{a=Date.create(a);
b=b||0;c=this.getTime();e=a.getTime();return c>=e-b&&c<e+1+b}},resetTime:function(){return this.set({hour:0,minute:0,second:0,millisecond:0})},toISOString:function(){return this.format(Date.ISO8601_DATETIME,true)}});l(Date,false,{ISO8601:Date.ISO8601_DATETIME});l(Date,true,{getWeekday:Date.prototype.getDay,getUTCWeekday:Date.prototype.getUTCDay,iso:Date.prototype.toISOString});r(Function,function(a,b){return b===undefined},{bind:function(a,b){var c=this;return function(){return c.apply(a,b||[])}},
delay:function(a,b){var c=this;setTimeout(function(){return c.apply(this,b||[])},a)}});(function(){["Array","Boolean","Date","Function","Number","String","RegExp"].each(function(a){Object["is"+a]=function(b){return Object.prototype.toString.call(b)==="[object "+a+"]"}});V.each(function(a,b){J.prototype[a]=b;Object[a]=function(c){return b.apply(c,Array.prototype.slice.call(arguments,1))}})})();(function(){B={};C={};for(var a=0;a<M.length;a++){var b=M[a];B[b.kata]=b;C[b.hira]=b}})();(function(){n={};
for(var a=0;a<D.length;a++){var b=D[a],c=b.charAt(0),d=b.charAt(1);b=b.substr(2);n[b]||(n[b]={});n[b][d]=c;n[b][d.toUpperCase()]=c.toUpperCase()}})();(function(){s={};for(var a={},b=0;b<D.length;b++){var c=D[b],d=c.charAt(0);c=c.charAt(1);if(a[c])a[c]+=d;else a[c]=d}for(c in a)if(a.hasOwnProperty(c)){b=a[c];s[c]=RegExp("["+b+"]","g");s[c.toUpperCase()]=RegExp("["+b.toUpperCase()+"]","g")}})();(function(){p={};w={};for(var a=0;a<L.length;a++){var b=L[a];p[b.half]=b;w[b.full]=b}})();(function(){x.each(function(a,
b){var c=a.unit,d=c.capitalize(),e=a.multiplier();Date.prototype[c+"sSince"]=function(h,f){return((this.getTime()-Date.create(h,f).getTime())/e).round()};Date.prototype[c+"sUntil"]=function(h,f){return((Date.create(h,f).getTime()-this.getTime())/e).round()};Date.prototype["add"+d+"s"]=function(h){var f={};f[c]=h;return this.advance(f)};ba(c,e);if(b<3){Date.prototype["isLast"+d]=function(){return this.is("last "+c)};Date.prototype["isThis"+d]=function(){return this.is("this "+c)};Date.prototype["isNext"+
d]=function(){return this.is("next "+c)}}if(b<4){Date.prototype["beginningOf"+d]=function(h){if(h===undefined)h=true;var f={month:0,day:1};switch(c){case "week":f.weekday=0;case "day":f.day=this.getDate();case "month":f.month=this.getMonth()}return this.set(f,h)};Date.prototype["endOf"+d]=function(h){if(h===undefined)h=true;var f=h?{hours:23,minutes:59,seconds:59,milliseconds:999}:{};f.day=this.getDate();f.month=this.getMonth();switch(c){case "year":f.month=11;f.day=31;break;case "month":f.day=this.daysInMonth();
break;case "week":f.weekday=6}return this.set(f,h)}}})})();(function(){E=G.map(function(d){return d.to(2)});F=H.map(function(d){return d.to(2)});var a=G.map(function(d){return d.to(2)+"(?:\\.|"+d.from(3)+")?"}).join("|"),b=H.map(function(d){return d.to(2)+"(?:\\.|"+d.from(3)+")?"}).join("|"),c=P.join("|");Q.each(function(d){var e="^"+d.reg;e=e.replace(/{WEEKDAYS}/,b);e=e.replace(/{MONTHS}/,a);e=e.replace(/{NUMBER}/,c);if(!d.timeIncluded){e+="(?:(?:\\s+|t)(\\d{1,2}):?(\\d{2})?:?(\\d{2})?(\\.\\d{1,6})?(am|pm)?(?:(Z)|(?:([+-])(\\d{2})(?::?(\\d{2}))?)?)?)?$";
d.to=d.to.concat(["hour","minute","second","millisecond","meridian","utc","offset_sign","offset_hours","offset_minutes"])}d.reg=RegExp(e,"i")})})();(function(){["today","yesterday","tomorrow","weekday","weekend","future","past"].concat(H).concat(G).each(function(a){Date.prototype["is"+a.capitalize()]=function(){return this.is(a)}})})()})();
