import { defineInstance } from '../number/namespace';
import * as methods from './methods';

defineInstance('duration', methods.duration);

defineInstance('year', methods.years);
defineInstance('years', methods.years);
defineInstance('month', methods.months);
defineInstance('months', methods.months);
defineInstance('week', methods.weeks);
defineInstance('weeks', methods.weeks);
defineInstance('day', methods.days);
defineInstance('days', methods.days);
defineInstance('hours', methods.hours);
defineInstance('hour', methods.hours);
defineInstance('minute', methods.minutes);
defineInstance('minutes', methods.minutes);
defineInstance('second', methods.seconds);
defineInstance('seconds', methods.seconds);

defineInstance('yearAgo', methods.yearsAgo);
defineInstance('yearsAgo', methods.yearsAgo);
defineInstance('monthAgo', methods.monthsAgo);
defineInstance('monthsAgo', methods.monthsAgo);
defineInstance('weekAgo', methods.weeksAgo);
defineInstance('weeksAgo', methods.weeksAgo);
defineInstance('dayAgo', methods.daysAgo);
defineInstance('daysAgo', methods.daysAgo);
defineInstance('hourAgo', methods.hoursAgo);
defineInstance('hoursAgo', methods.hoursAgo);
defineInstance('minuteAgo', methods.minutesAgo);
defineInstance('minutesAgo', methods.minutesAgo);
defineInstance('secondAgo', methods.secondsAgo);
defineInstance('secondsAgo', methods.secondsAgo);
defineInstance('millisecondAgo', methods.millisecondsAgo);
defineInstance('millisecondsAgo', methods.millisecondsAgo);

defineInstance('yearFromNow', methods.yearsFromNow);
defineInstance('yearsFromNow', methods.yearsFromNow);
defineInstance('monthFromNow', methods.monthsFromNow);
defineInstance('monthsFromNow', methods.monthsFromNow);
defineInstance('weekFromNow', methods.weeksFromNow);
defineInstance('weeksFromNow', methods.weeksFromNow);
defineInstance('dayFromNow', methods.daysFromNow);
defineInstance('daysFromNow', methods.daysFromNow);
defineInstance('hourFromNow', methods.hoursFromNow);
defineInstance('hoursFromNow', methods.hoursFromNow);
defineInstance('minuteFromNow', methods.minutesFromNow);
defineInstance('minutesFromNow', methods.minutesFromNow);
defineInstance('secondFromNow', methods.secondsFromNow);
defineInstance('secondsFromNow', methods.secondsFromNow);
defineInstance('millisecondFromNow', methods.millisecondsFromNow);
defineInstance('millisecondsFromNow', methods.millisecondsFromNow);

defineInstance('yearBefore', methods.yearsBefore);
defineInstance('yearsBefore', methods.yearsBefore);
defineInstance('monthBefore', methods.monthsBefore);
defineInstance('monthsBefore', methods.monthsBefore);
defineInstance('weekBefore', methods.weeksBefore);
defineInstance('weeksBefore', methods.weeksBefore);
defineInstance('dayBefore', methods.daysBefore);
defineInstance('daysBefore', methods.daysBefore);
defineInstance('hourBefore', methods.hoursBefore);
defineInstance('hoursBefore', methods.hoursBefore);
defineInstance('minuteBefore', methods.minutesBefore);
defineInstance('minutesBefore', methods.minutesBefore);
defineInstance('secondBefore', methods.secondsBefore);
defineInstance('secondsBefore', methods.secondsBefore);
defineInstance('millisecondBefore', methods.millisecondsBefore);
defineInstance('millisecondsBefore', methods.millisecondsBefore);

defineInstance('yearAfter', methods.yearsAfter);
defineInstance('yearsAfter', methods.yearsAfter);
defineInstance('monthAfter', methods.monthsAfter);
defineInstance('monthsAfter', methods.monthsAfter);
defineInstance('weekAfter', methods.weeksAfter);
defineInstance('weeksAfter', methods.weeksAfter);
defineInstance('dayAfter', methods.daysAfter);
defineInstance('daysAfter', methods.daysAfter);
defineInstance('hourAfter', methods.hoursAfter);
defineInstance('hoursAfter', methods.hoursAfter);
defineInstance('minuteAfter', methods.minutesAfter);
defineInstance('minutesAfter', methods.minutesAfter);
defineInstance('secondAfter', methods.secondsAfter);
defineInstance('secondsAfter', methods.secondsAfter);
defineInstance('millisecondAfter', methods.millisecondsAfter);
defineInstance('millisecondsAfter', methods.millisecondsAfter);
