import { defineInstance } from '../number/namespace';
import * as methods from './methods';

defineInstance('duration', methods.duration);

defineInstance('year', methods.years);
defineInstance('years', methods.years);
defineInstance('month', methods.months);
defineInstance('months', methods.months);
defineInstance('week', methods.weeks);
defineInstance('weeks', methods.weeks);
defineInstance('day', methods.days);
defineInstance('days', methods.days);
defineInstance('hours', methods.hours);
defineInstance('hour', methods.hours);
defineInstance('minute', methods.minutes);
defineInstance('minutes', methods.minutes);
defineInstance('second', methods.seconds);
defineInstance('seconds', methods.seconds);

defineInstance('yearAgo', methods.yearsAgo);
defineInstance('yearsAgo', methods.yearsAgo);
defineInstance('monthAgo', methods.monthsAgo);
defineInstance('monthsAgo', methods.monthsAgo);
defineInstance('weekAgo', methods.weeksAgo);
defineInstance('weeksAgo', methods.weeksAgo);
defineInstance('dayAgo', methods.daysAgo);
defineInstance('daysAgo', methods.daysAgo);
defineInstance('hourAgo', methods.hoursAgo);
defineInstance('hoursAgo', methods.hoursAgo);
defineInstance('minuteAgo', methods.minutesAgo);
defineInstance('minutesAgo', methods.minutesAgo);
defineInstance('secondAgo', methods.secondsAgo);
defineInstance('secondsAgo', methods.secondsAgo);
defineInstance('millisecondAgo', methods.millisecondsAgo);
defineInstance('millisecondsAgo', methods.millisecondsAgo);

defineInstance('yearFromNow', methods.yearsFromNow);
defineInstance('yearsFromNow', methods.yearsFromNow);
defineInstance('monthFromNow', methods.monthsFromNow);
defineInstance('monthsFromNow', methods.monthsFromNow);
defineInstance('weekFromNow', methods.weeksFromNow);
defineInstance('weeksFromNow', methods.weeksFromNow);
defineInstance('dayFromNow', methods.daysFromNow);
defineInstance('daysFromNow', methods.daysFromNow);
defineInstance('hourFromNow', methods.hoursFromNow);
defineInstance('hoursFromNow', methods.hoursFromNow);
defineInstance('minuteFromNow', methods.minutesFromNow);
defineInstance('minutesFromNow', methods.minutesFromNow);
defineInstance('secondFromNow', methods.secondsFromNow);
defineInstance('secondsFromNow', methods.secondsFromNow);
defineInstance('millisecondFromNow', methods.millisecondsFromNow);
defineInstance('millisecondsFromNow', methods.millisecondsFromNow);
